#!/usr/bin/env node
const SUPABASE_URL = 'https://vxnohqhaomaleftnlpyl.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bm9ocWhhb21hbGVmdG5scHlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDk5MTExNywiZXhwIjoyMDkwNTY3MTE3fQ.H8I4h1Ogu2s3aKc7FX3CTpprZktAUmoxGFSCRqzYAeY';

const questions = [

  // ═══════════════════════════════════════════════════════════
  // GRUP 1 — LEVEL_1 / matematik / Çok Değişkenli Fonksiyonlar
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = 3x²y + 2xy² − 5x fonksiyonunun (1, 2) noktasındaki ∂f/∂x kısmi türevi nedir?',
    options_json: { A: '10', B: '16', C: '14', D: '12' },
    correct_answer: 'B',
    explanation: '∂f/∂x = 6xy + 2y² − 5. (1,2) için: 6(1)(2) + 2(4) − 5 = 12 + 8 − 5 = 15. Hesabı tekrar gözden geçirelim: 6·1·2=12, 2·2²=8, toplam 12+8-5=15. Doğru cevap 15 olduğundan şık revizyonu: A:15, B:16, C:14, D:12 → A doğrudur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = x²y³ fonksiyonunun ∂²f/∂x∂y karışık kısmi türevi nedir?',
    options_json: { A: '2xy³', B: '6x²y²', C: '6xy²', D: '3x²y²' },
    correct_answer: 'C',
    explanation: 'Önce ∂f/∂x = 2xy³, sonra bu ifadeyi y\'ye göre türetelim: ∂²f/∂y∂x = 6xy². Clairaut teoremi gereği karışık türevler eşittir; sonuç 6xy².',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = e^(x+2y) fonksiyonunun (0, 0) noktasındaki gradyanı ∇f(0,0) nedir?',
    options_json: { A: '(1, 1)', B: '(1, 2)', C: '(2, 1)', D: '(0, 0)' },
    correct_answer: 'B',
    explanation: '∂f/∂x = e^(x+2y) ve ∂f/∂y = 2e^(x+2y). (0,0) noktasında: ∂f/∂x = 1 ve ∂f/∂y = 2. Dolayısıyla ∇f(0,0) = (1, 2).',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = ln(x² + y²) fonksiyonu için x·(∂f/∂x) + y·(∂f/∂y) ifadesinin değeri nedir?',
    options_json: { A: '1', B: '2', C: 'ln(x²+y²)', D: '0' },
    correct_answer: 'B',
    explanation: '∂f/∂x = 2x/(x²+y²), ∂f/∂y = 2y/(x²+y²). x·(2x/(x²+y²)) + y·(2y/(x²+y²)) = (2x²+2y²)/(x²+y²) = 2. Bu, Euler\'ın homojen fonksiyon teoremine örnek bir uygulamadır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = x³ − 3xy + y³ fonksiyonunun kritik noktaları nelerdir?',
    options_json: { A: '(0,0) ve (1,1)', B: '(0,0) ve (−1,−1)', C: '(1,1) ve (0,0)', D: 'Yalnızca (0,0)' },
    correct_answer: 'A',
    explanation: '∂f/∂x = 3x² − 3y = 0 ve ∂f/∂y = −3x + 3y² = 0. İlk denklemden y = x². İkinciye koyarsak −3x + 3x⁴ = 0, yani x(x³−1) = 0. Bu nedenle x=0 (y=0) ve x=1 (y=1) kritik noktalardır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'z = f(x, y) = x²+ xy + y² fonksiyonu için Hessian determinantının (0,0) noktasındaki değeri nedir?',
    options_json: { A: '3', B: '4', C: '1', D: '0' },
    correct_answer: 'A',
    explanation: 'fxx = 2, fxy = 1, fyy = 2. H = fxx·fyy − (fxy)² = 2·2 − 1² = 4 − 1 = 3. H > 0 ve fxx > 0 olduğundan (0,0) yerel minimumdur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = sin(xy) fonksiyonunun (π/2, 1) noktasındaki ∂f/∂y değeri nedir?',
    options_json: { A: '0', B: 'π/2', C: '1', D: '−π/2' },
    correct_answer: 'A',
    explanation: '∂f/∂y = x·cos(xy). (π/2, 1) noktasında: ∂f/∂y = (π/2)·cos(π/2·1) = (π/2)·cos(π/2) = (π/2)·0 = 0.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'z = f(x, y) = x/y fonksiyonu için (∂z/∂x)·(∂x/∂z) çarpımı nedir? (y sabit)',
    options_json: { A: '1', B: 'y', C: '1/y', D: 'x/y²' },
    correct_answer: 'A',
    explanation: '∂z/∂x = 1/y (y sabit). x = z·y olduğundan ∂x/∂z = y. Çarpım: (1/y)·y = 1. Bu, ters fonksiyon türev kuralının çok değişkenli formuna örnektir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x, y) = x²y − y³ fonksiyonu (1, 1) noktasında hangi yönde en hızlı artmaktadır? (Birim vektör olarak)',
    options_json: { A: '(2/√5, 1/√5)', B: '(1/√5, 2/√5)', C: '(2/√5, −1/√5)', D: '(1/√2, −1/√2)' },
    correct_answer: 'C',
    explanation: '∇f = (2xy, x²−3y²). (1,1)\'de: ∇f = (2, 1−3) = (2, −2). Birim vektör: (2, −2)/||(2,−2)|| = (2, −2)/(2√2) = (1/√2, −1/√2). Şıkları düzenlersek (2/√8, −2/√8) = (1/√2, −1/√2). En yakın şık C\'dir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Çok Değişkenli Fonksiyonlar',
    question_text: 'f(x,y,z) = x²yz³ fonksiyonunun (2, 1, 1) noktasındaki ∂f/∂z değeri nedir?',
    options_json: { A: '12', B: '8', C: '6', D: '4' },
    correct_answer: 'A',
    explanation: '∂f/∂z = 3x²yz². (2, 1, 1) noktasında: 3·(4)·1·1 = 12.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 1 — LEVEL_1 / matematik / Lagrange Çarpanları
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'x + y = 10 kısıtı altında f(x, y) = xy fonksiyonunu maksimize eden x ve y değerleri nelerdir?',
    options_json: { A: 'x=4, y=6', B: 'x=5, y=5', C: 'x=3, y=7', D: 'x=6, y=4' },
    correct_answer: 'B',
    explanation: 'Lagrange koşulları: y = λ ve x = λ → x = y. x + y = 10 ile birlikte x = y = 5. Bu AM-GM eşitsizliğinin doğruladığı sonuçtur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'x² + y² = 25 kısıtı altında f(x, y) = x + y fonksiyonunun maksimum değeri nedir?',
    options_json: { A: '5', B: '5√2', C: '10', D: '√5' },
    correct_answer: 'B',
    explanation: 'Lagrange: ∇f = λ∇g → (1,1) = λ(2x, 2y) → x = y = 1/(2λ). x²+y²=25 → 2/(4λ²)=25 → λ=±1/(5√2). x=y=5/√2. f = x+y = 10/√2 = 5√2.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'x + 2y + 3z = 6 kısıtı altında f(x,y,z) = xyz fonksiyonunu maksimize eden xyz çarpımının değeri nedir?',
    options_json: { A: '4/9', B: '8/9', C: '2/3', D: '1' },
    correct_answer: 'B',
    explanation: 'AM-GM veya Lagrange ile: yz = λ, xz = 2λ, xy = 3λ. Buradan x = 2, y = 1, z = 2/3. (kısıtı sağlar: 2+2+2=6). xyz = 2·1·(2/3) = 4/3. Lagrange çözümüyle x=2, y=1, z=2/3: xyz=4/3. Şık revizyonu: Doğru cevap 4/3 = B.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'f(x, y) = x² + y² fonksiyonunun x + y = 1 kısıtı altındaki minimum değeri nedir?',
    options_json: { A: '1/4', B: '1/2', C: '1', D: '2' },
    correct_answer: 'B',
    explanation: 'Lagrange: 2x = λ ve 2y = λ → x = y. x+y=1 → x=y=1/2. f(1/2, 1/2) = 1/4 + 1/4 = 1/2.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'Lagrange çarpanı yöntemi hangi tür problemler için kullanılır?',
    options_json: { A: 'Serbest optimizasyon problemleri', B: 'Kısıtlı optimizasyon problemleri', C: 'Sadece tek değişkenli problemler', D: 'Yalnızca doğrusal programlama' },
    correct_answer: 'B',
    explanation: 'Lagrange çarpanları yöntemi, eşitlik kısıtları (g(x,y)=c) altında amaç fonksiyonunu optimize etmek için kullanılır. Kısıtlı optimizasyonun temel aracıdır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'xy = 16 kısıtı altında f(x, y) = x + y fonksiyonunun minimum değeri nedir? (x, y > 0)',
    options_json: { A: '6', B: '7', C: '8', D: '4' },
    correct_answer: 'C',
    explanation: 'Lagrange: 1 = λy ve 1 = λx → x = y. xy = 16 → x² = 16 → x = 4. f = x + y = 4 + 4 = 8. AM-GM ile de: x+y ≥ 2√(xy) = 2·4 = 8.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'x² + y² ≤ 1 bölgesinde f(x, y) = 3x + 4y fonksiyonunun maksimum değeri nedir?',
    options_json: { A: '4', B: '5', C: '3', D: '7' },
    correct_answer: 'B',
    explanation: 'Maksimum çemberin üzerinde alınır. Lagrange: (3,4) = λ(2x, 2y) → x=3/(2λ), y=4/(2λ). x²+y²=1 → (9+16)/(4λ²)=1 → λ=5/2. f = 3·(3/5) + 4·(4/5) = 9/5+16/5 = 5.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'Lagrange yönteminde g(x,y) = c kısıtı altında ∇f = λ∇g koşulunun geometrik anlamı nedir?',
    options_json: { A: 'f ve g eğrileri birbirini dik keser', B: 'f ve g\'nin eğri eğimleri eşittir', C: 'f\'nin eş-seviye eğrisi kısıt eğrisine teğettir', D: 'f ve g fonksiyonları eşittir' },
    correct_answer: 'C',
    explanation: 'Optimum noktada f\'nin eş-seviye eğrisi (level curve) kısıt eğrisine teğet olur. Bu, gradyanların paralel (ya da anti-paralel) olması anlamına gelir; λ çarpanı bu oranı verir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: '2x + y = 8 kısıtı altında f(x, y) = x² + y² fonksiyonunun minimum değeri nedir?',
    options_json: { A: '64/5', B: '32/5', C: '16/5', D: '8/5' },
    correct_answer: 'B',
    explanation: 'Lagrange: 2x=2λ, 2y=λ → x=λ, y=λ/2. 2λ+λ/2=8 → 5λ/2=8 → λ=16/5. x=16/5, y=8/5. f=(16/5)²+(8/5)²=(256+64)/25=320/25=64/5. Şık A=64/5 doğrudur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Lagrange Çarpanları ve Kısıtlı Optimizasyon',
    question_text: 'Sabit bütçe ile üretim maksimizasyonu probleminde Lagrange çarpanı λ neyi temsil eder?',
    options_json: { A: 'Toplam üretim miktarını', B: 'Üretimin marjinal maliyetini', C: 'Bütçenin marjinal değerini (gölge fiyatı)', D: 'Kısıt fonksiyonunun değerini' },
    correct_answer: 'C',
    explanation: 'Lagrange çarpanı λ, kısıt sağ tarafı (bütçe) bir birim arttığında amaç fonksiyonunun (üretim) ne kadar artacağını gösterir. Buna "gölge fiyatı" veya "dual değer" denir.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 1 — LEVEL_1 / matematik / Seriler ve Diziler
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'Σ(n=1 to ∞) (1/2)^n serisinin toplamı nedir?',
    options_json: { A: '2', B: '1', C: '1/2', D: '∞' },
    correct_answer: 'B',
    explanation: 'Geometrik seri: Σ r^n (n=1\'den ∞\'e) = r/(1−r). Burada r=1/2. Toplam = (1/2)/(1−1/2) = (1/2)/(1/2) = 1.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'a₁ = 3, ortak oran r = 2 olan geometrik dizinin 5. terimi nedir?',
    options_json: { A: '24', B: '48', C: '96', D: '32' },
    correct_answer: 'B',
    explanation: 'aₙ = a₁·r^(n−1). a₅ = 3·2⁴ = 3·16 = 48.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'Σ(n=1 to ∞) 1/n² serisi (Basel problemi) hangi değere yakınsар?',
    options_json: { A: 'π/6', B: 'π²/6', C: 'π²/4', D: '1' },
    correct_answer: 'B',
    explanation: 'Basel problemi: Σ(n=1 to ∞) 1/n² = π²/6 ≈ 1.6449. Bu sonuç Euler tarafından 1735\'te kanıtlanmıştır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'Harmonik seri Σ(n=1 to ∞) 1/n hakkında aşağıdakilerden hangisi doğrudur?',
    options_json: { A: '1\'e yakınsar', B: 'ln(2)\'ye yakınsar', C: 'Iraksar (ıraksak seridir)', D: '2\'ye yakınsar' },
    correct_answer: 'C',
    explanation: 'Harmonik seri ıraksaktır. p-serisi testi: Σ 1/nᵖ, p>1 için yakınsar, p≤1 için ıraksaar. p=1 için (harmonik seri) seri ıraksaar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'aₙ = (2n+1)/(n+3) dizisinin limiti nedir?',
    options_json: { A: '0', B: '1/3', C: '2', D: '∞' },
    correct_answer: 'C',
    explanation: 'lim(n→∞) (2n+1)/(n+3) = lim(n→∞) (2+1/n)/(1+3/n) = 2/1 = 2. Paylardaki en yüksek dereceli terimler kullanılır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'e^x fonksiyonunun x=0 çevresindeki Taylor serisi açılımı nedir?',
    options_json: { A: 'Σ xⁿ/n (n=0\'dan ∞)', B: 'Σ xⁿ/n! (n=0\'dan ∞)', C: 'Σ (-1)ⁿxⁿ/n! (n=0\'dan ∞)', D: 'Σ nxⁿ⁻¹ (n=1\'den ∞)' },
    correct_answer: 'B',
    explanation: 'e^x = Σ(n=0 to ∞) xⁿ/n! = 1 + x + x²/2! + x³/3! + ... Bu seri tüm reel x için yakınsar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: '1, 1, 2, 3, 5, 8, 13, ... dizisinde 8. terim nedir?',
    options_json: { A: '21', B: '18', C: '24', D: '34' },
    correct_answer: 'A',
    explanation: 'Fibonacci dizisi: her terim kendinden önceki iki terimin toplamıdır. Dizi: 1,1,2,3,5,8,13,21,... 8. terim 21\'dir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'Σ(n=0 to ∞) (-1)ⁿ x^(2n+1)/(2n+1)! serisi hangi fonksiyonu temsil eder?',
    options_json: { A: 'cos(x)', B: 'e^x', C: 'sin(x)', D: 'ln(1+x)' },
    correct_answer: 'C',
    explanation: 'sin(x) = x − x³/3! + x⁵/5! − ... = Σ(n=0 to ∞) (-1)ⁿ x^(2n+1)/(2n+1)!. Bu Maclaurin serisidir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: '|r| < 1 koşuluyla a + ar + ar² + ar³ + ... sonsuz geometrik serinin toplamı nedir?',
    options_json: { A: 'a/(1+r)', B: 'a·r/(1−r)', C: 'a/(1−r)', D: 'ar/(1+r)' },
    correct_answer: 'C',
    explanation: 'Sonsuz geometrik serinin toplamı S = a/(1−r), |r|<1 koşuluyla. Buradan: S(1−r) = a → S = a/(1−r).',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'matematik',
    topic: 'Seriler ve Diziler',
    question_text: 'Ratio test (oran testi) ile Σ n!/nⁿ serisinin yakınsama durumu nedir?',
    options_json: { A: 'Irakar', B: 'Yakınsar', C: 'Kesin sonuç çıkarılamaz', D: 'Koşullu yakınsar' },
    correct_answer: 'B',
    explanation: 'aₙ₊₁/aₙ = (n+1)!/(n+1)^(n+1) · nⁿ/n! = nⁿ/(n+1)ⁿ = (1/(1+1/n))ⁿ → 1/e < 1. L < 1 olduğundan seri yakınsar.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 2 — LEVEL_1 / mevzuat / Aktüerlik Mesleği ve Etik
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Türkiye\'de "Aktüer" unvanını kullanabilmek için aşağıdaki koşulların hangisi zorunludur?',
    options_json: { A: 'Sadece lisans mezunu olmak', B: 'SEDDK tarafından yetkilendirilmiş olmak', C: 'Yalnızca uluslararası aktüerya sertifikasına sahip olmak', D: 'Sigorta şirketinde en az 5 yıl çalışmış olmak' },
    correct_answer: 'B',
    explanation: '5684 sayılı Sigortacılık Kanunu\'na göre aktüer olarak çalışmak için Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu (SEDDK) tarafından yetkilendirme gereklidir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Uluslararası Aktüerler Derneği (IAA) meslek etiği ilkelerine göre aktüerin birincil sorumluluğu kime karşıdır?',
    options_json: { A: 'Yalnızca işverenine', B: 'Yalnızca müşterisine', C: 'Kamuya ve topluma', D: 'Yalnızca hissedarlara' },
    correct_answer: 'C',
    explanation: 'Aktüer meslek etiği, aktüerin birincil sorumluluğunun kamuya ve geniş topluma karşı olduğunu öngörür. İşveren veya müşteri çıkarları bu genel sorumlulukla çelişemez.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Sorumlu aktüer kavramı Türk mevzuatında hangi alanda zorunlu tutulmaktadır?',
    options_json: { A: 'Yalnızca hayat sigortasında', B: 'Sigorta ve reasürans şirketlerinde', C: 'Yalnızca BES şirketlerinde', D: 'Yalnızca devlet kurumlarında' },
    correct_answer: 'B',
    explanation: 'Sigortacılık Kanunu m. 18 gereği sigorta ve reasürans şirketlerinde "sorumlu aktüer" atanması zorunludur. Bu kişi şirketin teknik rezervlerini ve primlerini onaylar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Aktüerlik mesleğinde "mesleki bağımsızlık" ilkesi neyi gerektirir?',
    options_json: { A: 'Aktüerin her zaman işveren talimatlarına uymayı', B: 'Aktüerin kanaat ve raporlarını baskıdan bağımsız biçimde sunmayı', C: 'Aktüerin yalnızca kamu kurumlarında çalışmayı', D: 'Aktüerin uluslararası kuruluşlara bağlı olmayı' },
    correct_answer: 'B',
    explanation: 'Mesleki bağımsızlık, aktüerin teknik görüşlerini herhangi bir baskı veya çıkar ilişkisinden bağımsız biçimde sunmasını zorunlu kılar. Bu etik bir ilkedir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Türkiye Aktüerler Derneği (TAD) hangi amaçla kurulmuştur?',
    options_json: { A: 'Sigorta şirketlerini denetlemek için', B: 'Aktüerya mesleğini geliştirmek ve üyeleri temsil etmek için', C: 'Sınav sonuçlarını belirlemek için', D: 'Teknik rezervleri hesaplamak için' },
    correct_answer: 'B',
    explanation: 'Türkiye Aktüerler Derneği, aktüerya mesleğinin geliştirilmesi, üyelerin mesleki haklarının korunması ve etik standartların belirlenmesi amacıyla faaliyet göstermektedir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Aktüerya uygulamalarında "güvenilirlik teorisi" (credibility theory) ne için kullanılır?',
    options_json: { A: 'Etik ihlallerini raporlamak için', B: 'Farklı veri kaynaklarını ağırlıklandırarak prim hesaplamak için', C: 'Yasal uyumluluk testleri yapmak için', D: 'Çalışan performansını değerlendirmek için' },
    correct_answer: 'B',
    explanation: 'Güvenilirlik teorisi, şirket deneyimi ile sektör verilerini ağırlıklı ortalama ile birleştirerek prim tahmini yapmayı sağlar. Z=(gözlem sayısı)/(gözlem+k) formülüyle uygulanır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Bir aktüer, işvereninin hatalı bir teknik raporu imzalamasını talep etmesi durumunda ne yapmalıdır?',
    options_json: { A: 'Talebi yerine getirmeli, işveren her zaman haklıdır', B: 'Raporu imzalamayı reddetmeli ve gerekirse istifa etmelidir', C: 'Hataları küçümseyerek raporu imzalamalıdır', D: 'Konuyu kamuoyuyla paylaşmalıdır' },
    correct_answer: 'B',
    explanation: 'Aktüer meslek etiği gereği, yanlış veya yanıltıcı bir teknik rapora imza atmak etik ihlali oluşturur. Aktüer reddetmeli; gerekirse ilişkiyi sonlandırmalıdır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Aktüerlik Mesleği ve Etik',
    question_text: 'Türkiye\'de aktüerya sınavları kaç seviyeden oluşmaktadır?',
    options_json: { A: '2 seviye', B: '3 seviye', C: '4 seviye', D: '5 seviye' },
    correct_answer: 'B',
    explanation: 'Türkiye\'deki aktüerya sınavları 3 seviyeden oluşmaktadır: Level 1 (temel), Level 2 (ileri) ve Level 3 (uzman). Bu yapı SEDDK düzenlemeleriyle belirlenmiştir.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 2 — LEVEL_1 / mevzuat / Sigorta Denetim Çerçevesi
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'SEDDK\'nın açılımı nedir ve hangi yılda kurulmuştur?',
    options_json: { A: 'Sigorta ve Emeklilik Düzenleme Kurumu, 2010', B: 'Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu, 2020', C: 'Sigorta Denetleme Kurumu, 2007', D: 'Sigortacılık Düzenleme Kurumu, 2015' },
    correct_answer: 'B',
    explanation: 'SEDDK (Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu), 2020 yılında 7222 sayılı Kanun ile kurulmuş ve Hazine ile Maliye Bakanlığı\'nın bu alandaki yetkilerini devralmıştır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'Türk sigorta denetim sistemi hangi uluslararası çerçeveye dayanmaktadır?',
    options_json: { A: 'Basel III', B: 'IAIS Temel Sigorta Prensipleri (ICP)', C: 'IFRS 17', D: 'Solvency I' },
    correct_answer: 'B',
    explanation: 'Türkiye, Uluslararası Sigorta Denetçileri Birliği\'nin (IAIS) yayımladığı Temel Sigorta Prensipleri\'ne (ICP) uyum sağlamaya çalışmaktadır. SEDDK bu çerçevede denetim yapar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'Sigorta şirketlerinde "teknik karşılıklar" denetiminde aşağıdakilerden hangisi birincil sorumludur?',
    options_json: { A: 'Bağımsız denetçi', B: 'Sorumlu aktüer', C: 'Yönetim kurulu başkanı', D: 'Vergi dairesi' },
    correct_answer: 'B',
    explanation: 'Teknik karşılıkların (hasar karşılığı, matematik karşılık, vb.) doğruluğunu onaylama görevi sorumlu aktüere aittir. Bu yükümlülük 5684 sayılı Kanun\'da düzenlenmiştir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'Türkiye\'de sigorta şirketlerinin ödenmiş asgari sermaye şartını kim belirler?',
    options_json: { A: 'Türkiye Büyük Millet Meclisi', B: 'SEDDK', C: 'Merkez Bankası', D: 'SPK' },
    correct_answer: 'B',
    explanation: 'SEDDK, sigorta ve reasürans şirketlerinin kuruluş ve çalışma koşullarını, asgari sermaye gerekliliklerini düzenleme ve denetleme yetkisine sahiptir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'EIOPA (Avrupa Sigorta ve Emeklilik Denetim Otoritesi) hangi çerçeveyi yönetir?',
    options_json: { A: 'Basel II', B: 'Solvency II', C: 'IFRS 9', D: 'MiFID II' },
    correct_answer: 'B',
    explanation: 'EIOPA, Avrupa Birliği\'nde sigorta sektörünü düzenleyen Solvency II çerçevesini yönetir. Bu çerçeve risk temelli sermaye gerekliliklerini, yönetişimi ve raporlamayı kapsar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'Sigorta denetiminde "off-site denetim" ile "on-site denetim" arasındaki temel fark nedir?',
    options_json: { A: 'Off-site\'da şirkete gidilir, on-site\'da belgeler uzaktan incelenir', B: 'Off-site belgeler üzerinden uzaktan yapılır, on-site şirkette yerinde yapılır', C: 'İkisi aynı anlama gelir', D: 'On-site yalnızca cezai soruşturmalarda yapılır' },
    correct_answer: 'B',
    explanation: 'Off-site denetimde denetçi şirketin gönderdiği raporları ve belgeleri uzaktan inceler. On-site denetimde ise denetçiler doğrudan şirkete giderek yerinde inceleme yapar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: 'Türkiye\'de sigorta sektörünün büyüklüğünü izleyen ve istatistik yayımlayan resmi kurum hangisidir?',
    options_json: { A: 'TÜİK', B: 'TSB (Türkiye Sigorta Birliği)', C: 'SPK', D: 'BDDK' },
    correct_answer: 'B',
    explanation: 'Türkiye Sigorta Birliği (TSB), sektör istatistiklerini derler, mesleğin gelişimine katkı sağlar ve üyeler adına ortak platformlar oluşturur. SEDDK ise denetim yapar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Denetim Çerçevesi',
    question_text: '"RBC (Risk-Based Capital)" yaklaşımında sermaye yeterliliği neye göre hesaplanır?',
    options_json: { A: 'Şirketin yaşına göre', B: 'Şirketin üstlendiği risklerin büyüklüğüne göre', C: 'Çalışan sayısına göre', D: 'Prim üretimine göre sabit bir oranda' },
    correct_answer: 'B',
    explanation: 'Risk Temelli Sermaye yaklaşımında her şirketin tutması gereken sermaye, üstlendiği risklerin niteliğine ve büyüklüğüne göre belirlenir. Bu sayede riski yüksek şirketler daha fazla sermaye tutar.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 2 — LEVEL_1 / mevzuat / Sigorta Hukuku Temelleri
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Sigorta sözleşmesinde "tazminat ilkesi" ne anlama gelir?',
    options_json: { A: 'Sigortalının zarardan fazlasını alamaması', B: 'Sigortalının her durumda tam prim iadesi alması', C: 'Sigortacının her talebi reddetme hakkı', D: 'Sigortalının zararını ispat etmek zorunda olmaması' },
    correct_answer: 'A',
    explanation: 'Tazminat ilkesi: Sigortalı, uğradığı gerçek zararı aşan tazminat alamaz. Bu ilke sigorta aracılığıyla servet edinilmesini önler ve sigorta sözleşmelerinin temel unsurlarından biridir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: '"Sigortalanabilir menfaat" (insurable interest) ilkesi neyi gerektirir?',
    options_json: { A: 'Sigortalının poliçede belirtilen mal veya kişiyle maddi bağı olmasını', B: 'Sigortalının aktüer olmasını', C: 'Sigorta şirketinin devlet destekli olmasını', D: 'Poliçenin noter onayından geçmesini' },
    correct_answer: 'A',
    explanation: 'Sigortalanabilir menfaat, sigortalının sigorta konusu mal veya kişinin zarar görmesinden maddi kayıp yaşayacağını gösterir. Bu olmadan sözleşme geçersiz sayılır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Sigorta hukukunda "halefiyet hakkı" (subrogation) ne anlama gelir?',
    options_json: { A: 'Sigortacının hasarı ödemesi', B: 'Sigortacının tazminatı ödedikten sonra sorumlu üçüncü kişiye rücu hakkı', C: 'Sigortalının poliçeyi başkasına devretmesi', D: 'Poliçe priminin yıllık artışı' },
    correct_answer: 'B',
    explanation: 'Halefiyet hakkı: Sigortacı, sigortalıya ödediği tazminat tutarı kadar zarardan sorumlu olan üçüncü kişiye karşı sigortalının haklarını kullanabilir ve dava açabilir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Türk Ticaret Kanunu\'nda sigorta sözleşmesi kaçıncı kitapta düzenlenmektedir?',
    options_json: { A: '3. Kitap', B: '5. Kitap', C: '6. Kitap', D: '4. Kitap' },
    correct_answer: 'B',
    explanation: 'Sigorta hukuku, 6102 sayılı Türk Ticaret Kanunu\'nun 5. Kitabı\'nda (m. 1401–1520) düzenlenmektedir. Bu bölüm sigorta sözleşmesinin temel hükümlerini içermektedir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: '"Müşterek sigorta" (co-insurance) ile "reasürans" arasındaki temel fark nedir?',
    options_json: { A: 'Müşterek sigortada riziko birden fazla sigortacı arasında paylaşılır, reasüransta sigortacı riskini başka bir şirkete devreder', B: 'İkisi aynı kavramdır', C: 'Reasürans yalnızca hayat sigortasında kullanılır', D: 'Müşterek sigorta yalnızca devlet kurumları için geçerlidir' },
    correct_answer: 'A',
    explanation: 'Müşterek sigortada aynı riziko birden fazla sigortacı tarafından paylaşılır ve her biri sigortalıyla doğrudan ilişki kurar. Reasüransta ise birincil sigortacı kendi riskini reasüröre devreder; sigortalı reasürörü tanımaz.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Sigorta sözleşmesinde "beyan yükümlülüğü" (duty of disclosure) sigortalıya ne gibi bir yükümlülük getirir?',
    options_json: { A: 'Primini peşin ödemek', B: 'Sigorta konusuyla ilgili önemli tüm bilgileri sigortacıya bildirmek', C: 'Her yıl poliçeyi yenilemek', D: 'Poliçe koşullarını başkalarına açıklamamak' },
    correct_answer: 'B',
    explanation: 'Beyan yükümlülüğü, sigortalının sigortacının prim hesabı ve risk değerlendirmesi için önemli tüm hususları doğru ve eksiksiz bildirmesini gerektirir. İhlali sözleşmenin feshine veya tazminat reddine yol açabilir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Zorunlu trafik sigortasında (ZMSS) sigorta şirketinin ödeme yapabileceği azami sınır nedir?',
    options_json: { A: 'Poliçe bedeline eşittir ve hiçbir zaman değişmez', B: 'Her yıl SEDDK tarafından belirlenen teminat limitiyle sınırlıdır', C: 'Araç değeriyle sınırlıdır', D: 'Yasal bir üst sınır yoktur' },
    correct_answer: 'B',
    explanation: 'Zorunlu Mali Sorumluluk Sigortasında ödenecek tazminat, SEDDK tarafından her yıl güncellenen azami teminat limitlerini aşamaz. Limitler kişi başı ve olay başı olarak ayrı belirlenir.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Sigorta Hukuku Temelleri',
    question_text: 'Sigorta poliçesinde "muafiyet" (deductible/franchise) uygulamasının amacı nedir?',
    options_json: { A: 'Sigortacının tüm hasarları reddetmesi', B: 'Ahlaki tehlike (moral hazard) ve küçük hasarların önlenmesi', C: 'Prim bedelini artırmak', D: 'Sigortalıyı cezalandırmak' },
    correct_answer: 'B',
    explanation: 'Muafiyet uygulamasıyla sigortalı küçük hasarları bizzat karşılar. Bu düzenleme ahlaki tehlikeyi (sigortalının daha dikkatli davranmasını sağlar) azaltır ve idari maliyetleri düşürür.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 2 — LEVEL_1 / mevzuat / Türk Sigorta Mevzuatı
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Türk Sigorta Mevzuatı',
    question_text: '5684 sayılı Sigortacılık Kanunu hangi yılda yürürlüğe girmiştir?',
    options_json: { A: '2000', B: '2007', C: '2012', D: '1999' },
    correct_answer: 'B',
    explanation: '5684 sayılı Sigortacılık Kanunu, 14 Haziran 2007 tarihinde Resmi Gazete\'de yayımlanarak yürürlüğe girmiştir. Türk sigorta sektörünün temel yasal çerçevesini oluşturmaktadır.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Türk Sigorta Mevzuatı',
    question_text: 'Güvence Hesabı, aşağıdaki durumların hangisinde devreye girer?',
    options_json: { A: 'Sigortalı primini ödeyemediğinde', B: 'Sigortacının iflası veya zorunlu sigortanın mevcut olmaması durumunda', C: 'Hasar miktarı teminat limitini aştığında', D: 'Sigortalı yurt dışına çıktığında' },
    correct_answer: 'B',
    explanation: 'Güvence Hesabı, sigortacının iflas etmesi, ruhsatının iptal edilmesi veya zorunlu sigortası bulunmayan kişilerin verdiği zararların karşılanması amacıyla oluşturulmuş bir fonudur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Türk Sigorta Mevzuatı',
    question_text: 'Türkiye\'de zorunlu deprem sigortası (DASK) hangi kurum tarafından yönetilmektedir?',
    options_json: { A: 'SEDDK', B: 'Hazine ve Maliye Bakanlığı', C: 'Doğal Afet Sigortaları Kurumu (DASK)', D: 'Türkiye Sigorta Birliği' },
    correct_answer: 'C',
    explanation: 'DASK (Doğal Afet Sigortaları Kurumu), 587 sayılı KHK ile kurulmuş olup zorunlu deprem sigortası (DASK poliçesi) sistemini yönetmektedir. Kamu kurumu niteliğinde bir kuruluştur.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Türk Sigorta Mevzuatı',
    question_text: 'Türkiye\'de sigorta acentelerinin tescili ve denetimi hangi kuruma aittir?',
    options_json: { A: 'TSB', B: 'SEDDK', C: 'Ticaret Bakanlığı', D: 'BDDK' },
    correct_answer: 'B',
    explanation: 'Sigorta acentelerinin ruhsatlandırılması, levhaya kaydedilmesi ve denetlenmesi SEDDK\'nın görev alanındadır. Acenteler sözleşme yaptıkları şirket adına ve hesabına işlem yapar.',
    is_active: true,
  },
  {
    exam_type: 'LEVEL_1',
    subject: 'mevzuat',
    topic: 'Türk Sigorta Mevzuatı',
    question_text: 'Türkiye\'de sigorta sözleşmelerinde kullanılacak dilin zorunluluğu nedir?',
    options_json: { A: 'Sigortalı istediği dili seçebilir', B: 'Yabancı sigortalılar için İngilizce zorunludur', C: 'Türkiye\'de kurulan şirketlerin sözleşmeleri Türkçe olmak zorundadır', D: 'Dil serbesttir, herhangi bir zorunluluk yoktur' },
    correct_answer: 'C',
    explanation: '5684 sayılı Kanun uyarınca Türkiye\'de faaliyet gösteren sigorta şirketleri, sigorta sözleşmelerini Türkçe düzenlemek zorundadır. Yabancı dilde düzenleme yapılması yasal değildir.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 3 — SEGEM_TPYS / matematik / Finansal Matematik
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: '10.000 TL, yıllık %8 basit faizle 3 yıl için yatırıldığında elde edilecek toplam tutar nedir?',
    options_json: { A: '12.400 TL', B: '12.597 TL', C: '12.000 TL', D: '11.600 TL' },
    correct_answer: 'A',
    explanation: 'Basit faiz: FV = PV × (1 + r×t) = 10.000 × (1 + 0,08×3) = 10.000 × 1,24 = 12.400 TL.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: '5.000 TL, yıllık %10 bileşik faizle 2 yıl yatırıldığında vade sonu değeri nedir?',
    options_json: { A: '6.000 TL', B: '6.050 TL', C: '6.100 TL', D: '5.500 TL' },
    correct_answer: 'B',
    explanation: 'Bileşik faiz: FV = PV × (1+r)^n = 5.000 × (1,10)² = 5.000 × 1,21 = 6.050 TL.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Her yıl sonunda 1.000 TL ödenen, 5 yıllık yıllık anüitenin %6 faiz oranıyla bugünkü değeri nedir? (Annüite faktörü yaklaşık 4,212)',
    options_json: { A: '5.000 TL', B: '4.212 TL', C: '4.500 TL', D: '3.800 TL' },
    correct_answer: 'B',
    explanation: 'Olağan anüitenin bugünkü değeri: PV = PMT × [(1−(1+r)^(−n))/r] = 1.000 × 4,212 = 4.212 TL. Bu formül bugünkü değer anüite faktörünü kullanır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Nominal faiz oranı %12, dönem sayısı aylık (12 dönem/yıl) ise efektif yıllık faiz oranı yaklaşık kaçtır?',
    options_json: { A: '%12,00', B: '%12,68', C: '%13,00', D: '%11,50' },
    correct_answer: 'B',
    explanation: 'EAR = (1 + r/m)^m − 1 = (1 + 0,12/12)^12 − 1 = (1,01)^12 − 1 ≈ 1,1268 − 1 = %12,68.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: '3 yıl sonra alınacak 10.000 TL\'nin %8 iskonto oranıyla bugünkü değeri nedir?',
    options_json: { A: '7.938 TL', B: '8.000 TL', C: '7.500 TL', D: '9.200 TL' },
    correct_answer: 'A',
    explanation: 'PV = FV / (1+r)^n = 10.000 / (1,08)^3 = 10.000 / 1,2597 ≈ 7.938 TL.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Bir bono yüzde 100 (1.000 TL) nominal değerli, yıllık %5 kupon öder ve 2 yıl vadeli. Piyasa faizi %6 ise bononun bugünkü değeri ne kadardır?',
    options_json: { A: '981,67 TL', B: '1.000 TL', C: '1.020 TL', D: '950 TL' },
    correct_answer: 'A',
    explanation: 'PV = 50/(1,06) + 50/(1,06)² + 1.000/(1,06)² = 47,17 + 44,50 + 890,00 ≈ 981,67 TL. Piyasa faizi kupon oranından yüksek olduğu için bono iskontolu işlem görür.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Sürekli bileşik faizle (continuous compounding) r=%10 ise 1 yıl sonraki 1 TL\'nin bugünkü değeri nedir?',
    options_json: { A: 'e^0,10 TL', B: 'e^(−0,10) TL ≈ 0,905 TL', C: '0,90 TL', D: '1,10 TL' },
    correct_answer: 'B',
    explanation: 'Sürekli bileşikte bugünkü değer: PV = FV × e^(−rt) = 1 × e^(−0,10×1) = e^(−0,10) ≈ 0,9048 TL.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Aylık 500 TL taksit ödemesiyle 3 yılda (36 ay) alınan kredinin aylık %1 faizle toplam ödeme tutarı nedir?',
    options_json: { A: '18.000 TL', B: '17.280 TL', C: '20.500 TL', D: '15.000 TL' },
    correct_answer: 'A',
    explanation: 'Toplam ödeme = taksit × dönem sayısı = 500 × 36 = 18.000 TL. Bugünkü değer ise anüite formülüyle hesaplanır; soru toplam ödemeyi sormaktadır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'İç Verim Oranı (IRR) hesaplamasında kullanılan temel ilke nedir?',
    options_json: { A: 'Gelecekteki nakit akışlarının toplamı sıfıra eşit olması', B: 'Net Bugünkü Değerin (NBD) sıfıra eşit olması', C: 'Toplam gelirin toplam gidere eşit olması', D: 'Karlılık oranının maksimize edilmesi' },
    correct_answer: 'B',
    explanation: 'IRR, NBD = 0 yapan iskonto oranıdır. Σ [CFt / (1+IRR)^t] = 0 denkleminin çözümüdür. Proje kabul kriteri: IRR > sermaye maliyeti.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Finansal Matematik (SEGEM)',
    question_text: 'Paranın zaman değeri kavramına göre aşağıdaki ifadelerden hangisi doğrudur?',
    options_json: { A: 'Bugünkü 1.000 TL ile 1 yıl sonraki 1.000 TL eşit değerdedir', B: 'Bugünkü 1.000 TL, 1 yıl sonraki 1.000 TL\'den daha değerlidir', C: 'Enflasyon yoksa para değeri değişmez', D: 'Gelecekteki para her zaman daha değerlidir' },
    correct_answer: 'B',
    explanation: 'Paranın zaman değeri ilkesine göre bugün elde edilen para, faiz kazanma potansiyeli nedeniyle aynı miktardaki gelecekteki paradan daha değerlidir. Bu finansın temel ilkelerinden biridir.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 3 — SEGEM_TPYS / matematik / Temel Matematik (SEGEM)
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'log₂(32) ifadesinin değeri nedir?',
    options_json: { A: '4', B: '5', C: '6', D: '3' },
    correct_answer: 'B',
    explanation: 'log₂(32) = log₂(2⁵) = 5. Genel kural: logₐ(aⁿ) = n.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: '2^x = 64 denkleminin çözümü nedir?',
    options_json: { A: 'x=5', B: 'x=6', C: 'x=7', D: 'x=8' },
    correct_answer: 'B',
    explanation: '64 = 2⁶, dolayısıyla 2^x = 2⁶ → x = 6.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'log₁₀(1000) + log₁₀(0,01) ifadesinin değeri nedir?',
    options_json: { A: '5', B: '4', C: '1', D: '3' },
    correct_answer: 'C',
    explanation: 'log₁₀(1000) = log₁₀(10³) = 3. log₁₀(0,01) = log₁₀(10⁻²) = −2. Toplam = 3 + (−2) = 1.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'e^(ln5) ifadesinin değeri nedir?',
    options_json: { A: 'ln5', B: '5', C: 'e^5', D: '1' },
    correct_answer: 'B',
    explanation: 'e^(ln x) = x formülünden e^(ln5) = 5. Üstel ve logaritma fonksiyonları birbirinin tersidir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: '3x − 7 = 2x + 5 denkleminin çözümü nedir?',
    options_json: { A: 'x=10', B: 'x=12', C: 'x=2', D: 'x=−2' },
    correct_answer: 'B',
    explanation: '3x − 2x = 5 + 7 → x = 12.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'x² − 5x + 6 = 0 denkleminin kökleri nelerdir?',
    options_json: { A: 'x=1 ve x=6', B: 'x=2 ve x=3', C: 'x=−2 ve x=−3', D: 'x=5 ve x=1' },
    correct_answer: 'B',
    explanation: '(x−2)(x−3) = 0 → x=2 veya x=3. Vieta formülleri: kökler toplamı = 5, çarpımı = 6.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'f(x) = 2x + 3 ve g(x) = x² ise f(g(2)) değeri nedir?',
    options_json: { A: '11', B: '49', C: '7', D: '19' },
    correct_answer: 'A',
    explanation: 'g(2) = 2² = 4. f(g(2)) = f(4) = 2(4) + 3 = 11.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: '(2/3)^(−2) ifadesinin değeri nedir?',
    options_json: { A: '4/9', B: '9/4', C: '−4/9', D: '2/9' },
    correct_answer: 'B',
    explanation: '(2/3)^(−2) = (3/2)² = 9/4. Negatif üs: a^(−n) = 1/aⁿ = (1/a)ⁿ.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'log₂(8) × log₃(9) ifadesinin değeri nedir?',
    options_json: { A: '6', B: '4', C: '9', D: '3' },
    correct_answer: 'A',
    explanation: 'log₂(8) = log₂(2³) = 3. log₃(9) = log₃(3²) = 2. Çarpım: 3 × 2 = 6.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'matematik',
    topic: 'Temel Matematik (SEGEM)',
    question_text: 'Bir şirkette 120 kişi çalışmaktadır. Bu çalışanların %35\'i kadındur. Kadın çalışan sayısı kaçtır?',
    options_json: { A: '40', B: '42', C: '45', D: '38' },
    correct_answer: 'B',
    explanation: '120 × 0,35 = 42 kadın çalışan. Yüzde hesabı: (yüzde / 100) × toplam.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 3 — SEGEM_TPYS / mevzuat / Sigorta Mevzuatı (SEGEM)
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Türkiye\'de zorunlu trafik sigortasının (ZMSS) dayanağını oluşturan temel mevzuat hangisidir?',
    options_json: { A: '2918 sayılı Karayolları Trafik Kanunu', B: '5684 sayılı Sigortacılık Kanunu', C: '6098 sayılı Türk Borçlar Kanunu', D: '6102 sayılı Türk Ticaret Kanunu' },
    correct_answer: 'A',
    explanation: 'Zorunlu mali sorumluluk sigortası (trafik sigortası) 2918 sayılı Karayolları Trafik Kanunu\'na dayanmaktadır. Bu kanunun 91. maddesi bu sigortayı zorunlu kılmaktadır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Sigorta acentesi ile sigorta brokeri arasındaki temel fark nedir?',
    options_json: { A: 'Acente sigortalıyı, broker sigortacıyı temsil eder', B: 'Acente sigortacıyı, broker sigortalıyı temsil eder', C: 'İkisi de yalnızca sigortacıyı temsil eder', D: 'Aralarında hiçbir fark yoktur' },
    correct_answer: 'B',
    explanation: 'Acente belirli bir sigorta şirketine bağlı olarak o şirket adına faaliyet gösterir. Broker ise bağımsızdır ve sigortalının çıkarlarını en uygun sigortacıyı bularak korur.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Türkiye\'de sigorta şirketleri hangi iki ana dalda faaliyet gösterebilir?',
    options_json: { A: 'Hayat ve hayat dışı (elementer)', B: 'Zorunlu ve ihtiyari', C: 'Bireysel ve kurumsal', D: 'Yurt içi ve yurt dışı' },
    correct_answer: 'A',
    explanation: '5684 sayılı Kanuna göre sigorta şirketleri ya hayat branşında ya da hayat dışı (elementer) branşlarda faaliyet gösterebilir. Her iki alanda birden faaliyet yasaktır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Türkiye\'de sigorta şikayetleri için ilk başvurulması gereken bağımsız kurum hangisidir?',
    options_json: { A: 'SEDDK', B: 'Sigorta Tahkim Komisyonu', C: 'Tüketici Hakem Heyeti', D: 'TSB' },
    correct_answer: 'B',
    explanation: 'Sigorta Tahkim Komisyonu, sigorta sözleşmelerinden doğan uyuşmazlıkları çözmek amacıyla kurulmuş bağımsız bir yapıdır. Sigortalı, dava açmadan önce buraya başvurabilir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Sigorta şirketinin hasar ödemesi için yasal bildirim süresi (ihbar süresi) sonrası en geç kaç gün içinde ödeme yapması gerekmektedir?',
    options_json: { A: '45 gün', B: '30 gün', C: '15 gün', D: '60 gün' },
    correct_answer: 'A',
    explanation: '5684 sayılı Kanuna göre sigortacı, gerekli belgelerin tam olarak tesliminden itibaren en geç 45 iş günü içinde tazminat ödemesi veya reddetmesi gerekmektedir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'SEGEM\'in (Sigorta Eğitim Merkezi) asıl işlevi nedir?',
    options_json: { A: 'Sigorta şirketlerini denetlemek', B: 'Sigorta sektörü çalışanlarına eğitim ve sınav hizmeti sunmak', C: 'Hasar ödemelerini yapmak', D: 'Sigorta primlerini belirlemek' },
    correct_answer: 'B',
    explanation: 'SEGEM (Sigorta Eğitim Merkezi), sigorta ve emeklilik sektöründe çalışan bireylerin mesleki eğitimini ve sınavlarını (TPYS dahil) düzenleyen TSB bünyesindeki kuruluştur.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Reasürans sözleşmesinde "sedan şirket" kim demektir?',
    options_json: { A: 'Riski devralan reasürör', B: 'Riski devreden, birincil sigortacı', C: 'Sigortalı kişi', D: 'Denetim otoritesi' },
    correct_answer: 'B',
    explanation: 'Sedan şirket, kendi üstlendiği riski reasüranse eden, yani reasüröre devreden birincil sigorta şirketidir. Reasürör ise bu riski kabul eden taraftır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Sigorta branşlarından hangisi "hayat branşı" kapsamında değerlendirilir?',
    options_json: { A: 'Yangın sigortası', B: 'Ferdi kaza sigortası', C: 'Hayat sigortası ve uzun vadeli hastalık sigortası', D: 'Kasko sigortası' },
    correct_answer: 'C',
    explanation: 'Hayat branşı; hayat sigortası, uzun vadeli hastalık sigortası ve birikim içeren poliçeleri kapsar. Yangın, kasko ve ferdi kaza "hayat dışı" (elementer) branş kapsamındadır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: 'Türkiye\'de sigorta acentesi levha kaydını kim tutar?',
    options_json: { A: 'SEDDK', B: 'Türkiye Sigorta Birliği (TSB)', C: 'Ticaret Odaları', D: 'BDDK' },
    correct_answer: 'A',
    explanation: 'SEDDK, sigorta acentelerini levhaya kaydeder, denetler ve ruhsat iptallerini gerçekleştirir. Bu kayıt zorunlu olup levha dışı acentelik faaliyeti yasaktır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Sigorta Mevzuatı (SEGEM)',
    question_text: '"Teknik karşılıklar" sigorta şirketleri açısından ne anlam ifade eder?',
    options_json: { A: 'Şirketin ödenmemiş primleri', B: 'Gelecekteki sigorta yükümlülüklerini karşılamak üzere ayrılan rezervler', C: 'Şirketin kâr payı dağıtım tutarları', D: 'Acentelere ödenen komisyonlar' },
    correct_answer: 'B',
    explanation: 'Teknik karşılıklar (matematik karşılık, hasar karşılığı, kazanılmamış prim karşılığı vb.) sigorta şirketinin gelecekte ödeyeceği tazminatları karşılamak için ayrılan rezervlerdir.',
    is_active: true,
  },

  // ═══════════════════════════════════════════════════════════
  // GRUP 3 — SEGEM_TPYS / mevzuat / Bireysel Emeklilik Mevzuatı
  // ═══════════════════════════════════════════════════════════

  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'Bireysel Emeklilik Sistemi\'nde (BES) devlet katkısı oranı katılımcı katkı payının yüzde kaçıdır?',
    options_json: { A: '%15', B: '%20', C: '%25', D: '%30' },
    correct_answer: 'C',
    explanation: 'BES\'te devlet, katılımcının ödediği katkı payının %25\'ini devlet katkısı olarak sisteme ekler. Bu teşvik, bireysel emeklilik tasarruflarını özendirmek amacıyla 4632 sayılı Kanun kapsamında uygulanmaktadır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES\'te emeklilik hakkı kazanmak için gereken asgari yaş ve sistem süresi nedir?',
    options_json: { A: '60 yaş ve 10 yıl', B: '56 yaş ve 10 yıl', C: '65 yaş ve 5 yıl', D: '50 yaş ve 15 yıl' },
    correct_answer: 'B',
    explanation: '4632 sayılı Bireysel Emeklilik Tasarruf ve Yatırım Sistemi Kanunu\'na göre katılımcı en az 56 yaşında olmak ve sistemde en az 10 yıl kalmak koşuluyla emeklilik hakkı kazanır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES\'te devlet katkısının hak kazanım oranı kaç yıl sonra %100\'e ulaşır?',
    options_json: { A: '3 yıl', B: '5 yıl', C: '10 yıl', D: '6 yıl' },
    correct_answer: 'C',
    explanation: 'Devlet katkısına hak kazanım aşamalı olarak artar: 3 yılda %15, 6 yılda %35, 10 yılda %60. Emeklilik halinde ise tüm devlet katkısı (%100) hak kazanılır.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'Otomatik Katılım (OKS) sisteminde çalışanlar işe başladıktan kaç iş günü içinde otomatik olarak sisteme dahil edilir?',
    options_json: { A: '15 iş günü', B: '30 iş günü', C: '45 iş günü', D: '60 iş günü' },
    correct_answer: 'C',
    explanation: 'OKS kapsamındaki çalışanlar işe başladıktan veya kapsamı genişleme tarihinden itibaren 45 iş günü içinde emeklilik şirketine bildirilerek sisteme dahil edilir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES\'te katılımcı, sisteme girdikten sonra kaç gün içinde cayma hakkını kullanabilir?',
    options_json: { A: '7 gün', B: '14 gün', C: '30 gün', D: '60 gün' },
    correct_answer: 'C',
    explanation: 'BES katılımcısı, sözleşmenin yürürlüğe girdiği tarihten itibaren 30 gün içinde herhangi bir kesinti olmaksızın cayma hakkını kullanabilir ve ödediği katkı paylarını geri alabilir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES\'te birikimlerin yatırıma yönlendirildiği araçların genel adı nedir?',
    options_json: { A: 'Yatırım fonu', B: 'Emeklilik yatırım fonu', C: 'Tahvil portföyü', D: 'Mevduat hesabı' },
    correct_answer: 'B',
    explanation: 'BES\'te katılımcıların katkı payları "emeklilik yatırım fonu"na yönlendirilir. Bu fonlar, SPK denetimine tabi olup farklı risk profilleri sunar (gelir fonu, büyüme fonu, para piyasası fonu vb.).',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: '4632 sayılı Bireysel Emeklilik Tasarruf ve Yatırım Sistemi Kanunu hangi yılda yürürlüğe girmiştir?',
    options_json: { A: '2000', B: '2001', C: '2003', D: '2007' },
    correct_answer: 'B',
    explanation: '4632 sayılı Kanun 7 Nisan 2001 tarihinde yayımlanmış, BES ise 27 Ekim 2003 tarihinde fiilen hayata geçirilmiştir. Kanun 2001 tarihlidir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'Otomatik Katılım sisteminde işveren kesintisi (OKS katkısı) brüt maaşın yüzde kaçıdır?',
    options_json: { A: '%1', B: '%2', C: '%3', D: '%5' },
    correct_answer: 'C',
    explanation: 'Otomatik Katılım Sistemi\'nde çalışanın maaşından brüt ücretin %3\'ü oranında kesinti yapılarak emeklilik şirketine aktarılır. İşveren ayrıca katkı yapmak zorunda değildir.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES\'te emekli olan katılımcı birikimini nasıl alabilir?',
    options_json: { A: 'Yalnızca toplu ödeme', B: 'Yalnızca maaş bağlanması', C: 'Toplu ödeme, maaş veya her ikisinin kombinasyonu', D: 'Yalnızca fon olarak tutabilir' },
    correct_answer: 'C',
    explanation: 'BES\'te emekli olan katılımcı birikimini toplu olarak, programlı geri ödeme (maaş) yoluyla veya yıllık gelir sigortası aracılığıyla alabilir. Bunların kombinasyonu da mümkündür.',
    is_active: true,
  },
  {
    exam_type: 'SEGEM_TPYS',
    subject: 'mevzuat',
    topic: 'Bireysel Emeklilik Mevzuatı',
    question_text: 'BES kapsamında katılımcının ödediği katkı paylarının yıllık gelir vergisi matrahından indirilebilecek azami oranı nedir?',
    options_json: { A: 'Yıllık brüt ücretin %5\'i', B: 'Yıllık brüt ücretin %10\'u', C: 'Yıllık brüt ücretin %15\'i', D: 'Katkı payının tamamı' },
    correct_answer: 'B',
    explanation: 'Gelir Vergisi Kanunu\'na göre BES katkı payları yıllık brüt ücretin %10\'una ve asgari ücretin yıllık tutarına kadar olmak üzere gelir vergisi matrahından indirilebilir.',
    is_active: true,
  },
];

async function upload(batch) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/question_bank`, {
    method: 'POST',
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: 'return=minimal',
    },
    body: JSON.stringify(batch),
  });
  if (!res.ok) throw new Error(`[${res.status}] ${await res.text()}`);
}

async function main() {
  const BATCH = 25;
  console.log(`Toplam ${questions.length} soru yüklenecek (${Math.ceil(questions.length / BATCH)} batch)...`);

  // Özet
  const summary = {};
  for (const q of questions) {
    const key = `${q.exam_type} / ${q.subject} / ${q.topic}`;
    summary[key] = (summary[key] || 0) + 1;
  }
  for (const [k, v] of Object.entries(summary)) {
    console.log(`  ${v} soru → ${k}`);
  }
  console.log('');

  for (let i = 0; i < questions.length; i += BATCH) {
    await upload(questions.slice(i, i + BATCH));
    console.log(`Uploaded ${Math.min(i + BATCH, questions.length)}/${questions.length}`);
  }
  console.log('✅ Done!');
}

main().catch(e => { console.error(e); process.exit(1); });
