#!/usr/bin/env node
// Tüm az sorulu konuları 5'e tamamlar
const SUPABASE_URL = 'https://vxnohqhaomaleftnlpyl.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bm9ocWhhb21hbGVmdG5scHlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDk5MTExNywiZXhwIjoyMDkwNTY3MTE3fQ.H8I4h1Ogu2s3aKc7FX3CTpprZktAUmoxGFSCRqzYAeY';

const q = (exam_type, subject, topic, question_text, A, B, C, D, correct_answer, explanation) => ({
  exam_type, subject, topic, question_text,
  options_json: { A, B, C, D }, correct_answer, explanation, is_active: true,
});

const questions = [

  // ══════════════════════════════════════════════════════════════
  // 1 SORULU KONULAR → +4 soru ekle
  // ══════════════════════════════════════════════════════════════

  // ── Bilanço Hazırlama [LEVEL_2/muhasebe] ──
  q('LEVEL_2','muhasebe','Bilanço Hazırlama','Bilanço hazırlanırken aktifler nasıl sıralanır?','Büyükten küçüğe','Likiditesi en yüksekten en düşüğe (dönen → duran)','Tarihi maliyete göre','Alfabetik','B','Dönen varlıklar (likit) önce, duran varlıklar sonra. Pasifte ise vadesi en kısa borçlar önce.'),
  q('LEVEL_2','muhasebe','Bilanço Hazırlama','TFRS\'ye göre maddi duran varlıklar bilançoda nasıl gösterilir?','Brüt maliyet','Maliyet − birikmiş amortisman − değer düşüklüğü = net defter değeri','Gerçeğe uygun değer zorunludur','Sigorta değeri','B','MDV: NBD = tarihi maliyet − birikmiş amortisman − birikmiş değer düşüklüğü. Yeniden değerleme modeli opsiyonel.'),
  q('LEVEL_2','muhasebe','Bilanço Hazırlama','Ertelenmiş vergi varlığı bilançoda nerede gösterilir?','Dönen varlıklar','Duran varlıklar (uzun vadeli)','Özkaynak','Kısa vadeli yabancı kaynaklar','B','Ertelenmiş vergi varlığı: geçici fark × vergi oranı. Uzun vadeli varlık olarak sınıflandırılır.'),
  q('LEVEL_2','muhasebe','Bilanço Hazırlama','Bilanço dışı finansman (off-balance sheet) nedir ve neden önemlidir?','Gelir tablosu kalemi','Varlık ve borçların bilanço dışında tutulması; finansal borçluluk oranını olduğundan düşük gösterir','Özkaynak kalemi','Nakit akışı','B','Operasyonel kiralama (eski TFRS): bilanço dışı. TFRS 16 ile artık aktife alınıyor. Kaldıraç görünümünü etkiler.'),

  // ── Bireysel Emeklilik Muhasebesi [LEVEL_2/muhasebe] ──
  q('LEVEL_2','muhasebe','Bireysel Emeklilik Muhasebesi','BES şirketinin bilançosunda katılımcılara ait fon varlıkları nasıl gösterilir?','Şirketin özkaynak hesabında','Katılımcı fonları ayrı bir kalemde; emanet niteliğinde yükümlülük','Nazım hesaplarda','Gösterilmez','B','BES fonları katılımcıya ait, şirket emanetçi. Aktif: yatırılan varlıklar. Pasif: katılımcı fon yükümlülüğü.'),
  q('LEVEL_2','muhasebe','Bireysel Emeklilik Muhasebesi','Yönetim ücreti (fon işletim gideri) BES muhasebesinde nasıl kaydedilir?','Prim geliri','Günlük olarak fon değerinden kesilir; şirket geliri, katılımcı maliyeti','Sermaye azalışı','Vergi gideri','B','FİG: günlük fon net varlık değeri × yıllık oran / 365. Katılımcı hesabını azaltır, şirket gelir tablosuna yansır.'),
  q('LEVEL_2','muhasebe','Bireysel Emeklilik Muhasebesi','BES\'de devlet katkısı muhasebe kaydı nasıl yapılır?','Doğrudan gelir','Katılımcı adına ayrı hesapta takip edilir; şirket geliri değil','Özkaynak artışı','Prim indirimi','B','Devlet katkısı: katılımcıya ait, ayrı hesapta. Hak kazanılmadan çekilirse iade edilir. Şirket bilançosunda geçici yükümlülük.'),
  q('LEVEL_2','muhasebe','Bireysel Emeklilik Muhasebesi','Fon birim pay değeri (BPD) nasıl hesaplanır?','Toplam prim / katılımcı sayısı','Fonun net varlık değeri / tedavüldeki pay sayısı','Toplam katkı / ay sayısı','Sabit değer','B','BPD = NAV / toplam pay adedi. Günlük güncellenir. Katılımcının birikim değeri = elindeki pay × BPD.'),

  // ── Emeklilik Planı Değerlemesi ve Finansmanı [LEVEL_3/emeklilik] ──
  q('LEVEL_3','emeklilik','Emeklilik Planı Değerlemesi ve Finansmanı','Projected Unit Credit (PUC) yöntemi DB emeklilik planında nasıl çalışır?','Yalnızca geçmiş hizmet dikkate alınır','Her çalışma yılı bir birim fayda kazandırır; yansıtılan (projected) son maaşla değerlenir','Sabit katkı hesaplanır','Sadece fon getirisi','B','PUC: TFRS IAS 19 zorunlu. Birim kredi = maaş × hizmet yılı × fayda katsayısı, final maaşa göre iskonto edilir.'),
  q('LEVEL_3','emeklilik','Emeklilik Planı Değerlemesi ve Finansmanı','DB planında Actuarial Gain/Loss (aktüeryal kazanç/kayıp) nasıl oluşur?','Prim ödemelerinde','Varsayılan (mortalite, ücret artışı, iskonto oranı) ile gerçekleşen arasındaki fark','Yatırım kararlarında','Vergi değişikliğinde','B','A/L: iskonto oranı değişimi, ücret artış sapması, mortalite deneyimi. TFRS IAS 19: OCI\'da yansıtılır.'),
  q('LEVEL_3','emeklilik','Emeklilik Planı Değerlemesi ve Finansmanı','Emeklilik yükümlülüğünü iskonto etmek için hangi faiz oranı kullanılır?','Risk-free faiz','Yüksek kaliteli kurumsal tahvil getirisi (IAS 19); Solvency II\'de risk-free','Hazine bonosu','Banka mevduat faizi','B','IAS 19: yükümlülük = beklenen nakit akışları × yüksek kalite kurumsal bond getirisiyle iskonto. EIOPA risk-free kurve Solvency II için.'),
  q('LEVEL_3','emeklilik','Emeklilik Planı Değerlemesi ve Finansmanı','Past Service Cost (geçmişe dönük hizmet maliyeti) ne zaman ortaya çıkar?','Her yıl','Plan koşulları değiştirildiğinde; değişiklik tarihinde hemen gelir tablosuna alınır','Sadece plan başlangıcında','Aktüeryal değerleme sırasında','B','PSC: plan tadili (örn. fayda formülü iyileştirilmesi) → geçmişteki hizmet yıllarına ek fayda → anında kar/zarar etkisi.'),

  // ── Kesikli Olasılık Dağılımları [LEVEL_1/istatistik] ──
  q('LEVEL_1','istatistik','Kesikli Olasılık Dağılımları','Binom dağılımı B(n,p) için ortalama ve varyans nedir?','np ve np','np ve np(1-p)','np ve np²','n/p ve np','B','Binom: E[X]=np, Var[X]=np(1-p)=npq. n bağımsız Bernoulli denemesi, p başarı olasılığı.'),
  q('LEVEL_1','istatistik','Kesikli Olasılık Dağılımları','Poisson dağılımında P(X=k) formülü nedir?','e^{-λ}·λ^k / k!','λ^k / k!','e^λ·λ^k / k!','λ^k·e^{-k}','A','Poisson: P(X=k)=e^{-λ}λ^k/k!, k=0,1,2... E[X]=Var[X]=λ. Nadir olaylar için.'),
  q('LEVEL_1','istatistik','Kesikli Olasılık Dağılımları','Geometrik dağılım P(X=k)=(1-p)^{k-1}·p nedir ve ne anlama gelir?','Belirli sayıda başarı','İlk başarının k. denemede gerçekleşme olasılığı','Binom özel hali','Normal yaklaşım','B','Geometrik: ilk başarıyı beklemek için gerekli deneme sayısı. E[X]=1/p, Var[X]=(1-p)/p². Bellek-sız.'),
  q('LEVEL_1','istatistik','Kesikli Olasılık Dağılımları','Negatif binom dağılımı geometrik dağılımdan nasıl farklıdır?','Hiç farkı yok','r. başarıya ulaşmak için gereken deneme sayısını modeller; r=1 iken geometriye eşit','Sürekli bir dağılım','Simetrik','B','NB(r,p): r başarıya kadar gereken deneme sayısı. E[X]=r/p, Var[X]=r(1-p)/p².'),

  // ── Limit ve Süreklilik [LEVEL_1/matematik] ──
  q('LEVEL_1','matematik','Limit ve Süreklilik','lim_{x→0} sin(x)/x kaça eşittir?','0','1','∞','Tanımsız','B','Temel limit: lim_{x→0} sin(x)/x = 1. L\'Hôpital veya Taylor serisiyle ispatlanır. Trigonometrik limitlerin temeli.'),
  q('LEVEL_1','matematik','Limit ve Süreklilik','f(x) = (x²-4)/(x-2) fonksiyonunun x→2 limitini bulunuz.','2','4','Tanımsız','0','B','f(x)=(x+2)(x-2)/(x-2)=x+2 (x≠2). lim_{x→2}(x+2)=4. Nokta tanımsız ama limit mevcuttur.'),
  q('LEVEL_1','matematik','Limit ve Süreklilik','Bir fonksiyonun x=a noktasında sürekli olabilmesi için hangi üç koşul sağlanmalıdır?','Sadece f(a) tanımlı olmalı','f(a) tanımlı, lim_{x→a} f(x) mevcut ve lim_{x→a} f(x) = f(a)','Sadece limit mevcut olmalı','Türevi sıfır olmalı','B','Süreklilik: (1) f(a) tanımlı, (2) limit mevcut, (3) limit = f(a). Üçü birden gereklidir.'),
  q('LEVEL_1','matematik','Limit ve Süreklilik','lim_{x→∞} (3x²+2x)/(5x²-1) nedir?','0','3/5','∞','3','B','En yüksek dereceli terimler: (3x²)/(5x²)=3/5. Payda ve paydayı x² ile böl.'),

  // ── Net Prim Hesabı [LEVEL_2/sigorta-matematigi] ──
  q('LEVEL_2','sigorta-matematigi','Net Prim Hesabı','Tam ömür boyu sigorta (whole life) için net yıllık prim P_x hangi koşuldan bulunur?','APV(prim) > APV(fayda)','APV(prim) = APV(fayda); P_x = A_x / ä_x','APV(prim) = 1','Brüt prim - gider yükü','B','Eşitlik ilkesi: P_x·ä_x = A_x → P_x = A_x/ä_x. ä_x = (1-A_x)/d ilişkisi de kullanılır.'),
  q('LEVEL_2','sigorta-matematigi','Net Prim Hesabı','n-yıllık dönem sigortası (term insurance) net primi nasıl bulunur?','A_x / ä_x','A_{x:n|}^1 / ä_{x:n|}','A_x · i','n · A_x','B','Term P: P^1_{x:n|} = A_{x:n|}^1 / ä_{x:n|}. Pay: n-yıl içinde ölüm tazminatının APV. Payda: n-yıl anüite APV.'),
  q('LEVEL_2','sigorta-matematigi','Net Prim Hesabı','Endowment (karma) sigortasında net prim bileşenleri nelerdir?','Yalnızca ölüm tazminatı','Ölüm tazminatı + hayatta kalma ödemesi; APV = A_{x:n|}^1 + A_{x:n|}^{E}','Yalnızca birikim','Reasürans primi','B','Endowment: A_{x:n|} = A_{x:n|}^1 (ölüm) + _n·E_x (pure endowment). Net prim: A_{x:n|}/ä_{x:n|}.'),
  q('LEVEL_2','sigorta-matematigi','Net Prim Hesabı','i=%6, A_40=0.161, ä_40=12.875 ise P_40 (whole life net prim) kaçtır?','%1.25','%1.55','%1.80','%2.10','A','P_40 = A_40/ä_40 = 0.161/12.875 ≈ 0.0125 = %1.25 (1000 TL için 12.5 TL/yıl).'),

  // ── Poliçe Modifikasyonları — Muafiyet ve Limitler [LEVEL_2/risk-analizi] ──
  q('LEVEL_2','risk-analizi','Poliçe Modifikasyonları — Muafiyet ve Limitler','Düz indirimsizlik (straight deductible / ordinary deductible) ile franchise (franchising) farkı nedir?','Aynıdır','Düz: hasar−d (d altı ödemez); franchise: hasar d\'yi aşarsa tamamı ödenir, d altı hiç ödemez','Franchise daha pahalı','Düz indirimsizlik tüm hasarı öder','B','Franchise/straight: franchise=d iken hasar=d ise tam ödeme. Düz: d altı sıfır, d üstü hasar-d. İkisi d noktasında farklı davranır.'),
  q('LEVEL_2','risk-analizi','Poliçe Modifikasyonları — Muafiyet ve Limitler','Politika limiti (policy limit) u ile birlikte hasar X iken sigorta ödemesi nedir?','min(X, u)','max(X-u, 0)','X','u','A','Poliçe limiti: sigorta ödemesi = min(X, u). u\'yu aşan kısım sigortalı üstünde kalır.'),
  q('LEVEL_2','risk-analizi','Poliçe Modifikasyonları — Muafiyet ve Limitler','Koinsürans (coinsurance) nedir?','Reasürans türü','Sigortalının hasarın belirli yüzdesini (α) kendisi üstlenmesi; sigortacı (1-α) öder','Prim indirimi','Deductible türü','B','Coinsurance: yüksek değer sigortacılığında. Eksik sigorta (underinsurance) halinde koinsürans cezası uygulanır.'),
  q('LEVEL_2','risk-analizi','Poliçe Modifikasyonları — Muafiyet ve Limitler','d indirimsizlik ve u limit birlikte uygulanınca sigorta ödemesi nasıldır?','min(X,u)-d','min(X,u) - min(X,d) = min(max(X-d,0), u-d)','max(X-d,0)','min(X-d, u)','B','Limited loss: [(X-d)_+ ] limited to (u-d). Yani min(max(X-d,0), u-d). Sigorta şeridi [d,u] aralığını kapsar.'),

  // ── Sigorta Sözleşmesi ve Tarafları [LEVEL_1/mevzuat] ──
  q('LEVEL_1','mevzuat','Sigorta Sözleşmesi ve Tarafları','Sigorta sözleşmesinin temel unsurları nelerdir?','Prim ve teminat','Risk, prim, tazminat yükümlülüğü ve süre','Sadece prim ve poliçe numarası','Sigortalı ve acente','B','Sigorta sözleşmesi: (1) sigortalanabilir menfaat, (2) risk, (3) prim, (4) tazminat yükümlülüğü, (5) süre.'),
  q('LEVEL_1','mevzuat','Sigorta Sözleşmesi ve Tarafları','Sigorta ettiren ile sigortalı arasındaki fark nedir?','Aynı kişilerdir','Sigorta ettiren (policyholder) sözleşmeyi yapıp primi ödeyen; sigortalı üzerinde risk gerçekleşen kişi','Sigortalı primi öder','Sadece hayat sigortasında ayrım vardır','B','Örnek: işveren (sigorta ettiren) çalışanı (sigortalı) için sağlık sigortası yaptırır. İkisi farklı kişi olabilir.'),
  q('LEVEL_1','mevzuat','Sigorta Sözleşmesi ve Tarafları','Lehdar (beneficiary) kimdir?','Prim ödeyen','Hasar anında tazminatı alacak kişi; sigortalıdan farklı olabilir','Sigorta şirketi','Acente','B','Lehdar: ölüm tazminatının alıcısı (hayat). Sigortalı sağken değiştirebilir. 2 tür: kabil-i rücu (değiştirilebilir) ve gayrikabili rücu.'),
  q('LEVEL_1','mevzuat','Sigorta Sözleşmesi ve Tarafları','İnce(e) beyan yükümlülüğü (disclosure duty) ne anlama gelir?','Sigorta şirketinin raporlama yükümlülüğü','Sigortalının tüm önemli bilgileri sigortacıya dürüstçe beyan etme zorunluluğu; ihlal iptal sebebidir','Prim beyannamesi','Poliçe yenileme bildirimi','B','Uberrima fides (en yüksek iyi niyet): sigortacı risk değerlendirmesi için beyana güvenir. Yanlış/eksik beyan → iptal/tazminat reddi.'),

  // ── Türkiye'de Aktüerlik Mesleği ve Yetkilendirme [LEVEL_1/mevzuat] ──
  q('LEVEL_1','mevzuat','Türkiye\'de Aktüerlik Mesleği ve Yetkilendirme','Türkiye\'de aktüerleri düzenleyen kurum hangisidir?','SPK','Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu (SEDDK)','BDDK','Hazine Müsteşarlığı','B','2022\'de Hazine\'den ayrılan SEDDK; sigorta, reasürans ve BES şirketlerini denetler. Aktüer sertifikasyonu da SEDDK bünyesinde.'),
  q('LEVEL_1','mevzuat','Türkiye\'de Aktüerlik Mesleği ve Yetkilendirme','Türkiye Aktüerler Derneği (TAD) hangi amaçla kurulmuştur?','Sigorta şirketlerini denetlemek','Aktüerlik mesleğini geliştirmek, etik standartlar belirlemek ve mesleki eğitim vermek','Prim tarifelerini belirlemek','Reasürans anlaşmalarını onaylamak','B','TAD: mesleki örgüt. IAA (Uluslararası Aktüerler Birliği) üyesi. Sınav, etik, sürekli eğitim programları yürütür.'),
  q('LEVEL_1','mevzuat','Türkiye\'de Aktüerlik Mesleği ve Yetkilendirme','Sigorta şirketinde sorumlu aktüerin görevleri nelerdir?','Sadece hasar tazminatı ödemek','Teknik karşılıkların yeterliliğini onaylamak, prim tarifelerini hazırlamak ve aktüeryal raporları imzalamak','Pazarlama stratejisi','Müşteri hizmetleri','B','Sorumlu aktüer: teknik karşılık bildirimi, tarife aktüeryal gerekçesi, SEDDK\'ya yıllık aktüeryal rapor. Şirkette tek atama.'),
  q('LEVEL_1','mevzuat','Türkiye\'de Aktüerlik Mesleği ve Yetkilendirme','Aktüerlik sınavlarında hangi uluslararası standart temel alınmaktadır?','CFA standartları','SOA/CAS benzeri modüler sınav sistemi; IAA eğitim standartlarına uygun','MBA müfredatı','Hukuk fakültesi müfredatı','B','Türkiye aktüerlik sınavları: matematiksel, finansal ve sigorta modülleri. IAA eğitim standartlarına paralel yapı.'),

  // ── Vektörler ve Matris İşlemleri [LEVEL_1/matematik] ──
  q('LEVEL_1','matematik','Vektörler ve Matris İşlemleri','2×2 matris A = [[a,b],[c,d]] için det(A) nedir?','a+d','ad-bc','ab-cd','ac-bd','B','det([[a,b],[c,d]]) = ad − bc. 2×2 için çapraz çarpım farkı.'),
  q('LEVEL_1','matematik','Vektörler ve Matris İşlemleri','İki vektör u ve v için iç çarpım (dot product) u·v nedir?','||u||·||v||','u₁v₁ + u₂v₂ + u₃v₃ (3 boyutlu)','||u-v||','||u||+||v||','B','u·v = Σuᵢvᵢ. Geometrik: u·v = ||u||·||v||·cos(θ). Dik ise u·v = 0.'),
  q('LEVEL_1','matematik','Vektörler ve Matris İşlemleri','Matris çarpımı AB ile BA neden genellikle farklıdır?','Her zaman aynıdır','Matris çarpımı değişme (komütatif) özelliğini sağlamaz; AB ≠ BA genel durumda','Sadece kare matrislerde','B her zaman sıfır matris','B','Matris çarpımı: (AB)ᵢⱼ = ΣAᵢₖBₖⱼ. Değişme özelliği yoktur. Ancak asosiyatif ve dağılma özelliği vardır.'),
  q('LEVEL_1','matematik','Vektörler ve Matris İşlemleri','Bir A matrisinin tersi A⁻¹ var olabilmesi için ne gerekir?','Simetrik olmalı','det(A) ≠ 0 (tekil olmayan/non-singular matris)','A kare değil','Tüm elemanlar pozitif','B','A⁻¹ mevcutsa: A·A⁻¹ = I. Şart: det(A) ≠ 0. Eğer det=0 → tekil matris, tersi yoktur.'),

  // ══════════════════════════════════════════════════════════════
  // 2 SORULU KONULAR → +3 soru ekle
  // ══════════════════════════════════════════════════════════════

  // ── Birleşik Oran, Hasar Oranı, Masraf Oranı [LEVEL_2/muhasebe] ──
  q('LEVEL_2','muhasebe','Birleşik Oran, Hasar Oranı, Masraf Oranı','Hasar oranı (loss ratio) nasıl hesaplanır?','Net prim / hasar','Ödenen hasarlar / Kazanılmış primler','Hasar / Yazılan primler','IBNR / Toplam hasar','B','Loss Ratio = Gerçekleşen hasarlar / Kazanılmış primler. %60 → prim gelirinin %60\'ı hasara gidiyor.'),
  q('LEVEL_2','muhasebe','Birleşik Oran, Hasar Oranı, Masraf Oranı','Masraf oranı (expense ratio) nedir?','Hasar/prim','Giderler / Yazılan (veya kazanılmış) primler','Rezerv / Prim','Komisyon / Reasürans','B','Expense ratio = (satış komisyonu + genel gider) / prim. Hasar oranı + masraf oranı = birleşik oran.'),
  q('LEVEL_2','muhasebe','Birleşik Oran, Hasar Oranı, Masraf Oranı','Birleşik oran %105 ise bu ne anlama gelir?','Şirket %5 teknik kâr etti','Her 100 TL prim için 105 TL hasar+gider çıktı; teknik zarar var','Prim yeterli','Şirket iflas etti','B','CR > 100%: teknik zarar. CR = 105% → 100 TL primin 105 TL harcamaya karşılık geldiği anlamına gelir; yatırım geliriyle telafi edilebilir.'),

  // ── Dağıtılabilir Kazançlar ve Embedded Value [LEVEL_3/finans-yatirim] ──
  q('LEVEL_3','finans-yatirim','Dağıtılabilir Kazançlar ve Embedded Value','Distributable Earnings (dağıtılabilir kazançlar) nedir?','Muhasebe kârı','Dönem kâr-zararı + required capital salınımı − vergi; hissedara nakit çekilebilir miktar','Net prim','Rezerv artışı','B','DE = net gelir − ΔRequired Capital. Ekonomik bakışla şirketten çekilebilecek nakit. EV analizi girdi verisi.'),
  q('LEVEL_3','finans-yatirim','Dağıtılabilir Kazançlar ve Embedded Value','VNB margin (VNB marjı) nedir?','VNB / toplam prim','VNB / APE (Annual Premium Equivalent); yeni iş kârlılık göstergesi','VNB / rezerv','VNB / gider','B','APE = yıllık prim + tek prim/10. VNB margin = VNB/APE. Şirketler arası kârlılık karşılaştırması için normalize edilmiş gösterge.'),
  q('LEVEL_3','finans-yatirim','Dağıtılabilir Kazançlar ve Embedded Value','EV Operating Return on EV (EVOP) nedir?','Muhasebe ROE','Expected return on EV + VNB + experience variances; operasyonel EV performans göstergesi','Net prim getirisi','Aktüeryal açık','B','EV operating return = [beklenen getiri + VNB + deneyim sapmaları] / dönem başı EV. Varsayım değişikliklerini dışlar.'),

  // ── Getiri Eğrileri — Spot ve Forward Oranlar [LEVEL_2/finans-teorisi] ──
  q('LEVEL_2','finans-teorisi','Getiri Eğrileri — Spot ve Forward Oranlar','Spot oran (zero-coupon rate) nedir?','Kupon tahvil getirisi','Bugünden belirli bir vadeye kadar olan sıfır kuponlu tahvil getirisi','Kısa vadeli gecelik oran','Forward sözleşme faizi','B','Spot rate s(t): bugünden t yıla kadar sıfır kupon. 1 TL yatır, (1+s(t))^t al. Getiri eğrisinin yapı taşı.'),
  q('LEVEL_2','finans-teorisi','Getiri Eğrileri — Spot ve Forward Oranlar','Forward oran f(t₁,t₂) nasıl hesaplanır?','[s(t₁)+s(t₂)]/2','[(1+s(t₂))^t₂ / (1+s(t₁))^t₁]^{1/(t₂-t₁)} − 1','s(t₂)−s(t₁)','s(t₂)·t₂/t₁','B','Forward: (1+s₂)^t₂ = (1+s₁)^t₁ · (1+f)^{t₂-t₁}. t₁\'den t₂\'ye arasındaki döneme ait bugünden kilitlenmiş faiz.'),
  q('LEVEL_2','finans-teorisi','Getiri Eğrileri — Spot ve Forward Oranlar','Bootstrap yöntemi getiri eğrisini nasıl inşa eder?','Regresyon analizi','Piyasada işlem gören kuponlu tahviller kullanılarak ardışık olarak spot oranlar hesaplanır','Monte Carlo','Interpolasyon','B','Bootstrap: kısa vadeli spot oranlardan başla, her vade için kuponlu tahvil fiyatını kullanarak bir sonraki spot oranı türet.'),

  // ── Hayat Anüiteleri — Yıllık ve Sürekli [LEVEL_3/hayat-sigortalari] ──
  q('LEVEL_3','hayat-sigortalari','Hayat Anüiteleri — Yıllık ve Sürekli','Sürekli ömür boyu anüite ā_x nasıl tanımlanır?','Σ_{k=0}^∞ v^k·_k·p_x','∫_0^∞ v^t·_t·p_x dt','A_x/d','1/P_x','B','ā_x = E[ā_{T_x|}] = ∫_0^∞ e^{-δt}·_t·p_x dt. Sürekli ödemelerin beklenen bugünkü değeri.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Anüiteleri — Yıllık ve Sürekli','Kesinlikli anüite (annuity-certain) ile hayat anüitesi farkı nedir?','Aynıdır','Kesinlikli: sabit n yıl ödeme (hayatta olup olmadığına bakılmaksızın). Hayat: ölüme kadar ödeme, ömür süreci rassal','Hayat anüitesi daha ucuz','Kesinlikli yalnızca emeklilikte','B','Hayat anüitesi: ödeme durma riski = erken ölüm. Kesinlikli: her koşulda n yıl ödeme. Hayat > kesinlikli genellikle.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Anüiteleri — Yıllık ve Sürekli','Ertelenmiş hayat anüitesi _{n|}ā_x nedir?','Hemen başlayan anüite','n yıl sonra başlayan hayat anüitesinin bugünkü değeri; _n·E_x · ā_{x+n}','n yıllık kesinlikli anüite','Hayat sigortası primleri','B','_{n|}ā_x = ∫_n^∞ e^{-δt}·_t·p_x dt = _n·E_x · ā_{x+n}. Emeklilik anüitesi değerlemesinde temel.'),

  // ── Maximum Likelihood Tahmini [LEVEL_2/risk-analizi] ──
  q('LEVEL_2','risk-analizi','Maximum Likelihood Tahmini','MLE (En Çok Olabilirlik) tahmincisi nasıl bulunur?','Ortalama alınarak','Log-olabilirlik fonksiyonunun θ\'ya göre türevi sıfıra eşitlenerek','Momentler eşitlenerek','Bayes yöntemiyle','B','MLE: L(θ|x) = Πf(xᵢ;θ). ℓ(θ) = ln L. dℓ/dθ = 0 → θ̂_MLE. Büyük örnekte tutarlı ve asimptotik normal.'),
  q('LEVEL_2','risk-analizi','Maximum Likelihood Tahmini','Üstel dağılım Exp(λ) için MLE ile λ tahmincisi nedir?','Σxᵢ/n','1/x̄ (örneklem ortalamasının tersi)','Σxᵢ²','Min(xᵢ)','B','Exp: f(x;λ)=λe^{-λx}. ℓ(λ)=n·ln(λ)-λΣxᵢ. dℓ/dλ=n/λ-Σxᵢ=0 → λ̂=n/Σxᵢ=1/x̄.'),
  q('LEVEL_2','risk-analizi','Maximum Likelihood Tahmini','MLE tahmincisinin invaryant özelliği nedir?','Her dağılımda sapmasız','g(θ̂_MLE) = MLE tahmincisi g(θ) için de MLE\'dir; fonksiyon dönüşümü geçerliliği korur','Minimum varyansı garantiler','Küçük örneklerde de iyi','B','İnvaryans: g monoton ise g(θ̂) = ĝ. Örn: λ̂=1/x̄ ise ortalama tahmini μ̂=1/λ̂=x̄.'),

  // ── Nelson-Aalen ve Kernel Yoğunluk Tahmini [LEVEL_2/risk-analizi] ──
  q('LEVEL_2','risk-analizi','Nelson-Aalen ve Kernel Yoğunluk Tahmini','Nelson-Aalen kümülatif tehlike tahmincisi Ĥ(t) nedir?','∑ dᵢ/nᵢ (sıralı ölüm zamanlarında)','Kaplan-Meier','Parametrik MLT','Kernel yoğunluğu','A','Nelson-Aalen: Ĥ(t) = Σ_{tᵢ≤t} dᵢ/nᵢ. dᵢ: t anındaki olay sayısı, nᵢ: risk kümesi. Sansürlü veri için.'),
  q('LEVEL_2','risk-analizi','Nelson-Aalen ve Kernel Yoğunluk Tahmini','Kernel yoğunluk tahmincisi (KDE) nedir?','Histogram','Her gözlem noktasına çekirdek fonksiyonu (Gaussian, Epanechnikov) yerleştirerek sürekli yoğunluk tahmini','Parametrik MLE','Bayesian tahminci','B','KDE: f̂(x) = (1/nh)·Σ K((x-xᵢ)/h). h: bant genişliği. Histogram\'ın düzleştirilmiş versiyonu.'),
  q('LEVEL_2','risk-analizi','Nelson-Aalen ve Kernel Yoğunluk Tahmini','Kaplan-Meier tahmincisi ile Nelson-Aalen farkı nedir?','KM daha az veri ister','KM hayatta kalma fonksiyonu Ŝ(t)=Π(1-dᵢ/nᵢ). Nelson-Aalen kümülatif tehlike Ĥ; küçük örneklerde KM pozitif sapmayı daha iyi yönetir','Aynı sonucu verir','NA parametrik','B','İlişki: Ŝ_NA(t)=exp(-Ĥ(t)). Büyük örneklerde benzer; küçük örneklerde NA hayatta kalma olasılığını biraz farklı verir.'),

  // ── Opsiyon Stratejileri [LEVEL_2/finans-teorisi] ──
  q('LEVEL_2','finans-teorisi','Opsiyon Stratejileri (Spread, Collar, Straddle)','Bull call spread nedir?','Sadece call satın almak','Daha düşük K₁\'den call al, daha yüksek K₂\'den call sat; sınırlı kâr, sınırlı kayıp','Call ve put satın almak','Vadeli işlem','B','Bull call spread: C(K₁)-C(K₂), K₁<K₂. Maliyet düşer; kâr potansiyeli K₂-K₁ ile sınırlı. Orta derece yükseliş beklentisi.'),
  q('LEVEL_2','finans-teorisi','Opsiyon Stratejileri (Spread, Collar, Straddle)','Straddle stratejisi nasıl kurulur ve ne zaman kârlıdır?','Call sat + put sat','Aynı K ve vadeye sahip call al + put al; büyük fiyat hareketi (her iki yönde) beklentisinde','Sadece call al','Kısa vadeli nötr beklenti','B','Long straddle: kârlı olması için fiyatın K\'dan |hareket| > C+P prim toplamı kadar uzaklaşması gerekir. Volatilite oynarken kullanılır.'),
  q('LEVEL_2','finans-teorisi','Opsiyon Stratejileri (Spread, Collar, Straddle)','Collar stratejisi nedir?','Long call + long put','Hisse tut + put al (koruma) + call sat (prim geliri); düşük maliyet ile sınırlı risk','Sadece put almak','Futures kullanmak','B','Collar: hisse portföyünü ucuza koruma. Call satışından elde edilen prim put maliyetini karşılar. Kâr ve kayıp her ikisi de sınırlı.'),

  // ── Risk Bazlı Sermaye Gereksinimleri [LEVEL_2/muhasebe] ──
  q('LEVEL_2','muhasebe','Risk Bazlı Sermaye Gereksinimleri','Risk bazlı sermaye (RBC) sisteminin amacı nedir?','Teknik karşılıkları azaltmak','Sigorta şirketinin üstlendiği risklere göre asgari sermayeyi belirlemek; sermaye yetersizliğini erken uyarmak','Prim gelirini artırmak','Vergi avantajı sağlamak','B','RBC (ABD): C0=varlık riski, C1=sigorta riski, C2=faiz oranı, C3=iş riski. Formül ile birleştirilerek asgari sermaye hesaplanır.'),
  q('LEVEL_2','muhasebe','Risk Bazlı Sermaye Gereksinimleri','Solvency I ve Solvency II arasındaki temel fark nedir?','Aynı sistemdir','Solvency I prim/hasar bazlı sabit oran; Solvency II şirketin gerçek risk profiline dayalı ekonomik sermaye','Solvency II daha basit','Solvency I ekonomik değerleme','B','Solvency I: max(%18·prim, %26·hasar). Solvency II: SCR=%99.5 VaR. Risk duyarlı, ekonomik bilanço.'),
  q('LEVEL_2','muhasebe','Risk Bazlı Sermaye Gereksinimleri','TFRS/UFRS çerçevesinde sigorta şirketi bilançosunda teknik karşılıkların sermayeye etkisi nedir?','Sermayeyi artırır','Karşılık yeterli ise kâr azalır → özkaynak azalır; yetersiz ise gelecekte reserve strengthening ile kâr erimesi','Etkisizdir','Vergi avantajı sağlar','B','Karşılık gideri → kâr azalır → dağıtılmamış kâr azalır → özkaynak azalır. Aşırı rezerv konservatif; az rezerv → risk.'),

  // ── Sigortanın Tanımı ve İşlevleri [LEVEL_1/mevzuat] ──
  q('LEVEL_1','mevzuat','Sigortanın Tanımı ve İşlevleri','Sigorta ekonomik açıdan ne işlev görür?','Tasarruf aracı','Bireysel riski havuzlayarak öngörülemeyen kayıpları paylaşma (risk pooling) ve sermayeyi korunma amaçlı kullandırma','Yatırım aracı','Kredi aracı','B','Sigorta: büyük sayılar kanunu ile bireysel risk belirsizliği azalır. Risk transferi + risk havuzu + tazminat işlevi.'),
  q('LEVEL_1','mevzuat','Sigortanın Tanımı ve İşlevleri','Sigorta edilebilir risk için hangi temel kriterler aranır?','Yalnızca olasılıklı olmak','Ölçülebilir, geniş popülasyona yayılabilir, tesadüfi (sigortalının kontrolü dışında), aşırı büyük olmayan kayıp','Sadece mali risk','Her türlü olay','B','Sigortalanabilir risk: insurable interest, fortuitous loss, large number of similar units, determinable loss, affordable premium.'),
  q('LEVEL_1','mevzuat','Sigortanın Tanımı ve İşlevleri','Ahlaki tehlike (moral hazard) ve olumsuz seçilim (adverse selection) sigortacılıkta neden problem oluşturur?','Prim gelirini artırır','Moral hazard: sigortalı davranışını kötüleştirir. Adverse selection: yüksek riskli bireyler sigortaya daha fazla yönelir → prim dengesizliği','Sadece sağlık sigortasında','Risk havuzu işlemez hale gelir fakat çözüm yoktur','B','Moral hazard önlemi: franchise, muafiyet. Adverse selection önlemi: risk sınıflandırması, beyan zorunluluğu, sağlık muayenesi.'),

  // ── Solvency II — Üç Sütunlu Yapı [LEVEL_3/finans-yatirim] ──
  q('LEVEL_3','finans-yatirim','Solvency II — Üç Sütunlu Yapı','Solvency II\'nin üç sütunu nelerdir?','Prim, rezerv, reasürans','Sütun 1: nicel gereksinimler (SCR/MCR). Sütun 2: yönetişim/ORSA. Sütun 3: raporlama/kamuoyu açıklaması','Risk, sermaye, denetim','BEL, RA, CSM','B','Pillar 1: SCR/MCR hesabı + teknik karşılıklar. Pillar 2: ORSA, risk yönetimi. Pillar 3: SFCR, RSR, Solvency ve Mali Durum Raporu.'),
  q('LEVEL_3','finans-yatirim','Solvency II — Üç Sütunlu Yapı','SFCR (Solvency and Financial Condition Report) nedir?','İç yönetim raporu','Solvency II Sütun 3 kapsamında kamuoyuna açıklanan sigorta şirketi solvency raporu','Aktüeryal değerleme belgesi','Denetçi raporu','B','SFCR: yıllık, kamuoyu. İşletme, yönetişim, risk profili, değerleme, sermaye yönetimi bölümleri. Şeffaflık amaçlı.'),
  q('LEVEL_3','finans-yatirim','Solvency II — Üç Sütunlu Yapı','Own Funds (özkaynak) Tier sınıflandırması neden yapılır?','Vergi amaçlı','Farklı kalitedeki sermayenin SCR ve MCR karşılamadaki ağırlığını belirlemek; Tier 1 en kaliteli','Muhasebe standardı','Reasürans amaçlı','B','Tier 1: temel özkaynak (adi hisse, dağıtılmamış kâr). Tier 2/3: alt borç gibi kalemler. SCR için Tier 1 min %50 olmalı.'),

  // ── Varyans Analizi (ANOVA) [LEVEL_1/istatistik] ──
  q('LEVEL_1','istatistik','Varyans Analizi (ANOVA)','Tek yönlü ANOVA\'nın sıfır hipotezi nedir?','Tüm gruplar farklıdır','Tüm grup ortalamaları eşittir: H₀: μ₁=μ₂=...=μk','Gruplar arası varyans sıfır','Sadece iki grup karşılaştırılır','B','H₀: μ₁=μ₂=...=μₖ. H₁: En az bir ortalama farklı. F = (grup arası ortalama kare) / (grup içi ortalama kare).'),
  q('LEVEL_1','istatistik','Varyans Analizi (ANOVA)','ANOVA\'da F istatistiği nasıl yorumlanır?','F küçükse H₀ reddedilir','F büyükse (kritik değerin üstündeyse) H₀ reddedilir; gruplar arasında anlamlı fark var','F=1 H₀ reddeder','F hiç kullanılmaz','B','F = MSB / MSW. MSB büyük → gruplar arası fark büyük → H₀ reddi. F ~ F(k-1, N-k) dağılımı altında.'),
  q('LEVEL_1','istatistik','Varyans Analizi (ANOVA)','ANOVA varsayımları nelerdir?','Sadece normallik','Normallik, varyans homojenliği (homoscedasticity) ve gözlemlerin bağımsızlığı','Yalnızca bağımsızlık','Poisson dağılımı','B','ANOVA varsayımları: (1) her grupta normal dağılım, (2) eşit varyans (Levene testi), (3) bağımsız gözlemler.'),

  // ══════════════════════════════════════════════════════════════
  // 3 SORULU KONULAR → +2 soru ekle
  // ══════════════════════════════════════════════════════════════

  // ── Aktüeryal Risk Yönetimi — Hayat Riskleri [LEVEL_3/finans-yatirim] ──
  q('LEVEL_3','finans-yatirim','Aktüeryal Risk Yönetimi — Hayat Riskleri','Mortalite riski ile uzun ömür riski arasındaki fark nedir?','Aynı risk','Mortalite: beklenenden erken ölüm (hayat sigortacısı için kayıp). Uzun ömür: beklenenden geç ölüm (emeklilik anüitesi için kayıp)','İkisi de yalnızca emekliliği etkiler','Sadece reasürans için önemli','B','Hayat sigortası: mortalite artışı = daha çok hasar = kayıp. Emeklilik anüitesi: mortalite azalışı = daha uzun ödeme = kayıp.'),
  q('LEVEL_3','finans-yatirim','Aktüeryal Risk Yönetimi — Hayat Riskleri','Hayat sigortasında faiz oranı riski nasıl ortaya çıkar?','Prim gelirleri azalır','Garanti edilen poliçe faiz oranı piyasa faizinin üstünde kalırsa aktüeryal kayıp; yatırım getirileri yükümlülükleri karşılamayabilir','Sigortalı sayısı azalır','Hasar frekansı değişir','B','Garantili faiz (crediting rate) riski: ürün tasarımında garanti edilen oran, piyasa faizi düştüğünde spread tersine döner.'),

  // ── Belirli İntegral ve Uygulamaları [LEVEL_1/matematik] ──
  q('LEVEL_1','matematik','Belirli İntegral ve Uygulamaları','∫₀¹ x² dx nedir?','1/2','1/3','1/4','2/3','B','∫x² dx = x³/3 + C. [x³/3]₀¹ = 1/3 - 0 = 1/3.'),
  q('LEVEL_1','matematik','Belirli İntegral ve Uygulamaları','Beklenen değer E[X] = ∫xf(x)dx formülünün integrasyon ile ilişkisi nedir?','Türev','Yoğunluk fonksiyonu f(x) ile ağırlıklı ortalama; belirlenen integral ile hesaplanır','Limit','Seri','B','E[X]=∫_{-∞}^{∞} x·f(x)dx. Sürekli rassal değişkenlerde beklenti, yoğunluğun x ile çarpımının integralidir.'),

  // ── Bileşik Poisson Süreci ve Beklenen Değer [LEVEL_2/sigorta-matematigi] ──
  q('LEVEL_2','sigorta-matematigi','Bileşik Poisson Süreci ve Beklenen Değer','Bileşik Poisson sürecinde S(t) = ΣXᵢ için E[S(t)] nedir?','λt','λt·E[X]','E[X]','λ·E[X²]','B','E[S(t)] = E[N(t)]·E[X] = λt·μ. Bağımsızlık ve N(t)~Poisson(λt) varsayımıyla.'),
  q('LEVEL_2','sigorta-matematigi','Bileşik Poisson Süreci ve Beklenen Değer','Bileşik Poisson\'da Var[S(t)] formülü nedir?','λt·Var[X]','λt·E[X²]','λt·(E[X])²','(λt)²·Var[X]','B','Var[S(t)] = λt·E[X²] (Wald kimliği). Çünkü Var[N]=E[N]=λt için bileşik formül: Var[S]=E[N]·E[X²]+Var[N]·(E[X])²-E[N]·(E[X])² = λt·E[X²].'),

  // ── CAPM ve Etkin Sınır [LEVEL_3/finans-yatirim] ──
  q('LEVEL_3','finans-yatirim','CAPM ve Etkin Sınır','Etkin sınır (efficient frontier) ve CML arasındaki ilişki nedir?','Aynı eğridir','CML risksiz varlıkla etkin sınırı tanjant noktasında (market portfolio) keser; tanjant portföy = piyasa portföyü','Etkin sınır CML\'yi içerir','CML yalnızca hisse senedine uygulanır','B','CML: rf + [(E(rm)-rf)/σm]·σp. Tanjant nokta: maximum Sharpe oranlı portföy = piyasa portföyü. Etkin sınırın üstüne geçmez.'),
  q('LEVEL_3','finans-yatirim','CAPM ve Etkin Sınır','Sistematik olmayan riskin portföy büyüklüğüyle ilişkisi nedir?','Sabit kalır','Portföy büyüdükçe çeşitlendirme ile azalır ve sıfıra yaklaşır','Artar','Sistematik riskle aynı davranır','B','Spesifik risk: N büyürken Var_spesifik → 0. Sistematik risk: β² · σ²_m; çeşitlendirme ile elimine edilemez.'),

  // ── Değişmeli (Reversionary) Anüiteler [LEVEL_3/hayat-sigortalari] ──
  q('LEVEL_3','hayat-sigortalari','Değişmeli (Reversionary) Anüiteler','Reversionary anüite nedir?','Her iki kişi hayattayken ödenen anüite','İlk kişi öldükten sonra ikinci kişi hayatta olduğu sürece ödenen anüite','Ölüm sigortası','Sadece kadınlara ödenen','B','Reversionary annuity to y upon death of x: ödemeler x\'in ölümüyle başlar, y\'nin hayatı boyunca devam eder. Eş emeklilik planları için.'),
  q('LEVEL_3','hayat-sigortalari','Değişmeli (Reversionary) Anüiteler','Reversionary anüite APV\'si nasıl hesaplanır?','ā_y','ā_y − ā_{xy}; last-survivor eksi joint life anüitesi farkı','ā_x + ā_y','ā_{xy}','B','APV = ā_{y|x} = ā_y − ā_{xy}. y\'nin tek başına anüitesinden çift hayat anüitesi çıkarılır.'),

  // ── Determinant ve Ters Matris [LEVEL_1/matematik] ──
  q('LEVEL_1','matematik','Determinant ve Ters Matris','Cramer kuralı ne için kullanılır?','Matris çarpımı','n×n doğrusal denklem sistemi Ax=b için xᵢ = det(Aᵢ)/det(A) formülüyle çözüm bulma','Özdeğer hesabı','Matris transpozesi','B','Cramer: xᵢ = det(Aᵢ)/det(A). Aᵢ: A\'nın i. sütunu b ile değiştirilen matris. Küçük sistemlerde pratik.'),
  q('LEVEL_1','matematik','Determinant ve Ters Matris','3×3 matrisin tersi A⁻¹ hangi formülle hesaplanır?','A/det(A)','(1/det(A))·adj(A); adj=kofaktör matrisinin transpozu','A²','det(A)·A','B','A⁻¹=(1/det(A))·adj(A). adj(A)=C^T (kofaktörler transpozu). det(A)≠0 şartıyla mevcut.'),

  // ── Fiyatlandırma ve Tarife — GLM Yaklaşımı [LEVEL_3/hayatdisi-sigortalar] ──
  q('LEVEL_3','hayatdisi-sigortalar','Fiyatlandırma ve Tarife — GLM Yaklaşımı','Hayat dışı sigortacılıkta sıklık modellemesi için hangi GLM ailesi uygundur?','Normal','Poisson regresyonu (log bağlantısı ile); sayım verisi için standart','Binomial','Gamma','B','Frekans: Y ~ Poisson, g(μ)=log(μ)=Xβ. Hasar sayısı non-negatif tam sayı; Poisson veya negatif binom.'),
  q('LEVEL_3','hayatdisi-sigortalar','Fiyatlandırma ve Tarife — GLM Yaklaşımı','Hasar şiddeti modellemesinde hangi dağılım ve bağlantı fonksiyonu tercih edilir?','Poisson/log','Gamma veya Lognormal / log bağlantısı; pozitif sürekli hasar büyüklüğü için','Normal/identity','Binomial/logit','B','Şiddet: Y>0 sürekli, sağ çarpık. Gamma GLM: log bağlantısı, çarpımlı tarife çarpanları. Tweedie ikisini birleştirir.'),

  // ── Gelir Tablosu Hazırlama [LEVEL_2/muhasebe] ──
  q('LEVEL_2','muhasebe','Gelir Tablosu Hazırlama','Sigorta şirketinin gelir tablosunda "teknik gelirler" nelerdir?','Sadece yatırım geliri','Kazanılmış primler, teknik olmayan yatırım geliri payı ve diğer teknik gelirler','Muhasebe kârı','Reasürans gelirleri','B','Teknik gelirler: KP (kazanılmış prim) = YP - ΔKPK. Hasarlar çıkarılınca teknik kâr/zarar bulunur.'),
  q('LEVEL_2','muhasebe','Gelir Tablosu Hazırlama','Ertelenmiş gelir (deferred income) hayat sigortasında nedir?','Aktüeryal fazla','Kazanılmamış primler karşılığı: tahsil edilen primin henüz kapsam dönemi dolmamış kısmı','Net prim','Hasar ödemeleri','B','Kazanılmamış prim: örneğin 1 Temmuz başlayan yıllık poliçe — 31 Aralık bilançosunda 6 aylık prim ertelenmiş gelir.'),

  // ── Hayat Sigortası Ürünleri — Tam Hayat [LEVEL_2/sigorta-matematigi] ──
  q('LEVEL_2','sigorta-matematigi','Hayat Sigortası Ürünleri — Tam Hayat','Tam hayat sigortası (whole life) ile vadeli hayat sigortası (term life) arasındaki fark nedir?','Aynıdır','Whole life: ölüm ne zaman olursa olsun ödeme + birikim. Term: n yıl içinde ölüm olursa ödeme, süre sonunda değer yok','Whole life daha ucuz','Term life kalıcı teminat','B','WL: prim daha yüksek; ömür boyu güvence + nakit değeri birikir. Term: prim düşük; geçici koruma, birikim yok.'),
  q('LEVEL_2','sigorta-matematigi','Hayat Sigortası Ürünleri — Tam Hayat','Whole life sigortasının nakit değeri (cash value) neden zamanla artar?','Prim yükselir','Rezerv birikimi: net primler hasarı aşan kısım rezerve eklenir, faizlenir ve sigortalının talebinde geri ödeme değerini oluşturur','Hasar azalır','Piyasa değeri','B','Nakit değer ≈ rezerv. Erken yıllarda düşük (başlangıç maliyetleri); zamanla birikim büyür. Sigortalı vazgeçme değeri.'),

  // ── Markov Zincirleri (Giriş) [LEVEL_2/sigorta-matematigi] ──
  q('LEVEL_2','sigorta-matematigi','Markov Zincirleri (Giriş)','Markov özelliği nedir?','Gelecek, geçmişin tamamına bağlı','Gelecek durum yalnızca mevcut duruma bağlı; geçmiş verilen mevcut koşullu bağımsız','Her durum eşit olasılıklı','Zamana göre değişmez','B','Markov: P(X_{n+1}=j|X_n=i, X_{n-1},...,X_0) = P(X_{n+1}=j|X_n=i). Basit ve güçlü bellek-sızlık özelliği.'),
  q('LEVEL_2','sigorta-matematigi','Markov Zincirleri (Giriş)','Geçiş matrisi P\'nin her satırının toplamı nedir ve neden?','0','1; her satır koşullu olasılık dağılımı (i\'den j\'ye tüm olası geçişlerin toplamı 1)','n','P\'ye bağlı','B','P_ij = P(X_{n+1}=j|X_n=i). Σⱼ Pᵢⱼ=1 (satır toplamı). Stokastik matris olarak tanımlanır.'),

  // ── Net Primler ve Özellikleri [LEVEL_3/hayat-sigortalari] ──
  q('LEVEL_3','hayat-sigortalari','Net Primler ve Özellikleri','Net primin "brüt primden" farkı nedir?','Aynıdır','Net prim: yalnızca saf risk maliyetini (aktuaryal eşitlik). Brüt prim: net prim + gider yükü + kâr payı','Net prim daha yüksek','Brüt prim rezervde kullanılır','B','Net (saf) prim: APV(faydalar)=APV(primler) denkliği. Brüt: gider, komisyon, kâr eklenmiş satış primi.'),
  q('LEVEL_3','hayat-sigortalari','Net Primler ve Özellikleri','Commutation functions (L, M, C, D tabloları) ne amaçla kullanılır?','Prim fiyatlandırması','Çok sayıda aktüeryal hesabı verimli yapmak için önceden hesaplanan hayat tablosu değerleri','Vergi hesabı','Reasürans','B','D_x=v^x·l_x, N_x=ΣD, M_x=ΣC, C_x=v^{x+1}·d_x. Anüite: ä_x=N_{x+1}/D_x. Sigorta: A_x=M_x/D_x.'),

  // ── Özyinelemeli Rezerv Hesabı [LEVEL_3/hayat-sigortalari] ──
  q('LEVEL_3','hayat-sigortalari','Özyinelemeli Rezerv Hesabı','Fackler birikme formülü (_kV+P)(1+i) = q_{x+k}·b + p_{x+k}·_{k+1}V nedir?','Prim tahsilat formülü','Dönem başı (rezerv+prim) faizle büyütülünce ölüm tazminatı + dönem sonu hayatta kalanların rezervini karşılamalı','Hasar frekansı hesabı','Geriye dönük rezerv','B','Fackler: aktüeryal denge. k\'dan k+1\'e rekürsiyon. Rezervleri ardışık hesaplamak için kullanılır.'),
  q('LEVEL_3','hayat-sigortalari','Özyinelemeli Rezerv Hesabı','Negatif rezerv (negative reserve) ne anlama gelir ve nasıl önlenir?','Her zaman normaldir','İlk yıllarda gider yükünün yüksek olması nedeniyle rezervin negatife düşmesi; CRVM ile önlenir','Rezerv mevzuata aykırı değil','Sigortalı lehine','B','Negatif reserve: CRVM (Commissioners Reserve Valuation Method) veya FPT ile önlenir. Çoğu düzenleyici negatif rezerve izin vermez.'),

  // ── Panjer Özyinelemesi [LEVEL_2/risk-analizi] ──
  q('LEVEL_2','risk-analizi','Panjer Özyinelemesi','Panjer özyinelemesi hangi dağılım sınıfına uygulanır?','Her dağılıma','(a,b,0) sınıfı: Poisson (a=0,b=λ), Binom (a=-p/(1-p), b=(n+1)p/(1-p)), Negatif Binom','Sadece Poisson','Yalnızca Normal','B','(a,b,0): p_n = (a+b/n)·p_{n-1}. Toplam hasar dağılımı konvolüsyon yerine özyinelemeyle hesaplanır.'),
  q('LEVEL_2','risk-analizi','Panjer Özyinelemesi','Panjer ile toplam hasar dağılımı S=X₁+...+X_N için f_S hesabı nasıl yapılır?','Monte Carlo simülasyonu','f_S(s) = (1/(1-a·f_X(0)))·Σ_{x=1}^s (a+bx/s)·f_X(x)·f_S(s-x) özyineleme ile','Doğrudan analitik','Tablo','B','Panjer algoritması: f_S(0) = P_N(f_X(0)). s=1,2,... için özyinelemeli hesap. Kesikli X için exact; sürekli X için discretize gerekli.'),

  // ── Sağlık Sigortası Temel Bilgileri [SEGEM_TPYS/mevzuat] ──
  q('SEGEM_TPYS','mevzuat','Sağlık Sigortası Temel Bilgileri','Türkiye\'de özel sağlık sigortasının SGK ile ilişkisi nedir?','Birbirinin yerine geçer','SGK zorunlu temel sağlık güvencesi; özel sigorta ek teminat veya daha hızlı/konforlu hizmet','SGK özel sigortayı kapsar','Birbirinden bağımsız ve çakışma yok','B','SGK: kamu zorunlu. Özel sağlık: tamamlayıcı (complementary) veya ek (supplementary). Katkı payı iadesi uygulaması da var.'),
  q('SEGEM_TPYS','mevzuat','Sağlık Sigortası Temel Bilgileri','Tamamlayıcı sağlık sigortası (TSS) nedir?','Hayat sigortası türü','SGK\'nın kapsadığı hizmetlerde sigortalının cebinden ödediği katılım payı ve fark ücretlerini karşılayan poliçe','Emeklilik ürünü','Yabancı uyruklu sigorta','B','TSS: SGK kapsamındaki tedavilerde ortaya çıkan hasta payını öder. 2015\'ten itibaren Türkiye\'de aktif şekilde sunuluyor.'),

  // ══════════════════════════════════════════════════════════════
  // 4 SORULU KONULAR → +1 soru ekle
  // ══════════════════════════════════════════════════════════════

  q('LEVEL_3','finans-yatirim','Aktüeryal Risk Yönetimi — Faiz Riski ve Garanti','Minimum garanti faizi (minimum guaranteed rate) hayat sigortacısında nasıl risk oluşturur?','Risk yok','Piyasa faizi garantinin altına düşerse yatırım getirileri yükümlülüğü karşılamaz; spread negatife döner','Sadece kısa vadede','Prim gelirini artırır','B','Garanti faiz: ürün tasarımında poliçe sahibine vaat edilen minimum kreditaj. Faiz düşerse spread riski: i_invest < i_guarantee.'),
  q('SEGEM_TPYS','mevzuat','Bireysel Emeklilik Sistemi (BES) Temelleri','BES\'de emekliliğe hak kazanmak için koşullar nelerdir?','10 yıl prim, 55 yaş','En az 10 yıl sistemde kalma ve 56 yaşını doldurma (2021 sonrası başlayanlar için 56)','15 yıl prim','Yalnızca yaş şartı','B','BES emeklilik: 10 yıl faaliyette + 56 yaş. Erken çıkışta devlet katkısı belirli oranda kesilir.'),
  q('LEVEL_2','finans-teorisi','Brownian Hareket ve Geometrik Brownian Hareket','Geometric Brownian Motion\'da S_T dağılımı nedir?','Normal','Log-normal: ln(S_T/S_0) ~ N((μ-σ²/2)T, σ²T)','Üstel','Poisson','B','GBM: dS=μS·dt+σS·dW. S_T = S_0·exp((μ-σ²/2)T + σW_T). S_T log-normal; ln(S_T) normal.'),
  q('LEVEL_2','muhasebe','Finansal Analiz ve Oran Analizi','Cari oran (current ratio) nedir ve nasıl yorumlanır?','Toplam aktif / Toplam borç','Dönen varlıklar / Kısa vadeli yabancı kaynaklar; 2:1 ideal, 1\'in altı likidite riski','Net kâr / Satışlar','Özkaynak / Aktif','B','Current ratio = CA/CL. >2: iyi likidite. <1: kısa vadeli borç ödemesinde risk. Sektöre göre değişir.'),
  q('LEVEL_3','finans-yatirim','Finansal Risk Yönetimi — Piyasa, Kredi, Likidite Riski','Likidite riski ile piyasa riski arasındaki fark nedir?','Aynıdır','Piyasa riski: fiyat dalgalanması. Likidite riski: varlığı zamanında ve adil fiyattan nakde çevirme güçlüğü','Likidite sadece bankada','Piyasa riski sadece hisse','B','Likidite riski: bid-ask spread genişlemesi, market depth azalması. Kriz döneminde piyasa+likidite riski birlikte artar.'),
  q('LEVEL_2','risk-analizi','Hasar Büyüklüğü Modelleri','Limited expected value (LEV) E[X∧u] nedir ve neden önemlidir?','E[X]','E[min(X,u)] = ∫_0^u S(x)dx; limiti u olan sigortanın beklenen ödemesini verir','Var[X]','P(X>u)','B','LEV: E[X∧u]=∫_0^u[1-F(x)]dx. Politika limiti u altında sigorta net prim hesabı için temel araç.'),
  q('LEVEL_2','sigorta-matematigi','Hayat Anüiteleri — Tam Hayat ve Süreli','n-yıllık süreli hayat anüitesi (temporary life annuity) ä_{x:n|} nasıl hesaplanır?','ä_x - ä_{x+n}','(1-A_{x:n|})/d veya N_{x+1}-N_{x+n+1})/D_x','n·v^n·_n·p_x','A_x/d','B','ä_{x:n|} = Σ_{k=0}^{n-1} v^k·_k·p_x = (N_{x+1}-N_{x+n+1})/D_x (kommütasyon). Veya (1-A_{x:n|})/d.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Sigortası Ürün Tasarımı','Variable Life sigortasında yatırım riski kime aittir?','Sigortacıya','Sigortalıya; poliçe değeri seçilen yatırım fonlarının performansına bağlı','Devlete','Reasüröre','B','Variable life: unit-linked. Sigortalı fon seçer; NAV değişir. Minimum ölüm tazminatı garantisi genellikle mevcuttur.'),
  q('LEVEL_3','hayatdisi-sigortalar','IBNR Rezervleri ve Koşu Üçgenleri','Gelişim üçgeni (development triangle) nedir?','Prim tahsilatı tablosu','Kazanım yılı × gelişim yılı matrisi; kümülatif hasarların nasıl büyüdüğünü gösterir','Hasar sıklığı','Tarife tablosu','B','Triangle: satır=accident year, sütun=development year. Köşegen: son değerlendirme. Chain-Ladder LDF bu üçgenden hesaplanır.'),
  q('LEVEL_1','olasilik','Koşullu Dağılımlar ve Koşullu Beklentiler','Koşullu beklenti E[Y|X=x] ne anlama gelir?','E[Y] ile aynı','X=x verildiğinde Y\'nin beklenen değeri; x\'e göre değişen bir fonksiyon','Var[Y|X]','P(Y=y|X=x)','B','E[Y|X=x] = ∫ y·f_{Y|X}(y|x)dy. İterate beklenti: E[Y] = E[E[Y|X]]. Koşullu dağılımın merkezi eğilimi.'),
  q('LEVEL_1','istatistik','Momentler ve Moment Üreten Fonksiyon','Moment üreten fonksiyon (MGF) M_X(t) = E[e^{tX}] neden kullanışlıdır?','Olasılık hesabı','k. moment E[Xᵏ] = M_X^{(k)}(0); kapalı form türevlemeyle momentler hızlıca bulunur','Varyans hesabı','Normal yaklaşım','B','M_X^{(k)}(0) = E[Xᵏ]. Ayrıca toplamların MGF\'si çarpım: M_{X+Y}(t)=M_X(t)·M_Y(t) (bağımsız X,Y için).'),
  q('LEVEL_2','muhasebe','Muhasebe Temelleri ve Bilanço','Çift taraflı kayıt (double-entry) sisteminin temel kuralı nedir?','Her işlem tek hesaba','Her finansal işlem en az iki hesabı etkiler; toplam borçlu = toplam alacaklı','Sadece nakit işlemleri','Gelir=gider','B','Çift taraflı: debit = credit. Varlık aldığında aktif borçlu, pasif alacaklı. Bilanço denkliği korunur.'),
  q('LEVEL_3','hayat-sigortalari','Net Prim Rezervleri — Retrospektif Yöntem','Retrospektif rezerv ile prospektif rezerv neden eşit olmalıdır?','Değiller','Aktüeryal denklik ilkesi gereği; geçmişte biriken prim fazlası = gelecekte ödenecek net yükümlülük','Sadece basit faizde','Faiz oranı sıfır ise','B','Eşitlik: retrospektif = prospektif. Her ikisi de aynı varsayımlar (faiz, mortalite) kullanılırsa net prim dengesini yansıtır.'),
  q('LEVEL_1','istatistik','Normal Dağılım','N(μ,σ²) normal dağılımında z-skoru nedir ve nasıl kullanılır?','z=(X+μ)/σ','z=(X−μ)/σ; standart normal N(0,1)\'e dönüştürme; tabloda olasılık okuma','z=μ/σ','z=X·σ','B','z=(X-μ)/σ. P(X≤x)=P(Z≤z)=Φ(z). z-tablosu veya standart normal CDF kullanılır.'),
  q('LEVEL_2','risk-analizi','Normal Power Yaklaşımı','Normal Power (NP) yaklaşımı nedir?','Normal dağılım yaklaşımı','Skewness (çarpıklık) düzeltmesi ekleyerek non-normal toplam hasar dağılımını daha iyi yaklaşan yöntem','Parametrik MLT','Monte Carlo','B','NP: x_p = μ + σ·(z_p + (γ₁/6)·(z_p²-1)). γ₁: çarpıklık. Normal\'den daha iyi; özellikle %99+ yüzdelikler için.'),
  q('LEVEL_1','matematik','Özdeğer ve Özvektörler','Özdeğer (eigenvalue) nedir?','Matrisin determinantı','Av = λv denklemini sağlayan λ skaleri; v: özvektör, A: kare matris','Matrisin izi','Matrisin sütun sayısı','B','Özdeğer: det(A-λI)=0 karakteristik denklemi. n×n matrisin n özdeğeri (tekrar sayısıyla birlikte). Kovaryans matrisinde ana bileşen analizi için kullanılır.'),
  q('LEVEL_2','muhasebe','Sermaye Yeterliliği — Solvency I','Solvency I hayat dışı sigortacısı için asgari sermaye nasıl hesaplanır?','SCR formülü','max(prim bazlı limit, hasar bazlı limit): prim × %18 veya hasar × %26','Sadece teknik karşılık','Risk değerlendirmesi','B','Solvency I: max(18%·primler, 26%·ortalama hasar). Basit, risk duyarsız. AB\'de Solvency II ile değiştirildi.'),
  q('LEVEL_2','muhasebe','Sigorta Muhasebesi — Üretim Muhasebesi','Sigorta üretim muhasebesi (yazılan primler kaydı) nasıl yapılır?','Nakit alındığında','Poliçe imzalandığında yazılan prim + alacak; henüz kazanılmamış kısım KPK hesabında ertelenir','Dönem sonunda','Hasar ödenince','B','Prim kayıt: YP (written premium) → brüt tahakkuk. KPK (unearned premium reserve) → pasif. Kazanılmış prim = YP − ΔKPK.'),
  q('LEVEL_2','muhasebe','Sigorta Şirketleri Muhasebesi','Reasürans devri (cession) muhasebede nasıl gösterilir?','Sigorta şirketi geliri','Reasüröre devredilen prim gider; karşılığında alacak olarak reasürans hasar payı aktifleştirilir','Sermaye azalışı','Nazım hesap','B','Reasürans muhasebe: devir prim → gider (veya yazılan primden düşüm). Reasürans hasar alacağı → aktif. Net=brüt-devirler.'),
  q('LEVEL_3','hayat-sigortalari','Solvency II — Hayat','Solvency II\'de hayat sigortacısı için teknik karşılık hesabında kullanılan risk-free faiz eğrisi nereden alınır?','Hazine tahvil getirileri','EIOPA tarafından yayımlanan risk-free faiz oranı term structure (ile VA veya MA eklenerek)','Merkez bankası politika faizi','Şirket belirlediği faiz','B','EIOPA risk-free: swap faizleri − kredi riski düzeltmesi. Likidite primi (VA/MA) şirket koşullarına göre eklenir.'),
  q('LEVEL_3','hayatdisi-sigortalar','Solvency II — Hayat Dışı','Solvency II\'de non-life UW risk SCR hesabı için hangi iki alt modül kombinlenir?','Prim ve hasar','Prim ve rezerv riski + katastrofik risk; korelasyon matrisiyle birleştirilir','Sadece prim riski','Sadece cat risk','B','SCR_nl_UW = sqrt(SCR_pr² + 2·ρ·SCR_pr·SCR_cat + SCR_cat²). ρ=0 (standart formülde bağımsız).'),
  q('LEVEL_3','finans-yatirim','Solvency II — Risk Marjı','Solvency II\'de Risk Marjı (Risk Margin) nedir ve nasıl hesaplanır?','Güvenlik yükü','Sigorta yükümlülüklerinin başka bir şirkete devredilmesi için gereken ek tazminat; CoC yöntemi: CoCr·Σ SCR_t·v^t','Aktüeryal rezerv farkı','Yönetim kâr payı','B','Risk Margin = CoCr × PV(gelecek SCR). CoCr: %6 (Solvency II standart). BEL + RM = teknik karşılık.'),
  q('SEGEM_TPYS','mevzuat','Sorumluluk ve Kaza Sigortaları','Zorunlu trafik sigortasının amacı nedir?','Araç hasarını ödemek','Trafik kazasında üçüncü kişilere verilen bedensel ve maddi zararları güvence altına almak','Sürücünün kendi hasarını karşılamak','Aracın çalınmasını','B','Zorunlu trafik (ZMSS): üçüncü kişi sorumluluğu. Maddi + bedensel hasar güvencesi. Poliçesiz araç trafiğe çıkamaz.'),
  q('LEVEL_3','hayat-sigortalari','Stokastik Hayat Modelleri','Cohort (jenerasyon) mortalite tablosu vs. period (dönem) tablosu farkı nedir?','Aynıdır','Period: tek bir yılın yaşa göre mortalitesi (statik kesit). Cohort: doğum yılı izlenerek gerçek hayat deneyimi (dinamik)','Cohort daha eski','Period projeksiyon içerir','B','Period table: sabit yıl kesiti (q_x 2020 için). Cohort/generation table: 1960 doğumlular 50 yıl izlenir. Projeksiyon mortalite iyileşmesini yakalar.'),
  q('LEVEL_3','hayatdisi-sigortalar','Tarife Belirleme (Ratemaking)','Offbalance (dengesiz) tarife neden tehlikelidir?','Fazla prim geliri','Bazı riskler priminin altında, bazıları üstünde tarife edildiğinde adverse selection çeker; kazançlı riskler gider, kötü riskler kalır','Regülasyon sorunu','Acenteleri zorlar','B','Offbalance: ortalama prim doğru ama segmentasyon yanlış → cherry-picking by competitors. Rakipler iyi riskleri alır; şirket kötü risklerle kalır.'),

];

async function upload(batch) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/question_bank`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': SERVICE_KEY,
      'Authorization': `Bearer ${SERVICE_KEY}`,
      'Prefer': 'return=minimal',
    },
    body: JSON.stringify(batch),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`HTTP ${res.status}: ${text}`);
  }
}

async function main() {
  console.log(`Toplam soru: ${questions.length}`);
  const BATCH = 20;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await upload(batch);
    console.log(`✓ ${Math.min(i + BATCH, questions.length)}/${questions.length}`);
  }
  console.log('✅ Tamamlandı!');
}

main().catch(e => { console.error(e); process.exit(1); });
