#!/usr/bin/env node
const SUPABASE_URL = 'https://vxnohqhaomaleftnlpyl.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bm9ocWhhb21hbGVmdG5scHlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDk5MTExNywiZXhwIjoyMDkwNTY3MTE3fQ.H8I4h1Ogu2s3aKc7FX3CTpprZktAUmoxGFSCRqzYAeY';

const q = (exam_type, subject, topic, question_text, A, B, C, D, correct_answer, explanation) => ({
  exam_type, subject, topic, question_text,
  options_json: { A, B, C, D }, correct_answer, explanation, is_active: true,
});

const questions = [

  // ─── EMEKLİLİK ────────────────────────────────────────────────────────────

  // BES Matematik
  q('LEVEL_3','emeklilik','BES Matematik','Bireysel Emeklilik Sistemi\'nde (BES) devlet katkısı nasıl hesaplanır?','Aylık katkının %25\'i devlet tarafından eklenir','Katılımcı katkısının %30\'u devlet katkısı olarak eklenir (2024 itibarıyla)','Yıllık toplam katkının %10\'u','Sabit 1000 TL/ay','B','Türkiye BES: devlet katkısı = katılımcı katkısının %30\'u (son değişikliklerle). Asgari ücretle sınırlandırılmış.'),
  q('LEVEL_3','emeklilik','BES Matematik','Emeklilik fon birikiminin aktüeryal bugünkü değerini hesaplamak için kullanılan temel iskonto faktörü nedir?','Teknik faiz oranı ve hayatta kalma olasılıklarını içeren v^t·_t·p_x','Sadece teknik faiz oranı','Enflasyon oranı','Nominal faiz oranı','A','BES birikimi: PV=Σ katkı_t·v^t·_t·p_x. Hem faiz hem mortalite etkisi. Katkı ödeme süresi ve emeklilik yaşı kritik.'),
  q('LEVEL_3','emeklilik','BES Matematik','Defined Contribution (DC) planında yatırım riski kime aittir?','Şirkete','Çalışana (katılımcı)','Devlete','Emeklilik şirketine','B','DC: katkı belirli, birikim yatırım performansına bağlı. Yatırım riski çalışanda. DB\'de ise işverende.'),
  q('LEVEL_3','emeklilik','BES Matematik','Yaşam boyu gelir (life annuity) seçeneğinde emekli maaşı nasıl hesaplanır?','Birikim / beklenen ömür','Birikim / ä_x (emeklilik yaşı anüite faktörü)','Birikim × faiz oranı','Sabit prim yöntemi','B','Maaş = Birikim / ä_x. ä_x teknik faiz ve hayat tablosuna göre. Kadın için daha uzun ömür → düşük maaş.'),
  q('LEVEL_3','emeklilik','BES Matematik','BES\'de vade sonu yüzde getiri hedefi hangi aktüeryal kavramı ifade eder?','Brüt yatırım getirisi','Net teknik faiz (yatırım getirisi − yönetim ücreti)','Faiz oranı paritesi','Enflasyona karşı reel getiri','B','Net teknik faiz: portföy getirisi − fon işletim gideri (yönetim ücreti). Aktüeryal projeksiyonlarda kullanılan.'),

  // Emeklilik Fon Yönetimi
  q('LEVEL_3','emeklilik','Emeklilik Fon Yönetimi','Tanımlı Fayda (Defined Benefit — DB) emeklilik planında aktüeryal açık (actuarial deficit) nedir?','Prim fazlası','Plan varlıkları < Plan yükümlülükleri; aktüeryal hesaplamalara göre yetersiz birikim','Yatırım geliri','Devlet katkı açığı','B','Actuarial deficit = PV(faydalar) - Plan varlıkları. Pozitifse işveren ek katkı yapmak zorunda.'),
  q('LEVEL_3','emeklilik','Emeklilik Fon Yönetimi','Entry Age Normal (EAN) katkı metodu nedir?','Her yıl sabit prim','İşe girişten itibaren fayda projeksiyonu yapılır; sabit katkı oranı belirlenir; normal maliyet düzlenir','Geçmiş hizmet bazlı','Sadece son 5 yıl','B','EAN: normal cost = PV(projected benefit at retirement)×entry age level premium. Düz katkı profili.'),
  q('LEVEL_3','emeklilik','Emeklilik Fon Yönetimi','Liabiliy-Driven Investing (LDI) stratejisi nedir?','Maksimum getiri odaklı','Portföyü plan yükümlülüklerinin faiz/duration riskini hedge edecek şekilde yapılandırmak','Yalnızca hisse senedi yatırımı','Nakit odaklı strateji','B','LDI: varlık durasyonu = yükümlülük durasyonu. Faiz riski minimize. Uzun vadeli tahvil + swap kullanımı.'),
  q('LEVEL_3','emeklilik','Emeklilik Fon Yönetimi','Ömür boyu maaş garantisi (longevity risk) emeklilik fonunu nasıl etkiler?','Birikim hızlanır','Ortalama yaşam süresinden uzun yaşayanlar için fondan beklenden fazla çekim; fon tükenir','Fon riski azalır','Devlet garantisi devreye girer','B','Longevity risk: katılımcı beklenenden uzun yaşarsa fon bitirir. DB planında işveren; DC\'de katılımcı riskini taşır.'),
  q('LEVEL_3','emeklilik','Emeklilik Fon Yönetimi','Actuarial Assumptions Set değişikliği (örn. mortalite güncellemesi) DB planına etkisi nedir?','Etki yok','Yükümlülük yeniden hesaplanır; genellikle öngörülen yaşam uzamasıyla PV(faydalar) artar, açık büyür','Sadece prim etkiler','Varlık değeri değişir','B','Mortalite iyileştirmesi → daha uzun emekli maaşı → yükümlülük artar → aktüeryal açık büyür → işveren katkısı artmalı.'),

  // Sosyal Güvenlik Aktüerliği
  q('LEVEL_3','emeklilik','Sosyal Güvenlik Aktüerliği','Sosyal Güvenlik sisteminin PAYG (pay-as-you-go) finansman modeli nedir?','Bireysel hesap sistemine dayalı','Mevcut çalışanların prim ödemeleri o anki emeklilere aktarılır; birikim yoktur','Sermaye piyasasına dayalı','Özel sigorta mantığıyla işler','B','PAYG: nesiller arası dayanışma. Demografik dönüşüm (yaşlanan nüfus) sistemin sürdürülebilirliğini tehdit eder.'),
  q('LEVEL_3','emeklilik','Sosyal Güvenlik Aktüerliği','SGK\'nın uzun vadeli aktüeryal denge analizi için gerekli demografik göstergeler nelerden oluşur?','Sadece ölüm oranları','Doğurganlık oranı, mortalite projeksiyonu, göç ve işgücüne katılım oranı','Sadece prim gelirleri','Sadece enflasyon','B','Sosyal güvenlik projeksiyon: nüfus + işgücü + mortalite + doğurganlık + göç. Emekli/Aktif çalışan oranı kritik.'),
  q('LEVEL_3','emeklilik','Sosyal Güvenlik Aktüerliği','SGK\'da prim açığı (contribution gap) nedir?','Primin yeterli olmadığı durum','Prim gelirleri − emeklilik giderleri; negatifse devlet bütçesinden transfer gerekir','Prim fazlası rezervi','Fon yatırım geliri','B','Prim açığı = prim gelirleri - (emekli maaşı + sağlık giderleri + idare). Açık büyüyünce fiskale baskı artar.'),
  q('LEVEL_3','emeklilik','Sosyal Güvenlik Aktüerliği','NDC (Notional Defined Contribution) sistemi nasıl çalışır?','Gerçek fon birikimine dayalı','Her çalışana sanal hesap; prim kayıtlanır, hesaplama DC gibi; ödeme PAYG ile yapılır','DB planının bir türü','Yalnızca Türkiye\'de uygulanan','B','NDC: İsveç modeli. Sanal hesap: prim + notional interest (ücret artışı). Emeklilik: hayat tablosu ve yaşa göre annuity.'),
  q('LEVEL_3','emeklilik','Sosyal Güvenlik Aktüerliği','Emeklilik yaşının artırılması sosyal güvenlik sistemine aktüeryal etkisi nedir?','Prim gelirleri azalır','Ödeme süresi kısalır, daha az emekli maaşı ödenir; daha uzun prim süresi; sistem maliyeti düşer','Etkisi yoktur','Sadece kısa vadeli fayda','B','Emeklilik yaşı ↑: daha az emekli (yükümlülük ↓) + daha fazla prim ödeyen (gelir ↑). Aktüeryal denge iyileşir.'),

  // ─── FİNANS VE YATIRIM ───────────────────────────────────────────────────

  // İleri Türev Araçlar
  q('LEVEL_3','finans-yatirim','İleri Türev Araçlar','Varyans swap\'ı (variance swap) nedir?','Faiz oranı takası','Gerçekleşen varyans ile üzerinde anlaşılan sabit varyans arasındaki farkın ödeneceği forward kontratı','Döviz takası','Metaemtia swap','B','Var swap: payoff = N·(σ²_realized − K_var). Volatilite ticareti için saf araç; gamma/vega riski yok.'),
  q('LEVEL_3','finans-yatirim','İleri Türev Araçlar','Compound option (bileşik opsiyon) nedir?','Birden fazla standardı içeren opsiyon','Opsiyonun opsiyonu; call-on-call, put-on-call gibi. Gebers fiyatlama modeli.','Çift para birimli opsiyon','Egzotik olmayan standart opsiyon','B','Bileşik opsiyon: Gebers (1979). Call on call: 1. son tarihe kadar alım opsiyonu satın alma hakkı.'),
  q('LEVEL_3','finans-yatirim','İleri Türev Araçlar','CDS (Credit Default Swap) nedir ve koruma alıcısı ne öder?','Faiz oranı değişimi için','Referans kuruluşun temerrüdüne karşı sigorta: alıcı periyodik spread öder; temerrütte koruma satıcısı kayıp öder','Hisse senedi türevi','Emtia vadeli işlemi','B','CDS: kredi riski transferi. Spread = yıllık prim (baz puan). Temerrütte: yüz × (1-recovery rate) ödenir.'),
  q('LEVEL_3','finans-yatirim','İleri Türev Araçlar','Swaption nedir?','Swap bitiş seçeneği','Belirlenen bir vadede belirlenmiş koşullarda faiz swapına girme hakkı veren opsiyon','Çoklu döviz swapı','Hisse swapı','B','Swaption: payer swaption = sabit ödeyen olmak hakkı. Receiver swaption = sabit alan olmak hakkı. Black modeli ile değerleme.'),
  q('LEVEL_3','finans-yatirim','İleri Türev Araçlar','Delta-Gamma hedging neden Delta-only hedging\'e göre üstündür?','Daha ucuz','Delta ikinci dereceden fiyat değişimlerini yakalayamaz; Gamma büyük fiyat hareketlerinde residual riski azaltır','Daha az işlem gerektirir','Gamma her zaman sıfırdır','B','Delta hedge: ∂C/∂S korunur. Gamma: ∂²C/∂S². Büyük S hareketinde Gamma önemli. Γ-nötr + Δ-nötr ideal.'),

  // Risk Yönetimi — ERM
  q('LEVEL_3','finans-yatirim','Risk Yönetimi — ERM','Enterprise Risk Management (ERM) geleneksel risk yönetiminden nasıl ayrılır?','Sadece finansal risklere odaklanır','Tüm risk kategorilerini (finansal, operasyonel, stratejik, itibar) entegre ve bütünsel yaklaşımla yönetir','Yalnızca sigorta şirketlerine uygulanır','Risk transferini dışlar','B','ERM: COSO çerçevesi. Siloları kırarak tüm organizasyonda risk kültürü. Portföy yaklaşımıyla diversifikasyon.'),
  q('LEVEL_3','finans-yatirim','Risk Yönetimi — ERM','ORSA (Own Risk and Solvency Assessment) nedir?','Dış derecelendirme belgesi','Sigorta şirketinin kendi risk ve sermaye yeterliliğini değerlendirdiği iç süreç; Solvency II gereksinimi','Zorunlu stres testi raporu','Muhasebe denetim raporu','B','ORSA: Madde 45 Solvency II. Şirket kendi perspektifinden risk profili, SCR ve uzun vadeli ödeme gücünü değerlendirir.'),
  q('LEVEL_3','finans-yatirim','Risk Yönetimi — ERM','Operasyonel risk Solvency II Standard Formula\'da nasıl hesaplanır?','Prim × 0.3','Prim hacmine ve rezerve uygulanan faktörler; max(prim bazlı, rezerv bazlı) çerçevesi','Markov zinciri','İç model gereklidir','B','SCR_op = min(0.30·BSCR, %3·prim veya 0.3·rezerv). Standart formül basit; iç model daha hassas.'),
  q('LEVEL_3','finans-yatirim','Risk Yönetimi — ERM','Risk iştahı (risk appetite) ve risk toleransı (risk tolerance) farkı nedir?','Aynı kavramlardır','Risk iştahı strateji düzeyinde alınmak istenen risk miktarı; tolerans kabul edilebilir sapma limiti','Risk iştahı daha dar','Tolerans daha geniş','B','Risk appetite: "ne kadar risk almak istiyoruz?" Risk tolerance: "ne kadar sapmaya katlanabiliriz?" İkincisi birincinin alt limitidir.'),
  q('LEVEL_3','finans-yatirim','Risk Yönetimi — ERM','Stres testi ve senaryo analizi ERM\'de nasıl kullanılır?','Sadece tarihi verilere dayanır','Uç senaryolarda sermaye yeterliliğini test eder; kötü durum planlamasını bilgilendirir','Yalnızca piyasa riski için','Zorunlu değildir','B','Stress test: tek faktör şoku (örn. faiz +200bp). Senaryo: çok faktörlü (2008 krizi benzeri). SCR gereksinimi belirler.'),

  // Sermaye Yeterliliği
  q('LEVEL_3','finans-yatirim','Sermaye Yeterliliği','Solvency II\'de SCR (Solvency Capital Requirement) nedir?','Minimum faaliyete izin verilen sermaye','%99.5 VaR ile ölçülen 1 yıllık şok senaryosunda yeterli olması gereken ekonomik sermaye','Teknik karşılık','Muhasebe sermayesi','B','SCR = Economic capital @ 99.5% one-year VaR. Yeterli olunmazsa düzenleyici müdahale. MCR daha alt sınır.'),
  q('LEVEL_3','finans-yatirim','Sermaye Yeterliliği','MCR (Minimum Capital Requirement) ve SCR ilişkisi nedir?','MCR > SCR her zaman','MCR < SCR; MCR altına düşünce lisans iptali; SCR altında uyarı/plan','İkisi eşittir','MCR yalnızca hayat sigortasına uygulanır','B','MCR: mutlak alt sınır (SCR\'nin %25-45\'i). MCR<Özkaynak<SCR → kurtarma planı. Özkaynak<MCR → lisans iptali.'),
  q('LEVEL_3','finans-yatirim','Sermaye Yeterliliği','RAROC (Risk-Adjusted Return on Capital) formülü nedir?','Net kâr / Toplam varlık','(Net gelir − Beklenen kayıp) / Ekonomik sermaye','Net prim / Rezerv','Teknik kâr / Prim','B','RAROC = (Gelir - Beklenen kayıp) / EC. EC: %99.9 VaR gibi. Performans ölçütü ve sermaye dağıtımında kullanılır.'),
  q('LEVEL_3','finans-yatirim','Sermaye Yeterliliği','İç model Solvency II\'de standart formüle göre ne avantaj sağlar?','Daha az raporlama','Şirketin gerçek risk profiline uygun SCR; standart formülün konservatifliğinden kurtulma','Daha düşük teknik karşılık','Otomatik onay','B','Internal model: EIOPA onaylı. Şirkete özgü korelasyon, dağılım. Genellikle SCR azaltır; uygulama maliyeti yüksek.'),
  q('LEVEL_3','finans-yatirim','Sermaye Yeterliliği','Basel III/IV çerçevesi sigortacılık sermaye yeterliliğiyle nasıl ilişkilidir?','Aynı kurallar geçerli','Bankacılığa yönelik; IAIS ICS sigortacılar için. Sistemik risk bağlamında benzer kavramlar (tier 1/2 sermaye) kullanılır','Sigortacıya uygulanmaz','Sigortacılar Basel\'e tabidir','B','Bankacılık: Basel (BIS). Sigortacılık: Solvency II (AB), ICS (IAIS küresel). Kavramsal benzerlik; ayrı çerçeveler.'),

  // ─── HAYAT SİGORTALARI ───────────────────────────────────────────────────

  // Asset-Liability Management
  q('LEVEL_3','hayat-sigortalari','Asset-Liability Management','ALM\'de duration matching neden önemlidir?','Yatırım getirisini maksimize etmek','Varlık ve yükümlülük durasyon farkını (duration gap) sıfıra yaklaştırarak faiz riski yönetimi','Prim maliyetini azaltmak','Vergi optimizasyonu','B','Duration gap = D_A - (L/A)·D_L. Gap=0: faiz şoklarında ekonomik net değer değişmez. Bağışıklık stratejisi.'),
  q('LEVEL_3','hayat-sigortalari','Asset-Liability Management','Convexity (dışbükeylik) ALM\'de neden önemlidir?','Kredi riskini ölçer','İkinci dereceden faiz duyarlılığı; büyük faiz hareketlerinde duration approximation\'ı düzeltir','Likidite ölçütü','Sadece sabit getirili varlıklar için','B','Fiyat ≈ -D·Δy + ½C·Δy². Convexity etkisi: faiz düşerken varlık değeri daha fazla artar, düzeltme gerekir.'),
  q('LEVEL_3','hayat-sigortalari','Asset-Liability Management','Hayat sigortacısı için likidite riski nasıl ortaya çıkar?','Yatırım getirisi düşer','Beklenmedik erken vazgeçmeler (surrender) ve ölüm tazminatlarının nakit ihtiyacı uzun vadeli varlıkları elden çıkarmayı zorlayabilir','Prim gelirleri azalır','Reasürans maliyeti artar','B','Likidite riski: acil nakit için uzun vadeli tahviller piyasa değerinden (zararla) satılmak zorunda kalınabilir.'),
  q('LEVEL_3','hayat-sigortalari','Asset-Liability Management','Solvency II\'de Best Estimate Liability (BEL) nedir?','Tarihi maliyet esaslı rezerv','Gelecek nakit akışlarının risk-nötr iskonto eğrisiyle iskonto edilmiş bugünkü değeri','Brüt teknik karşılık','Net prim karşılığı','B','BEL: olasılık ağırlıklı nakit akışları (prim, hasar, gider) × risk-free iskonto. + Risk Adjustment = TP.'),
  q('LEVEL_3','hayat-sigortalari','Asset-Liability Management','ALM\'de immunization (bağışıklık) stratejisinin iki koşulu nedir?','D_A > D_L ve C_A > C_L','D_A = D_L ve C_A ≥ C_L','D_A < D_L','Sadece D_A = D_L','B','Klasik bağışıklık: (1) PV(A)=PV(L), (2) D_A=D_L, (3) C_A≥C_L (Redington koşulları). Faiz şoklarına karşı koruma.'),

  // Embedded Value
  q('LEVEL_3','hayat-sigortalari','Embedded Value','Embedded Value (EV) hayat sigortasında nedir?','Muhasebe defter değeri','Adjusted Net Worth + Present Value of In-Force Business (PVIF); ekonomik değer ölçütü','Prim geliri toplamı','Teknik karşılık','B','EV = ANW + PVIF. ANW: serbest sermaye. PVIF: mevcut portföyden beklenen gelecek kâr PV. Ekonomik değer.'),
  q('LEVEL_3','hayat-sigortalari','Embedded Value','MCEV (Market-Consistent Embedded Value) klasik EV\'den farkı nedir?','Daha basit hesaplama','Piyasa tutarlı (risk-nötr) değerleme kullanır; opsiyonlar ve garantiler (O&G) için piyasa fiyatı kullanılır','Sadece Almanya\'da uygulanan','Muhasebe bazlı','B','MCEV: O&G değeri açıkça ölçülür. Risk-nötr senaryolar. CFO Forum MCEV prensipleri (2009).'),
  q('LEVEL_3','hayat-sigortalari','Embedded Value','VNB (Value of New Business) nedir?','Geçmiş portföy değeri','Yeni yazılan işten beklenen kâr; prim eşdeğer primle (EP) normalize edilir','Yönetim gideri','Rezerv artışı','B','VNB = PV(yeni iş kâr akışları) değerleme andaki varsayımlarla. EV artışının yeni iş katkısı.'),
  q('LEVEL_3','hayat-sigortalari','Embedded Value','EV Analysis of Movement (AoM) neyi açıklar?','Sadece faiz değişimini','Dönem başı EV\'den dönem sonu EV\'ye geçişi açıklayan kalemler: VNB, expected return, assumption changes, experience variances','Yalnızca mortalite etkisini','Teknik karşılık değişimini','B','AoM: EV₁ = EV₀ + VNB + Expected return + Δassumptions + Experience variances + Other. Yönetim için kârlılık analizi.'),
  q('LEVEL_3','hayat-sigortalari','Embedded Value','Frictional cost (sürtünme maliyeti) EV hesabında ne anlama gelir?','Satış komisyonu','Şirket içinde tutulan (serbest olmayan) sermayenin alternatif yatırım maliyetinden daha az getiri sağlaması','Operasyonel gider','Vergi maliyeti','B','Frictional cost: required capital getirisi < risk-free rate. Serbest olmayan sermayenin fırsat maliyeti. ANW\'yi azaltır.'),

  // Hayat Sigortası Ürün Tasarımı
  q('LEVEL_3','hayat-sigortalari','Hayat Sigortası Ürün Tasarımı','Universal Life (UL) poliçesinde esneklik nasıl sağlanır?','Sabit prim, sabit teminat','Katılımcı prim miktarını ve ödeme zamanını değiştirebilir; hesap değeri yatırım getirisiyle büyür','Sadece ölüm teminatı','DB planı gibi','B','UL: esnek prim, esnek teminat. Hesap değeri = birikmiş prim + faiz − COI − giderler. Düşen ödeme riski.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Sigortası Ürün Tasarımı','Participating (katılımlı) hayat sigortasında prim fazlası nasıl geri verilir?','Nakit iade yok','Aktüeryal fazlalar sigortalıya kâr payı (dividend) olarak dağıtılır','Vergi indirimi','Ek teminat olarak otomatik','B','Par life: beklenen kötümser varsayımlar > gerçekleşen → kâr. Kâr payı: nakit, prim indirimi, ek teminat, birikimli seçenekler.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Sigortası Ürün Tasarımı','Kritik hastalık (CI) ürününde "dread disease" trigger nedir?','Hastanede yatış','Belirtilen kritik hastalıklardan (kanser, MI, inme vb.) birinin tanısı konulması','Engellilik oranı','Ölüm','B','CI: tanı anında toplu ödeme. Hayatta kalma koşulu genellikle 30 gün. Sigorta altındaki hastalıklar tanımı kritik.'),
  q('LEVEL_3','hayat-sigortalari','Hayat Sigortası Ürün Tasarımı','Long-Term Care (LTC) sigortasının temel aktüeryal güçlüğü nedir?','Prim fiyatlaması kolay','Uzun vadeli mortalite ve morbidite (bakım ihtiyaç süresi) projeksiyonunun belirsizliği; erken kapanan sektör deneyimi','Devlet sübvansiyonu','Reasüransı kolay','B','LTC güçlük: uzun gecikme (50s\'de satın al, 80s\'de kullan), morbidity trend bilinmiyor, deneyim yetersiz, rezerv riski büyük.'),

  // Solvency II — Hayat
  q('LEVEL_3','hayat-sigortalari','Solvency II — Hayat','Hayat sigortacısında SCR Life alt modülü hangi riskleri kapsar?','Piyasa riski','Mortalite, uzun ömür, maluliyet, lapses, gider, revizyon ve katastrofik hayat riskleri','Kredi riski','Operasyonel risk','B','SCR_life: mortality, longevity, disability/morbidity, lapse, expense, revision, CAT. Agregasyonda korelasyon.'),
  q('LEVEL_3','hayat-sigortalari','Solvency II — Hayat','Uzun ömür riski (longevity risk) SCR hesabında nasıl stres uygulanır?','Mortalite %15 artar','Mortalite oranları %20 azaltılarak hesaplanan BEL artışı longevity risk SCR\'sini verir','Prim 2 kat artar','Rezerv %10 artar','B','Longevity stress: q_{x+t} × 0.80 (20% azalma). Daha uzun yaşayan → daha çok maaş → yükümlülük artar. SCR = ΔBEL.'),
  q('LEVEL_3','hayat-sigortalari','Solvency II — Hayat','Lapse risk SCR nasıl hesaplanır?','Sabit %5','Toplu iptal (mass lapse) ve sürekli iptal senaryolarının en kötüsü seçilir; BEL değişimi SCR','Prim kaybı','Gider artışı','B','Lapse SCR: stres (up lapse: %50 artış; down lapse: %50 azalış; mass lapse: %40 anında). En büyük BEL artışı kullanılır.'),
  q('LEVEL_3','hayat-sigortalari','Solvency II — Hayat','Volatility adjustment (VA) ve matching adjustment (MA) nedir?','Vergi düzeltmeleri','Uzun vadeli yatırımcı için yapay spread dalgalanmasını azaltmak amacıyla iskonto eğrisine eklenen spread düzeltmeleri','Mortalite düzeltmesi','Operasyonel risk düzeltmesi','B','VA: kısa vadeli spread dalgalanmasına karşı. MA: birebir eşleştirilmiş portföy için daha yüksek iskonto. İkisi BEL\'i düşürür.'),

  // ─── HAYAT DIŞI SİGORTALAR ───────────────────────────────────────────────

  // Hasar Rezervleri
  q('LEVEL_3','hayatdisi-sigortalar','Hasar Rezervleri','Gross vs. Net hasar rezervi farkı nedir?','Brüt prim ve net prim farkı','Gross: reasürans öncesi; Net: reasürans sonrası. Gross-Net farkı reasürans alacağını verir','Tarihi maliyet farkı','Sadece hayat dışında kullanılır','B','Gross reserve = sigortacının toplam yükümlülüğü. Net reserve = gross − reasürans payı. Bilanço ikisini birden gösterir.'),
  q('LEVEL_3','hayatdisi-sigortalar','Hasar Rezervleri','IBNER (Incurred But Not Enough Reserved) nedir?','Ihbar edilmemiş hasarlar','Raporlanmış ama yeterince provizyon ayrılmamış hasarlar; ilerleyen süreçte artacak hasarlar','Reddedilen talepler','Reasürans alacağı','B','IBNER: case reserve\'ler eksik ayrılmış. Gelişim faktörleri (LDF>1) bu etkiyi yakalar. IBNR+IBNER=toplam gelişim.'),
  q('LEVEL_3','hayatdisi-sigortalar','Hasar Rezervleri','Tail factor (kuyruk faktörü) ne için kullanılır?','İlk kazanım yılı','Chain-Ladder üçgeninin son gelişim sütunundan nihailiğe kadar olan gelişimi tahmin eder','Brüt/net düzeltme','Enflasyon düzeltmesi','B','Tail factor: son gözlemlenen sütundan ultimate\'e. Genellikle uzman görüşü veya ekstrapole eğri. Long-tail branşlarda kritik.'),
  q('LEVEL_3','hayatdisi-sigortalar','Hasar Rezervleri','Reserve adequacy (provizyon yeterliliği) değerlendirmesi için hangi göstergeler kullanılır?','Sadece rezerv/prim oranı','Prior year development, development year ratios, diagnostic triangles, paid-to-incurred ratio','Sadece hasar oranı','Muhasebe kârı','B','Yeterlilik testleri: önceki yıl gelişimi (pozitif = aşırı; negatif = yetersiz), açılma/kapanma analizi, PFAD.'),
  q('LEVEL_3','hayatdisi-sigortalar','Hasar Rezervleri','Solvency II\'de teknik karşılık (TP) hayat dışı için nasıl hesaplanır?','Chain-Ladder yeterli','BEL (risk-free iskontolu nakit akış tahmini) + Risk Adjustment; IBNR+RBNS+premiums reserve toplamı','Sadece IBNR','Tarihi maliyet','B','TP = BEL + RA. BEL: prim ve hasar akışları risk-free eğriyle iskonto. RA: finansal olmayan risk için tazminat.'),

  // Katastrofik Risk Modelleri
  q('LEVEL_3','hayatdisi-sigortalar','Katastrofik Risk Modelleri','Probabilistic catastrophe model kaç katmandan oluşur?','2','4: tehlike (hazard), maruziyet (exposure), hasar (vulnerability), finansal','3','1','B','Cat model: (1) Hazard: frekans/şiddet dağılımı, (2) Exposure: konum/inşaat, (3) Vulnerability: hasar oranı, (4) Financial: sigorta koşulları.'),
  q('LEVEL_3','hayatdisi-sigortalar','Katastrofik Risk Modelleri','PML (Probable Maximum Loss) ve OEP (Occurrence Exceedance Probability) farkı nedir?','Aynı kavramdır','PML: tek olaydan maksimum kayıp tahmini. OEP: belirli tek olay kayıp eşiğini yılda bir veya daha fazla aşma olasılığı eğrisi','PML kümülatif, OEP tek olay','OEP yalnızca deprem için','B','OEP: P(en büyük olay > x) vs x. AEP: P(yıllık toplam > x). PML: deterministik üst tahmin. Reasürans satın alma kılavuzu.'),
  q('LEVEL_3','hayatdisi-sigortalar','Katastrofik Risk Modelleri','Return period (dönüş periyodu) kavramı nedir?','Ortalama hasar süresi','1/P(aşım); 250-yıllık olay = yılda %0.4 aşım olasılıklı kayıp eşiği','Hasar ödeme süresi','Ortalama poliçe süresi','B','250-yıllık = %0.4 yıllık aşım olasılığı. Solvency II SCR 200-yıllık katastrofik senaryo kullanır.'),
  q('LEVEL_3','hayatdisi-sigortalar','Katastrofik Risk Modelleri','Secondary uncertainty (ikincil belirsizlik) cat modelde nedir?','Model parametresi hatası','Verilen olay gerçekleştiğinde hasar miktarının belirsizliği; zarar fonksiyonunun varyansı','Tehlike frekansı belirsizliği','Reasürans şartı belirsizliği','B','Primary: hangi olay, ne büyüklükte. Secondary: o olay gerçekleşince sigortalı hasar ne? Hasar fonksiyonu (MDR) varyansı.'),
  q('LEVEL_3','hayatdisi-sigortalar','Katastrofik Risk Modelleri','Zon/Coğrafi toplama riski (geographic concentration) neden önemlidir?','Prim fiyatlaması için','Birden fazla poliçenin aynı coğrafyada yoğunlaşması katastrofik olayda aşırı kümülasyona yol açar','Sadece tarife belirleme','İstatistiksel çeşitlendirme sağlar','B','Geographic correlation: tek deprem/fırtına aynı bölgedeki tüm poliçeleri etkileyebilir. Kümülasyon kontrolü zorunlu.'),

  // Solvency II — Hayat Dışı
  q('LEVEL_3','hayatdisi-sigortalar','Solvency II — Hayat Dışı','SCR Non-Life alt modülü hangi premium and reserve risk stresini kullanır?','Hasar sayısı iki katına çıkar','Prim ve rezervlerin log-normal dağılım varsayımıyla σ_premium ve σ_reserve volatilitesi uygulanır','Enflasyon %10 artar','Tüm poliçeler iptal edilir','B','SCR_nl = 3·σ·V formula (basitleştirilmiş). σ: EIOPA segmente göre volatilite. V: prim + hasar rezerv hacmi.'),
  q('LEVEL_3','hayatdisi-sigortalar','Solvency II — Hayat Dışı','Non-Life CAT SCR standart formülde nasıl hesaplanır?','Chain-Ladder','EIOPA ülke özgü faktörler (prim bazlı) veya olaya dayalı (tabanlı) senaryolar; deprem, fırtına, sel, insan yapımı','Sadece PML','Şirket seçimi','B','Cat SCR: natural cat (fırtına/deprem/sel/dolu) + man-made (yangın/deniz/havacılık vb.) + ülke faktörleri. Karmaşık hesaplama.'),
  q('LEVEL_3','hayatdisi-sigortalar','Solvency II — Hayat Dışı','Underwriting cycle (tarifeli döngü) neden hayat dışı sigortacılık için önemlidir?','Hayat tablosunu etkiler','Prim yetersizliği dönemlerinde (soft market) kombinasyon oranı 100% üstüne çıkar; sermaye yönetimini zorlaştırır','Reasürans kolaylaşır','Mortalite değişir','B','Hard market: yüksek prim, sıkı koşullar. Soft market: düşük prim, gevşek koşullar → CR>100 → teknik zarar risk.'),
  q('LEVEL_3','hayatdisi-sigortalar','Solvency II — Hayat Dışı','Lapse (poliçe iptali) riski hayat dışı sigortada hayat sigortasından farkı nedir?','Daha büyük etkisi var','Hayat dışında vadeler kısa, renewal tekrar fiyatlanabilir; hayat sigortasında çok yıllı garantiler daha büyük lapse riski oluşturur','Aynı etki','Hayat dışında yoktur','B','Hayat dışı: yıllık yenileme → lapse düşük BEL etkisi. Hayat: uzun vadeli garanti → büyük lapse SCR (down/up/mass).'),

  // Tarife Belirleme (Ratemaking)
  q('LEVEL_3','hayatdisi-sigortalar','Tarife Belirleme (Ratemaking)','Pure premium yöntemi nedir?','Toplam prim/poliçe sayısı','Beklenen hasar maliyetinin maruz kalmaya (exposure) bölümü; Loss/Exposure','Brüt prim yöntemi','Kombine rasyo yöntemi','B','Pure premium = Toplam hasar / Toplam exposure. Sonra fiyat = PP / (1 - expense ratio - profit loading).'),
  q('LEVEL_3','hayatdisi-sigortalar','Tarife Belirleme (Ratemaking)','Loss development ve loss trending ratemaking\'de neden gereklidir?','Sadece reasürans için','Geçmiş hasarları nihai değere (development) ve günümüz kost seviyesine (trend) getirmek için','Vergi hesabı','Rezerv hesabı','B','Development: IBNR dahil ultimate. Trend: hasar maliyeti enflasyonu (ULAE, tıp enflasyonu). İkisi olmadan prim yetersiz.'),
  q('LEVEL_3','hayatdisi-sigortalar','Tarife Belirleme (Ratemaking)','Credibility weighting ratemaking\'de ne zaman kullanılır?','Her zaman','Gözlem deneyimi yetersizse istatistiksel güvenilirlik için sektör/piyasa istatistikleriyle ağırlıklandırmak','Tam verisi olan büyük şirkette','Sadece maliyet enflasyonunda','B','Yetersiz kendi deneyimi → Z·(kendi PP) + (1-Z)·(endüstri PP). Bühlmann veya klasik tam kredibilite standardı.'),
  q('LEVEL_3','hayatdisi-sigortalar','Tarife Belirleme (Ratemaking)','Klasifikasyon ratemaking (sınıf tarifesi) için GLM kullanımının avantajı nedir?','Parametre gereksiz','Tüm tarife değişkenlerini aynı anda modeller; karşılıklı etkileşimi (interaction) kontrol eder; kalibre çarpan üretir','Daha az veri ister','Tek değişkenli analiz daha iyi','B','GLM (log-link, Poisson/Tweedie): p(hasar)=exp(α+β₁x₁+β₂x₂+...). Çok değişkenli; sadece univariate bias olmaz.'),

  // ─── SAĞLIK SİGORTALARI ──────────────────────────────────────────────────

  // Morbidite Tabloları
  q('LEVEL_3','saglik-sigortalari','Morbidite Tabloları','Morbidite tablosu mortalite tablosundan nasıl farklıdır?','Aynı tablodur','Mortalite: ölüm geçişi. Morbidite: hastalık insidansı, prevalansı ve iyileşme oranlarını içerir','Morbidite sadece yaşa bağlı','Morbidite sadece kronik hastalıklar için','B','Morbidite tablosu: q_x^sick (hastalanma oranı), q_x^recover (iyileşme), q_x^dead. Çok durumlu Markov modeli gerektirir.'),
  q('LEVEL_3','saglik-sigortalari','Morbidite Tabloları','İnsidans oranı ve prevalans oranı farkı nedir?','Aynı kavramdır','İnsidans: belirli dönemde yeni vakalar/nüfus. Prevalans: belli andaki toplam vaka/nüfus','İnsidans kümülatif, prevalans anlık','Prevalans daha dar','B','Incidence = yeni vaka/1000 kişi·yıl. Prevalence = toplam hasta/toplam nüfus (anlık fotoğraf).'),
  q('LEVEL_3','saglik-sigortalari','Morbidite Tabloları','Sağlık sigortacısı için morbidite trendinin önemi nedir?','Mortaliteyle aynı','Hastalık insidansındaki değişim gelecek hasar maliyetini etkiler; kronik hastalık artışı rezerv ve prim tahminini zorlaştırır','Demografik trend önemsiz','Sadece yaşlı nüfusla ilgili','B','Morbidity trend: tıbbi teknoloji, yaşam tarzı değişimi, yaşlanan nüfus. Tarife projeksiyonunda trend faktörü zorunlu.'),
  q('LEVEL_3','saglik-sigortalari','Morbidite Tabloları','Comorbidity (eş tanı) neden sağlık sigortası modellemesinde karmaşıklık yaratır?','Mortalite etkisi yok','Birden fazla kronik hastalığı olan bireylerin toplam maliyeti bağımsız hastalık maliyetlerinin toplamından çok farklı olabilir','Sadece yaşlılarda görülür','Önemsizdir','B','Comorbidity: diyabet + HT + böbrek hastalığı birlikte → bağımsız toplama göre çok daha yüksek maliyet. Kopula modeli.'),
  q('LEVEL_3','saglik-sigortalari','Morbidite Tabloları','Experience study (deneyim çalışması) morbidite tablosu güncellemesinde neden önemlidir?','Sadece denetim için','Gerçekleşen hastalık oranlarını varsayılan oranlarla karşılaştırarak A/E (Actual/Expected) farkını tespit eder; tabloyu kalibre eder','Vergi hesabı','Muhasebe zorunluluğu','B','A/E = gerçekleşen/beklenen. A/E > 1: tablo iyimser (kötümser tarife gerekli). A/E < 1: tablo kötümser. Sürekli güncelleme şart.'),

  // Sağlık Sigortası Matematik
  q('LEVEL_3','saglik-sigortalari','Sağlık Sigortası Matematik','Sağlık sigortasında stop-loss (aggregate deductible) nedir?','Bireysel hasar limiti','Toplam yıllık hasar belirli eşiği aştığında sigortacının ödeme yapması; kendi kendine sigortalı planlar için','Tek hasar indirimi','Reasürans limiti','B','Self-insured stop-loss: spesifik SL (tek kişi) ve aggregate SL (yıllık toplam). Şirketlerin sağlık planı riski sınırlar.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Sigortası Matematik','IBNR sağlık sigortasında hayat dışı sigortadan nasıl farklıdır?','Farklılık yok','Sağlık hasarları çok daha kısa gecikme süresi; aylık development yeterli; ancak tarife sezonu etkisi ve mevsimsellik var','Sağlıkta IBNR hesaplanmaz','Sağlıkta daha uzun kuyruk','B','Health IBNR: 3-6 ay tail. Mevsimsellik: grip sezonu, yılsonu erteleme. Aylık üçgen analizi. Lag triangle yaygın.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Sigortası Matematik','Community rating ile experience rating sağlık primlerinde farkı nedir?','Aynıdır','Community: tüm gruba aynı prim (risk paylaşımı); experience: grubun kendi geçmiş hasarına göre prim','Experience daha adil bir sigorta','Community sadece özel sigorta','B','Community rating: herkes aynı prim (dayanışma). Experience rating: kendi hasar geçmişine göre (piyasa etkin). Ahlaki tehlike vs. eleme.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Sigortası Matematik','PMPM (Per Member Per Month) ölçütü nedir?','Aylık toplam prim','Toplam maliyet / (üye sayısı × ay sayısı); sağlık planı maliyet karşılaştırma standardı','Hasta başına yıllık gelir','Kişi başına aylık kâr','B','PMPM = Toplam Gider / (Üye·Ay). Ürün, dönem, demografik segment karşılaştırmasında evrensel kullanım.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Sigortası Matematik','Risk adjustment (risk düzeltmesi) sağlık sigortasında ne amaçla kullanılır?','Prim hesabı için','Farklı risk profiline sahip planlar/sigortacılar arasında seçim yanlılığını (adverse selection) önlemek amacıyla transfer mekanizması','Rezerv amaçlı','Mortalite modeli','B','ACA risk adjustment: sağlıklı bireyleri çeken planlardan hasta ağırlıklı planlara transfer. HHS-HCC modeli.'),

  // Sağlık Tarifeleri
  q('LEVEL_3','saglik-sigortalari','Sağlık Tarifeleri','Sağlık sigortasında tarife faktörleri (rating factors) neler olabilir?','Sadece yaş','Yaş, cinsiyet, coğrafya, aile büyüklüğü, plan türü; tobacco use (bazı piyasalarda)','Sadece gelir düzeyi','Kredi skoru','B','Rating factors: demografik (yaş/cinsiyet), coğrafi (coğrafi maliyet endeksi), tütün kullanımı. ACA: sınırlı faktörler.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Tarifeleri','Sağlık sigortası tarifesinde trend analizi kaç bileşenden oluşur?','1','2: frekans trendi (hastalık başvurusu sıklığı) + şiddet trendi (başvuru başına maliyet)','3','4','B','Total trend = (1+freq trend)·(1+severity trend) - 1. Ayrı modelleme: frekans demografik; şiddet tıbbi enflasyon.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Tarifeleri','Medical Loss Ratio (MLR) nedir ve düzenleyici açıdan önemi nedir?','Kâr marjı','(Tıbbi giderler + kalite giderleri) / Prim; ACA zorunluluğu: bireysel %80, grup %85 altında kalınırsa prim iadesi','Yönetim gideri oranı','Teknik kâr oranı','B','MLR: ACA gereksinimi. MLR < minimum → sigortacı prim iadesi (rebate) yapar. Şeffaflık ve maliyet kontrolü amaçlı.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Tarifeleri','Adverse selection (olumsuz seçilim) sağlık tarifesini nasıl bozar?','Prim düşer','Yüksek riskli bireyler düşük primli planlara yönelir; prim spirali başlar; düşük riskli bireyler ayrılır','Prim sabit kalır','Şiddet trendi azalır','B','Death spiral: hasta bireyler sigortalanır → hasar yüksek → prim artar → sağlıklılar ayrılır → daha yüksek prim. Piyasa çöküşü.'),
  q('LEVEL_3','saglik-sigortalari','Sağlık Tarifeleri','Capitation (kişi başı sabit ödeme) modelinde aktüeryal risk nasıl değişir?','Risk sigortacıda kalır','Sağlayıcıya (hastane/hekim) hizmet hacmi riski aktarılır; fazla hizmet → zarar, az hizmet → kâr','Risk devlete geçer','Risk sigortalıya geçer','B','Capitation: sağlayıcı PMPM alır, tüm hizmetleri sunar. Hizmet hacmi riski sağlayıcıda. Aşırı tedavi azalır, yetersiz tedavi riski oluşur.'),

];

async function upload(batch) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/question_bank`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': SERVICE_KEY,
      'Authorization': `Bearer ${SERVICE_KEY}`,
      'Prefer': 'return=minimal',
    },
    body: JSON.stringify(batch),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`HTTP ${res.status}: ${text}`);
  }
}

async function main() {
  console.log(`Toplam soru: ${questions.length}`);
  const BATCH = 20;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await upload(batch);
    console.log(`✓ ${Math.min(i + BATCH, questions.length)}/${questions.length} yüklendi`);
  }
  console.log('✅ LEVEL_3 seed tamamlandı!');
}

main().catch(e => { console.error(e); process.exit(1); });
