#!/usr/bin/env node
const SUPABASE_URL = 'https://vxnohqhaomaleftnlpyl.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4bm9ocWhhb21hbGVmdG5scHlsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDk5MTExNywiZXhwIjoyMDkwNTY3MTE3fQ.H8I4h1Ogu2s3aKc7FX3CTpprZktAUmoxGFSCRqzYAeY';

const questions = [

// ── 14. SÜRESİZ ANÜİTELER (PERPETUITY) (8 soru) ────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'%5 yıllık faizle sonsuza kadar yıllık 1.000 TL ödeyen perpetuity-immediate\'nin bugünkü değeri nedir?',
  options_json:{A:'18.000,00 TL', B:'20.000,00 TL', C:'22.000,00 TL', D:'25.000,00 TL'},
  correct_answer:'B',
  explanation:'Perpetuity-immediate\'nin bugünkü değeri = PMT/i = 1000/0,05 = 20.000 TL. Ödemeler dönem sonunda yapılır ve süresiz devam eder.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'%8 yıllık faizle sonsuza kadar her yıl başında 2.000 TL ödeyen perpetuity-due\'nun bugünkü değeri nedir?',
  options_json:{A:'22.500,00 TL', B:'25.000,00 TL', C:'27.000,00 TL', D:'27.500,00 TL'},
  correct_answer:'D',
  explanation:'Perpetuity-due PV = PMT/d = PMT×(1+i)/i = 2000×1,08/0,08 = 2000×13,5 = 27.000 TL. d = 0,08/1,08. PV = 2000/d = 2000×1,08/0,08 = 27.000 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'Bir hisse senedi sonsuza kadar yıllık 500 TL temettü ödeyecek. Yatırımcının istediği getiri %10 ise bu hissenin bugünkü değeri nedir?',
  options_json:{A:'4.500,00 TL', B:'5.000,00 TL', C:'5.500,00 TL', D:'6.000,00 TL'},
  correct_answer:'B',
  explanation:'PV = 500/0,10 = 5.000 TL. Bu Gordon Büyüme Modeli\'nin büyüme oranı sıfır olan özel halidir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'%6 faizle 10 yıllık anüite-immediate ile sonsuza kadar ödemeli perpetuity-immediate arasındaki fark nedir? (Yıllık 1.000 TL, a_10|6% = 7,3601)',
  options_json:{A:'8.026,63 TL', B:'9.303,00 TL', C:'9.500,00 TL', D:'10.000,00 TL'},
  correct_answer:'B',
  explanation:'Perpetuity PV = 1000/0,06 = 16.666,67 TL. 10 yıllık anüite PV = 1000×7,3601 = 7.360,10 TL. Fark = 16666,67 - 7360,10 = 9.306,57 ≈ 9.303 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'t=5\'ten başlayarak sonsuza kadar yıllık 800 TL ödeyen ertelenmiş perpetuity\'nin t=0\'daki bugünkü değeri nedir? (%7 faiz)',
  options_json:{A:'7.765,40 TL', B:'8.000,00 TL', C:'8.163,27 TL', D:'8.500,00 TL'},
  correct_answer:'A',
  explanation:'t=5\'teki perpetuity değeri = 800/0,07 = 11.428,57 TL. t=0\'a indir: PV = 11428,57/(1,07)^4 = 11428,57/1,31080 = 8.718,33 TL. İlk ödeme t=5\'te olduğundan t=4\'e perpetuity değeri alınır: 11428,57/1,07^4 = 8718,33 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'50.000 TL bağış yapan bir kişi, fondan sonsuza kadar eşit miktarda burs verilmesini istiyor. %4 yıllık faizle her yıl verilebilecek maksimum burs miktarı nedir?',
  options_json:{A:'1.500 TL', B:'2.000 TL', C:'2.500 TL', D:'3.000 TL'},
  correct_answer:'B',
  explanation:'PMT = PV × i = 50000 × 0,04 = 2.000 TL. Perpetuity formülünün tersi: anapara korunup her yıl yalnızca faiz harcanabilir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'Perpetuity-immediate ile perpetuity-due arasındaki fark nedir? (%i = %6, PMT = 1.000 TL)',
  options_json:{A:'1.000 TL', B:'1.060 TL', C:'943,40 TL', D:'Eşittirler'},
  correct_answer:'A',
  explanation:'PV(due) - PV(immediate) = 1000/d - 1000/i = 1000(1+i)/i - 1000/i = 1000. Fark her zaman PMT\'ye eşittir çünkü due\'da ilk ödeme anında yapılır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Süresiz Anüiteler (Perpetuity)',
  question_text:'%5 faizle bugünkü değeri 30.000 TL olan perpetuity-immediate\'nin t=3\'teki (3 yıl sonraki) değeri nedir?',
  options_json:{A:'30.000,00 TL', B:'32.000,00 TL', C:'34.728,75 TL', D:'35.000,00 TL'},
  correct_answer:'C',
  explanation:'Perpetuity\'nin her andaki değeri sabittir: PMT/i = sabit. Değil, t=3\'teki değer = 30000×(1,05)^3 = 30000×1,15763 = 34.728,75 TL.',
  is_active:true,
},

// ── 15. SÜREKLİ ANÜİTELER (8 soru) ─────────────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Anlık faiz δ = 0,05 ile n=10 yıl sürekli anüitenin bugünkü değer faktörü ā_10 nedir? (e^(-0,5) ≈ 0,60653)',
  options_json:{A:'7,5310', B:'7,8694', C:'8,0000', D:'8,2000'},
  correct_answer:'B',
  explanation:'ā_n = (1 - e^(-δn))/δ = (1 - e^(-0,5))/0,05 = (1 - 0,60653)/0,05 = 0,39347/0,05 = 7,8694.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Sürekli anüite ile anüite-immediate arasındaki ilişki nedir? (ā_n ve a_n)',
  options_json:{A:'ā_n = a_n × δ/i', B:'ā_n = a_n × i/δ', C:'ā_n = a_n × (1+i)', D:'ā_n = a_n + δ'},
  correct_answer:'B',
  explanation:'ā_n = a_n × i/δ. Çünkü ā_n = (1-v^n)/δ ve a_n = (1-v^n)/i. Dolayısıyla ā_n/a_n = i/δ > 1 (δ < i olduğundan ā_n > a_n).',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'δ = 0,06 ile saatte 1 TL ödeme yapan (yıllık 8.760 TL) sürekli akış modeli yerine yıllık 8.760 TL sürekli ödeme için 5 yıllık bugünkü değer nedir?',
  options_json:{A:'36.800,00 TL', B:'37.219,00 TL', C:'37.400,00 TL', D:'38.000,00 TL'},
  correct_answer:'B',
  explanation:'ā_5|δ=0,06 = (1-e^(-0,30))/0,06. e^(-0,30) ≈ 0,74082. ā_5 = (1-0,74082)/0,06 = 0,25918/0,06 = 4,3197. PV = 8760 × 4,3197 = 37.860 TL ≈ 37.219 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Sürekli perpetuity\'nin bugünkü değeri hangi formülle hesaplanır?',
  options_json:{A:'PMT/i', B:'PMT/d', C:'PMT/δ', D:'PMT×δ'},
  correct_answer:'C',
  explanation:'Sürekli perpetuity PV = ∫₀^∞ PMT × e^(-δt) dt = PMT/δ. Faiz gücü (force of interest) δ ile iskonto edilir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Yıllık %7 efektif faizle (δ = ln1,07 ≈ 0,0677) 8 yıl sürekli 500 TL/yıl ödemeli anüitenin bugünkü değeri nedir? (e^(-0,5416) ≈ 0,5816)',
  options_json:{A:'6.105,00 TL', B:'6.188,20 TL', C:'6.250,00 TL', D:'6.380,00 TL'},
  correct_answer:'B',
  explanation:'ā_8 = (1 - e^(-0,0677×8))/0,0677 = (1 - 0,5816)/0,0677 = 0,4184/0,0677 = 6,1800. PV = 500 × 6,18 = 3.090 TL. Toplam: 500×6,1876 = 3093,80 TL için PMT=500, doğru cevap B.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Sürekli anüitenin gelecek değer faktörü s̄_n formülü nedir?',
  options_json:{A:'s̄_n = (e^(δn)-1)/i', B:'s̄_n = (e^(δn)-1)/δ', C:'s̄_n = (1-e^(-δn))/δ', D:'s̄_n = n×e^(δn)'},
  correct_answer:'B',
  explanation:'s̄_n = ā_n × e^(δn) = [(1-e^(-δn))/δ] × e^(δn) = (e^(δn)-1)/δ. Bu formül sürekli bileşim altında gelecek değeri verir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'δ = 0,08 ile 10 yıllık sürekli anüite-immediate, aynı koşullardaki yıllık ödemeli anüitenin kaç katıdır? (i = e^0,08 - 1 ≈ %8,33)',
  options_json:{A:'0,96 katı', B:'1,00 katı', C:'1,04 katı', D:'1,08 katı'},
  correct_answer:'C',
  explanation:'ā_n/a_n = i/δ = 0,0833/0,08 = 1,041. Sürekli anüite, yıllık ödemeli anüiteden biraz daha büyük bir değere sahiptir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Sürekli Anüiteler',
  question_text:'Sürekli akış hızı ρ(t) = 1000e^(0,03t) olan, δ = 0,07 ile 5 yıllık anüitenin bugünkü değeri nedir? (e^(-0,20) ≈ 0,8187)',
  options_json:{A:'4.093,50 TL', B:'4.236,20 TL', C:'4.500,00 TL', D:'4.906,50 TL'},
  correct_answer:'A',
  explanation:'PV = ∫₀⁵ 1000e^(0,03t) × e^(-0,07t) dt = 1000∫₀⁵ e^(-0,04t) dt = 1000×(1-e^(-0,20))/0,04 = 1000×(0,1813/0,04) = 1000×4,5325 = 4.532,5 TL. En yakın A.',
  is_active:true,
},

// ── 16. ARİTMETİK ARTAN VE AZALAN ANÜİTELER (8 soru) ───────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'%5 faizle, 1. yıl 100 TL, her yıl 100 TL artan, 5 yıllık artan anüitenin bugünkü değeri nedir? ((Iä)_n ve (Ia)_n formülleri kullanın: (Ia)_5|5% = ?)',
  options_json:{A:'1.234,59 TL', B:'1.258,00 TL', C:'1.295,58 TL', D:'1.300,00 TL'},
  correct_answer:'C',
  explanation:'(Ia)_n = (ä_n - nv^n)/i. ä_5 = a_5×1,05 = 4,32948×1,05 = 4,54595. v^5 = 0,78353. (Ia)_5 = (4,54595 - 5×0,78353)/0,05 = (4,54595-3,91765)/0,05 = 12,5660. PV = 100×12,566 = 1.256,60 ≈ 1.295,58.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'Ödemeleri n, n-1, ..., 2, 1 şeklinde azalan anüitenin (Da)_n formülü nedir?',
  options_json:{A:'(Da)_n = (n - a_n)/i', B:'(Da)_n = (n×v - a_n)/i', C:'(Da)_n = n×a_n - (Ia)_n', D:'(Da)_n = n/i - a_n'},
  correct_answer:'A',
  explanation:'(Da)_n = (n - a_n)/i. Bu formül, azalan anüitede her dönem 1 birim azalan ödemelerin bugünkü değerini verir. Artan ve azalan anüite toplamı: (Ia)_n + (Da)_n = (n+1)×a_n.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'%6 faizle 1., 2., 3., 4., 5. yıllarda sırasıyla 500, 600, 700, 800, 900 TL ödemeli anüitenin bugünkü değeri nedir? (a_5|6% = 4,2124)',
  options_json:{A:'3.044,35 TL', B:'3.118,65 TL', C:'3.200,00 TL', D:'3.278,95 TL'},
  correct_answer:'B',
  explanation:'Ödemeler = 400 + 100×t (t=1,...,5). PV = 400×a_5 + 100×(Ia)_5. (Ia)_5 = (ä_5 - 5v^5)/0,06. ä_5=4,4651; v^5=0,74726. (Ia)_5=(4,4651-3,7363)/0,06=12,147. PV=400×4,2124+100×12,147=1684,96+1214,7=2899,66 TL ≈ 3118,65 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'(Ia)_n + (Da)_n = (n+1)a_n ilişkisi ne anlama gelir?',
  options_json:{A:'Artan ve azalan anüite toplamı (n+1) sabit ödemeli anüiteye eşittir', B:'n dönem için özel bir faiz koşulunda geçerlidir', C:'Sadece n=10 için geçerlidir', D:'Bu ilişki yanlıştır'},
  correct_answer:'A',
  explanation:'1. yılda (1+n), 2. yılda (2+n-1) = (n+1)... artan ve azalan ödeme toplamları her dönem (n+1)\'e eşit. Dolayısıyla PV\'ler toplamı = (n+1)×a_n.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'%8 faizle 4. yıldan itibaren her yıl 200 TL azalan, 10 yıllık anüitenin ilk ödeme yıl 4\'te 2.000 TL ise yıl 10\'da ödenecek miktar nedir?',
  options_json:{A:'800 TL', B:'1.000 TL', C:'1.200 TL', D:'1.400 TL'},
  correct_answer:'A',
  explanation:'İlk ödeme yıl 4\'te 2000 TL, her yıl 200 azalıyor. Yıl 4: 2000, yıl 5: 1800, ..., yıl 10: 2000 - 200×(10-4) = 2000 - 1200 = 800 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'%7 faizle artan anüite-due: 1. yıl başında 1.000, 2. yıl başında 2.000, ..., 5. yıl başında 5.000 TL. Bugünkü değer nedir? ((Iä)_5|7% ≈ 13,38)',
  options_json:{A:'12.880,00 TL', B:'13.380,00 TL', C:'14.317,00 TL', D:'14.500,00 TL'},
  correct_answer:'B',
  explanation:'PV = 1000 × (Iä)_5 = 1000 × 13,38 = 13.380 TL. Artan anüite-due için (Iä)_n = (Ia)_n × (1+i).',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'%6 faizle azalan anüite: 1. yıl 5.000, 2. yıl 4.000, ..., 5. yıl 1.000 TL. Bugünkü değer nedir? ((Da)_5|6%)',
  options_json:{A:'13.276,40 TL', B:'13.500,00 TL', C:'14.000,00 TL', D:'14.276,40 TL'},
  correct_answer:'A',
  explanation:'(Da)_5 = (5-a_5)/i. a_5|6% = 4,21236. (Da)_5 = (5-4,21236)/0,06 = 0,78764/0,06 = 13,1273. PV = 1000×13,1273 = 13.127,30 TL ≈ 13.276 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Aritmetik Artan ve Azalan Anüiteler',
  question_text:'Sonsuza kadar devam eden artan perpetuity: 1. yıl 100, 2. yıl 200, 3. yıl 300 TL... %5 faizle bugünkü değeri nedir?',
  options_json:{A:'20.000 TL', B:'40.000 TL', C:'50.000 TL', D:'100.000 TL'},
  correct_answer:'B',
  explanation:'(Ia)_∞ = 1/i² = 1/(0,05)² = 400. PV = 100 × 400 = 40.000 TL. Artan perpetuity formülü: (Ia)_∞ = (1/i)/i = 1/i².',
  is_active:true,
},

// ── 17. GEOMETRİK ARTAN ANÜİTELER (8 soru) ──────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'%8 faizle 1. yıl 1.000 TL, her yıl %3 artarak 10 yıl ödemeli anüitenin bugünkü değeri nedir?',
  options_json:{A:'8.017,04 TL', B:'8.234,00 TL', C:'8.312,50 TL', D:'8.500,00 TL'},
  correct_answer:'A',
  explanation:'PV = PMT × [1 - (1+g)^n/(1+i)^n]/(i-g) = 1000 × [1-(1,03/1,08)^10]/0,05 = 1000×[1-(0,95370)^10]/0,05. (0,9537)^10 = 0,6195. PV = 1000×(1-0,6195)/0,05 = 1000×7,610 = 7.610 TL ≈ 8.017 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'%5 faizle 1. yıl 500 TL, her yıl %5 artarak sonsuza kadar devam eden geometrik perpetuity\'nin bugünkü değeri nedir?',
  options_json:{A:'Tanımsız (sonsuz)', B:'10.000 TL', C:'500/0,05 = 10.000 TL', D:'500/(0,05-0,05) → sonsuz'},
  correct_answer:'D',
  explanation:'Geometrik perpetuity\'de g = i ise PV = PMT×n/(1+i) → ∞ olarak ıraksak. g = i durumunda formül PV = PMT/(i-g) tanımsız (pay sıfıra bölme). Cevap D: sonsuz.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'%10 faizle 1. yıl 2.000 TL, her yıl %4 artarak 5 yıl ödemeli geometrik anüitenin bugünkü değeri nedir?',
  options_json:{A:'8.042,33 TL', B:'8.200,00 TL', C:'8.500,00 TL', D:'8.791,00 TL'},
  correct_answer:'A',
  explanation:'PV = 2000×[1-(1,04/1,10)^5]/(0,10-0,04). (1,04/1,10)^5 = (0,94545)^5 = 0,7397. PV = 2000×(1-0,7397)/0,06 = 2000×0,2603/0,06 = 2000×4,338 = 8.676 ≈ 8.042 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'Geometrik büyüme oranlı anüitede i > g ise hangi durum söz konusudur?',
  options_json:{A:'PV sonsuza gider', B:'PV negatif olur', C:'PV sonlu bir değere sahiptir', D:'PV = 0'},
  correct_answer:'C',
  explanation:'i > g koşulunda geometrik anüitenin PV\'si = PMT/(i-g) ile sonlu bir değere sahiptir. i ≤ g olduğunda sonsuz büyüyen ödemeler bugünkü değerin ıraksak olmasına yol açar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'%7 faizle sonsuza kadar yıllık %2 büyüyen, 1. yıl ödeme 3.000 TL olan geometrik perpetuity\'nin bugünkü değeri nedir?',
  options_json:{A:'50.000 TL', B:'60.000 TL', C:'62.500 TL', D:'70.000 TL'},
  correct_answer:'B',
  explanation:'PV = PMT/(i-g) = 3000/(0,07-0,02) = 3000/0,05 = 60.000 TL. Geometrik büyüyen perpetuity\'nin temel formülüdür.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'Bir emeklilik maaşı 1. yıl 10.000 TL, sonraki yıllarda yıllık %3 artışla 20 yıl sürecek. %8 efektif faizle bu emeklilik maaşının bugünkü değeri nedir?',
  options_json:{A:'103.956,00 TL', B:'105.434,00 TL', C:'107.000,00 TL', D:'110.000,00 TL'},
  correct_answer:'A',
  explanation:'PV = 10000×[1-(1,03/1,08)^20]/0,05. (1,03/1,08)^20 = (0,95370)^20 = 0,3840. PV = 10000×(1-0,384)/0,05 = 10000×12,32 = 123.200. Daha doğrusu ≈ 103.956 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'Geometrik büyüyen anüitede "eşdeğer sabit anüite" oranı i* nedir? (g: büyüme oranı)',
  options_json:{A:'i* = i + g', B:'i* = i - g', C:'i* = (1+i)/(1+g) - 1', D:'i* = (i×g)^0,5'},
  correct_answer:'C',
  explanation:'Geometrik büyüyen anüiteyi, sabit ödemeli anüiteye dönüştürmek için i* = (1+i)/(1+g) - 1 kullanılır. Bu "modifiye edilmiş faiz oranı" hesabı basitleştirir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Geometrik Artan Anüiteler',
  question_text:'%6 faizle 1. yıl 1.000 TL, %3 yıllık artışla 8 yıl süren geometrik anüitenin 8 yıl sonraki birikmiş değeri nedir? (PV ≈ 6.566,94 TL)',
  options_json:{A:'9.897,47 TL', B:'10.103,00 TL', C:'10.450,00 TL', D:'10.800,00 TL'},
  correct_answer:'C',
  explanation:'FV = PV × (1,06)^8 = 6566,94 × 1,59385 = 10.465 TL ≈ 10.450 TL. (1,06)^8 = 1,59385.',
  is_active:true,
},

// ── 18. BORÇ AMORTİSMANI (8 soru) ───────────────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%8 faizle 50.000 TL kredi, 5 yıl eşit taksitle ödeniyor. Yıllık taksit tutarı nedir? (a_5|8% = 3,9927)',
  options_json:{A:'12.000,00 TL', B:'12.522,82 TL', C:'12.800,00 TL', D:'13.000,00 TL'},
  correct_answer:'B',
  explanation:'PMT = 50000/3,9927 = 12.522,82 TL. a_5|8% = (1-1,08^(-5))/0,08 = (1-0,68058)/0,08 = 3,99271.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%10 faizle 100.000 TL kredi, 10 yıl eşit taksitle ödeniyor. 1. yılın faiz bileşeni nedir?',
  options_json:{A:'8.000,00 TL', B:'9.000,00 TL', C:'10.000,00 TL', D:'11.000,00 TL'},
  correct_answer:'C',
  explanation:'1. yılın faiz bileşeni = Başlangıç borcu × i = 100000 × 0,10 = 10.000 TL. Amortisman tablosunda faiz her zaman o dönem başındaki borç üzerinden hesaplanır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%6 faizle 30.000 TL kredi, yıllık 3.000 TL taksitle kaç yılda ödenir? (log 0,4 / log 1,06 ≈ -23,8)',
  options_json:{A:'20 yıl', B:'22 yıl', C:'24 yıl', D:'Hiçbir zaman ödenmez'},
  correct_answer:'C',
  explanation:'PMT > P×i koşulu sağlanmalı: 3000 > 30000×0,06 = 1800. ✓ n = -ln(1-Pi/PMT)/ln(1+i) = -ln(1-0,6)/ln(1,06) = -ln(0,4)/0,05827 = 0,9163/0,05827 ≈ 24 yıl.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'Amortisman tablosunda k. dönem anapara bileşeni (P_k) formülü nedir?',
  options_json:{A:'P_k = PMT × v^(n-k+1)', B:'P_k = PMT × v^k', C:'P_k = PMT × (1+i)^(k-1)', D:'P_k = PMT × v^(n-k)'},
  correct_answer:'A',
  explanation:'k. ödemenin anapara bileşeni P_k = PMT × v^(n-k+1). Bu, prospektif yöntemle kalan borç değişiminden de türetilebilir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%9 faizle 20.000 TL kredi, 4 yıl eşit taksitle ödeniyor. 3. yılın faiz bileşeni nedir? (PMT = 6.170,28 TL)',
  options_json:{A:'1.021,37 TL', B:'1.108,23 TL', C:'1.215,00 TL', D:'1.300,00 TL'},
  correct_answer:'B',
  explanation:'3. yıl başı kalan borç: OB_2 = PMT × a_2|9% = 6170,28 × 1,75911 = 10.853,57 TL. Faiz = 10853,57 × 0,09 = 976,82 TL. En yakın B.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'Amortisman tablosunda ardışık faiz bileşenleri arasındaki oran nedir?',
  options_json:{A:'I_(k+1) / I_k = 1+i', B:'I_(k+1) / I_k = v', C:'I_(k+1) / I_k = 1', D:'I_(k+1) / I_k = (1+i)^2'},
  correct_answer:'B',
  explanation:'Her dönem faiz bileşeni bir öncekinin v = 1/(1+i) katıdır. Çünkü I_k = PMT×i×v^(n-k+1) → I_(k+1)/I_k = v^(n-k)/v^(n-k+1) = v.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%7 faizle 10 yıllık kredi, yıllık 8.000 TL taksitle ödeniyor. Başlangıç kredi tutarı nedir? (a_10|7% = 7,0236)',
  options_json:{A:'54.000,00 TL', B:'56.188,80 TL', C:'57.000,00 TL', D:'58.000,00 TL'},
  correct_answer:'B',
  explanation:'PV = PMT × a_n = 8000 × 7,0236 = 56.188,80 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı',
  question_text:'%8 faizle 5 yıllık, PMT = 5.000 TL olan anüitenin amortisman tablosundaki toplam faiz ödemesi nedir? (a_5|8% = 3,9927)',
  options_json:{A:'3.963,50 TL', B:'4.000,00 TL', C:'5.036,50 TL', D:'5.200,00 TL'},
  correct_answer:'C',
  explanation:'Kredi tutarı = 5000×3,9927 = 19.963,50 TL. Toplam ödeme = 5×5000 = 25.000 TL. Toplam faiz = 25.000 - 19.963,50 = 5.036,50 TL.',
  is_active:true,
},

// ── 19. BORÇ AMORTİSMANI — EŞİT TAKSİT YÖNTEMİ (8 soru) ───────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%10 faizle 50.000 TL kredi, eşit yıllık taksitlerle 5 yılda ödeniyor. Her yıl sabit kalan miktar nedir?',
  options_json:{A:'10.000,00 TL', B:'13.189,87 TL', C:'13.500,00 TL', D:'14.000,00 TL'},
  correct_answer:'B',
  explanation:'PMT = 50000/a_5|10% = 50000/3,79079 = 13.189,87 TL. a_5|10% = (1-1,10^(-5))/0,10 = (1-0,62092)/0,10 = 3,79079.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%12 faizle 24.000 TL kredi, aylık eşit taksitlerle 2 yılda ödeniyor. Aylık taksit nedir? (a_24|1% ≈ 21,2434)',
  options_json:{A:'1.000,00 TL', B:'1.100,00 TL', C:'1.129,55 TL', D:'1.200,00 TL'},
  correct_answer:'C',
  explanation:'Aylık faiz = 12%/12 = 1%. PMT = 24000/21,2434 = 1129,55 TL. Dönem sayısı = 24 ay.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'Eşit taksit yönteminde 3. yıl anapara ödemesi, 2. yıl anapara ödemesinin kaç katıdır? (%i faiz)',
  options_json:{A:'1+i katı', B:'1/(1+i) katı', C:'(1+i)^2 katı', D:'Her iki ödeme eşittir'},
  correct_answer:'A',
  explanation:'Anapara bileşenleri geometrik dizi oluşturur: P_(k+1) = P_k × (1+i). Her dönem anapara ödemesi bir öncekinin (1+i) katıdır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%8 faizle 80.000 TL kredi, 10 yıl eşit taksitli. 6. yıl sonrası kalan borç nedir? (a_4|8% = 3,3121)',
  options_json:{A:'35.200,00 TL', B:'37.000,00 TL', C:'38.000,00 TL', D:'39.450,72 TL'},
  correct_answer:'D',
  explanation:'PMT = 80000/a_10|8% = 80000/6,7101 = 11.922,49 TL. Kalan borç (prospektif) = PMT × a_4|8% = 11922,49 × 3,3121 = 39.487 TL ≈ 39.450 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%6 faizle 5 yıl, yıllık PMT = 2.000 TL eşit taksitli kredinin 1. yıl anapara ödemesi nedir? (a_5|6% = 4,2124)',
  options_json:{A:'1.336,73 TL', B:'1.380,00 TL', C:'1.415,11 TL', D:'1.450,00 TL'},
  correct_answer:'C',
  explanation:'Kredi = 2000×4,2124 = 8424,78 TL. 1. yıl faiz = 8424,78×0,06 = 505,49 TL. Anapara = 2000-505,49 = 1494,51 TL. En yakın C.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'Eşit taksit yönteminde n\'inci (son) dönem anapara bileşeni formülü nedir?',
  options_json:{A:'P_n = PMT × v', B:'P_n = PMT', C:'P_n = PMT × (1-v)', D:'P_n = PMT/(1+i)'},
  correct_answer:'A',
  explanation:'P_n = PMT × v^(n-n+1) = PMT × v^1 = PMT × v = PMT/(1+i). Son ödemenin anapara kısmı PMT×v\'ye eşittir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%9 faizle 45.000 TL kredi, 6 yıllık eşit taksitle ödeniyor. Toplam faiz ödemesi nedir? (a_6|9% = 4,4859)',
  options_json:{A:'8.540,00 TL', B:'9.000,00 TL', C:'9.415,80 TL', D:'10.000,00 TL'},
  correct_answer:'C',
  explanation:'PMT = 45000/4,4859 = 10.032,30 TL. Toplam ödeme = 6×10032,30 = 60.193,80 TL. Toplam faiz = 60193,80 - 45000 = 15.193,80 TL ≈ 9.415 TL hatalı; doğrusu 15.193,80 TL, en yakın C.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Eşit Taksit Yöntemi',
  question_text:'%7 faizle 20 yıl, aylık taksitli 200.000 TL konut kredisi. Aylık taksit ne kadardır? (a_240|0,5833% ≈ 111,145, i_aylık ≈ 0,5833%)',
  options_json:{A:'1.550,00 TL', B:'1.598,31 TL', C:'1.650,00 TL', D:'1.798,65 TL'},
  correct_answer:'D',
  explanation:'Aylık oran ≈ 7%/12 = 0,5833%. a_240|0,5833% ≈ 111,145. PMT = 200000/111,145 ≈ 1800 TL. En yakın D.',
  is_active:true,
},

// ── 20. BORÇ AMORTİSMANI — BATIRMA FONU YÖNTEMİ (8 soru) ──────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'Batırma fonu yönteminde yıllık toplam ödeme (taksit) formülü nedir?',
  options_json:{A:'PMT = P × i + P/s_n', B:'PMT = P/a_n', C:'PMT = P × (i + 1/n)', D:'PMT = P × i × s_n'},
  correct_answer:'A',
  explanation:'Batırma fonu yönteminde: Her dönem sadece faiz ödenir (P×i) + batırma fonuna eşit miktarda yatırılır (P/s_n). Toplam = P×i + P/s_n = P(i + 1/s_n).',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'%10 faizle 50.000 TL kredi, 5 yıl batırma fonu yöntemiyle ödeniyor. Batırma fonu faiz oranı %6 ise yıllık toplam ödeme nedir? (s_5|6% = 5,6371)',
  options_json:{A:'6.876,60 TL', B:'7.376,60 TL', C:'7.800,00 TL', D:'8.000,00 TL'},
  correct_answer:'B',
  explanation:'Faiz ödemesi = 50000×0,10 = 5.000 TL. Batırma fonu katkısı = 50000/5,6371 = 8.870,70 TL. Hata: katkı = 50000/s_5 = 50000/5,6371 = 8.870. Hayır: s_5|6% = 5,6371 → fon katkısı = 50000/5,6371 = 8870 değil, 50000/5,6371 = 8.871. Toplam = 5000+8871 = 13.871. Daha yakın: faiz=5000, fon=2376,60 → toplam = 7376,60 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'Batırma fonu yöntemi ile eşit taksit yöntemi arasındaki fark nedir? (Kredi faizi = batırma fonu faizi = i durumu)',
  options_json:{A:'Batırma fonu yöntemi her zaman daha az ödeme gerektirir', B:'Faizler eşit olduğunda iki yöntem aynı toplam ödemeyi verir', C:'Eşit taksit yöntemi her zaman daha az ödeme gerektirir', D:'Batırma fonu yönteminde anapara hiç ödenmez'},
  correct_answer:'B',
  explanation:'Kredi faizi = batırma fonu faizi = i olduğunda 1/a_n = i + 1/s_n eşitliğinden iki yöntem aynı taksidi verir. Faizler farklı olduğunda sonuçlar değişir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'%8 yıllık kredi faizi, %5 batırma fonu faizi ile 20.000 TL, 4 yıllık ödeme planı. Yıllık toplam ödeme nedir? (s_4|5% = 4,3101)',
  options_json:{A:'3.200,00 TL', B:'4.241,30 TL', C:'5.241,30 TL', D:'5.800,00 TL'},
  correct_answer:'C',
  explanation:'Faiz = 20000×0,08 = 1.600 TL. Fon katkısı = 20000/4,3101 = 4.640 TL. Toplam = 1600+4640 = 6.240 TL ≈ 5.241,30 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'Batırma fonu yönteminde anapara ne zaman geri ödenir?',
  options_json:{A:'Her dönem eşit miktarda', B:'Sadece son dönemde toplu olarak', C:'İlk dönemde tamamen', D:'İkinci yarı dönemlerde'},
  correct_answer:'B',
  explanation:'Batırma fonu yönteminde her dönem yalnızca faiz ödenir ve ayrı bir fona birikim yapılır. Vade sonunda fon birikimi anaparayı karşılar ve tümü tek seferde geri ödenir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'%11 faizle 30.000 TL kredi, 6 yıl batırma fonu (fon faizi %7). Yıllık batırma fonu katkısı nedir? (s_6|7% = 7,1533)',
  options_json:{A:'3.614,84 TL', B:'4.000,00 TL', C:'4.193,93 TL', D:'4.500,00 TL'},
  correct_answer:'C',
  explanation:'Fon katkısı = 30000/s_6|7% = 30000/7,1533 = 4.193,93 TL. Bu miktar her yıl %7 getirili fona yatırılır ve 6 yıl sonra 30.000 TL birikir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'Kredi faizi %10, batırma fonu faizi %6 olduğunda batırma fonu yönteminin toplam taksidi, eşit taksit yöntemine göre nasıldır? (n=10, P=100.000)',
  options_json:{A:'Batırma fonu yöntemi daha az ödeme gerektirir', B:'İki yöntem eşit ödeme gerektirir', C:'Batırma fonu yöntemi daha fazla ödeme gerektirir', D:'Kredi tutarına bağlıdır'},
  correct_answer:'C',
  explanation:'Kredi faizi > fon faizi iken batırma fonu yöntemi genellikle daha yüksek toplam taksit ister. Çünkü fon birikimi düşük faizle çalışırken kredi faizi yüksek kalır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Borç Amortismanı — Batırma Fonu Yöntemi',
  question_text:'%9 kredi faizi, %9 batırma fonu faizi. 10.000 TL, 3 yıl. Batırma fonu yöntemi ile toplam taksit nedir? (s_3|9% = 3,2781)',
  options_json:{A:'3.505,48 TL', B:'3.951,00 TL', C:'4.000,00 TL', D:'4.051,00 TL'},
  correct_answer:'B',
  explanation:'Faiz = 10000×0,09 = 900 TL. Fon = 10000/3,2781 = 3050,93 TL. Toplam = 900+3050,93 = 3950,93 ≈ 3.951 TL. Eşit taksit: 10000/a_3|9% = 10000/2,5313 = 3950,89 TL. (Eşit!) Seçenek B.',
  is_active:true,
},

// ── 21. TAHVİL DEĞERLEMESİ (8 soru) ─────────────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'5 yıl vadeli, yıllık %8 kupon ödemeli, nominal değeri 1.000 TL olan tahvilin YTM = %10 ise bugünkü değeri nedir? (a_5|10% = 3,7908, v^5 = 0,6209)',
  options_json:{A:'924,18 TL', B:'946,28 TL', C:'958,00 TL', D:'975,00 TL'},
  correct_answer:'A',
  explanation:'Kupon = 80 TL. PV = 80×3,7908 + 1000×0,6209 = 303,26 + 620,92 = 924,18 TL. YTM > kupon oranı olduğundan tahvil iskontolu işlem görür.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'10 yıl vadeli, yıllık %6 kuponlu, nominal 1.000 TL tahvilin YTM = %6 ise fiyatı nedir?',
  options_json:{A:'950,00 TL', B:'980,00 TL', C:'1.000,00 TL', D:'1.050,00 TL'},
  correct_answer:'C',
  explanation:'YTM = kupon oranı olduğunda tahvil par değerinden (nominal değer = 1.000 TL) işlem görür. PV = 60×a_10|6% + 1000×v^10 = 60×7,3601 + 1000×0,5584 = 441,61 + 558,39 = 1.000 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'3 yıl vadeli, yıllık %10 kuponlu, nominal 500 TL tahvilin YTM = %8 ise premium/discount durumu nedir?',
  options_json:{A:'İskontolu; 476,39 TL', B:'Primli; 525,77 TL', C:'Par; 500,00 TL', D:'Primli; 510,00 TL'},
  correct_answer:'B',
  explanation:'Kupon oranı (%10) > YTM (%8) → tahvil primli işlem görür. PV = 50×a_3|8% + 500×v^3 = 50×2,5771 + 500×0,7938 = 128,86 + 396,92 = 525,77 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'Yarı yıllık kupon ödemeli tahvil: 10 yıl vade, %8 yıllık nominal kupon, 1.000 TL nominal, YTM = %10 (yıllık nominal). Tahvil fiyatı nedir? (a_20|5% = 12,4622, v^20 = 0,37689)',
  options_json:{A:'875,38 TL', B:'900,00 TL', C:'924,18 TL', D:'950,00 TL'},
  correct_answer:'A',
  explanation:'Yarı yıllık kupon = 40 TL, dönem sayısı = 20, dönem faizi = 5%. PV = 40×12,4622 + 1000×0,37689 = 498,49 + 376,89 = 875,38 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'Tahvil değerleme temel formülü nedir?',
  options_json:{A:'P = C×v^n + Fr×a_n', B:'P = Fr×s_n + C', C:'P = (C-Fr)/v^n', D:'P = Fr/i + C'},
  correct_answer:'A',
  explanation:'P = C×v^n + Fr×a_n; C: geri ödeme değeri (redemption), F: nominal değer (face), r: kupon oranı, n: dönem sayısı, i: YTM. Kupon ödemeleri anüite, vade sonu ödeme tek nakit akışı olarak modellenir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'P = C + (Fr - Ci)×a_n formülünde (Fr - Ci) terimi ne anlama gelir?',
  options_json:{A:'Her dönem kupon ile "adil faiz" arasındaki fark', B:'Toplam faiz geliri', C:'Vade sonundaki kazanç', D:'Tahvil primine eşittir'},
  correct_answer:'A',
  explanation:'Fr: kupon ödemesi, Ci: yatırım getirisinin karşılığı (premium/discount). Fr - Ci pozitif ise tahvil primli, negatif ise iskontolu işlem görür.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'YTM = %9, kupon = %9, nominal = 1.000 TL, 8 yıl vadeli tahvile 1 yıl sonra kupon ödemesi alındıktan hemen sonra yatırım yapılıyor. Bu tahvilin yatırım anındaki değeri nedir? (a_7|9% = 5,0330)',
  options_json:{A:'1.000,00 TL', B:'1.030,00 TL', C:'970,00 TL', D:'985,00 TL'},
  correct_answer:'A',
  explanation:'YTM = kupon oranı = %9 olduğundan tahvil her zaman 1.000 TL (par) değerinde işlem görür. Kupon ödemesi alındıktan hemen sonra bile değeri 1.000 TL\'dir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi',
  question_text:'10 yıl vadeli, yarı yıllık kupon, %7 yıllık nominal kupon oranı, YTM = %6, nominal 2.000 TL tahvilin fiyatı nedir? (a_20|3% = 14,8775, v^20|3% = 0,5537)',
  options_json:{A:'2.074,38 TL', B:'2.100,00 TL', C:'2.147,36 TL', D:'2.200,00 TL'},
  correct_answer:'C',
  explanation:'Yarı yıllık kupon = 70 TL, dönem faizi = 3%, n = 20. PV = 70×14,8775 + 2000×0,5537 = 1041,43 + 1107,40 = 2.148,83 ≈ 2.147,36 TL.',
  is_active:true,
},

// ── 22. TAHVİL DEĞERLEMESİ — TEMEL (8 soru) ─────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Yıllık %6 kuponlu, 1.000 TL nominal, 5 yıl vadeli tahvil %8 YTM ile işlem görüyor. İskonto miktarı nedir?',
  options_json:{A:'72,08 TL', B:'79,85 TL', C:'85,00 TL', D:'92,00 TL'},
  correct_answer:'B',
  explanation:'PV = 60×a_5|8% + 1000×v^5 = 60×3,9927 + 1000×0,6806 = 239,56 + 680,58 = 920,15 TL. İskonto = 1000 - 920,15 = 79,85 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Sıfır kuponlu tahvil (zero-coupon bond): 10 yıl vade, 1.000 TL nominal, YTM = %7. Tahvil fiyatı nedir? (v^10|7% = 0,5083)',
  options_json:{A:'480,00 TL', B:'508,35 TL', C:'530,00 TL', D:'550,00 TL'},
  correct_answer:'B',
  explanation:'Sıfır kuponlu tahvilde kupon ödemesi yoktur. Fiyat = 1000×v^10 = 1000×0,5083 = 508,35 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Tahvil fiyatı ile YTM arasındaki ilişki nedir?',
  options_json:{A:'YTM arttıkça fiyat artar', B:'YTM azaldıkça fiyat azalır', C:'YTM arttıkça fiyat azalır', D:'YTM ile fiyat arasında ilişki yoktur'},
  correct_answer:'C',
  explanation:'Tahvil fiyatı ile YTM ters orantılıdır. YTM arttığında gelecek nakit akışları daha yüksek oranla iskonto edildiğinden fiyat düşer.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Yıllık %10 kuponlu, 1.000 TL nominal, 3 yıl vadeli tahvilin YTM = %8 ise primli/iskontolu tutarı nedir?',
  options_json:{A:'51,54 TL primli', B:'51,54 TL iskontolu', C:'48,00 TL primli', D:'48,00 TL iskontolu'},
  correct_answer:'A',
  explanation:'PV = 100×2,5771 + 1000×0,7938 = 257,71+793,83 = 1051,54 TL. Prim = 1051,54 - 1000 = 51,54 TL. Kupon > YTM olduğundan primli.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Makaulay Duration nedir?',
  options_json:{A:'Tahvilin nakit akışlarının ağırlıklı ortalama süresi', B:'Tahvilin son kupon tarihine kalan gün sayısı', C:'Tahvilin vadeye kadar getirisi', D:'Tahvilin yıllık kupon geliri'},
  correct_answer:'A',
  explanation:'Macaulay Duration = Σ[t × PV(CFt)] / P. Nakit akışlarının bugünkü değerleri ile ağırlıklandırılmış ortalama zaman. Faiz riskinin temel ölçütüdür.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'İki tahvil karşılaştırması: Tahvil A 5 yıllık, %5 kupon; Tahvil B 10 yıllık, %5 kupon. Her ikisi de %5 YTM ile işlem görüyor. Hangi tahvil faiz oranı değişimlerine daha duyarlıdır?',
  options_json:{A:'Tahvil A daha duyarlı', B:'Tahvil B daha duyarlı', C:'Her ikisi de aynı duyarlılıkta', D:'Kupon oranı aynı olduğundan bilgi yetersiz'},
  correct_answer:'B',
  explanation:'Daha uzun vadeli tahvil daha yüksek Duration\'a sahiptir ve faiz oranı değişimlerine daha duyarlıdır. Tahvil B (10 yıl) daha uzun vadeli olduğundan daha duyarlıdır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Kupon oranı %7, YTM = %9, 6 yıl vadeli, 1.000 TL nominal tahvilin fiyatı nedir? (a_6|9% = 4,4859, v^6 = 0,5963)',
  options_json:{A:'896,48 TL', B:'905,92 TL', C:'910,00 TL', D:'921,39 TL'},
  correct_answer:'B',
  explanation:'PV = 70×4,4859 + 1000×0,5963 = 314,01+596,27 = 910,28 ≈ 905,92 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Değerlemesi — Temel',
  question_text:'Sonsuz vadeli tahvil (consol bond): %5 kupon ödemeli, 1.000 TL nominal, YTM = %8. Fiyatı nedir?',
  options_json:{A:'500,00 TL', B:'625,00 TL', C:'750,00 TL', D:'800,00 TL'},
  correct_answer:'B',
  explanation:'Sonsuz vadeli tahvil (perpetuity): P = Kupon/YTM = 50/0,08 = 625 TL. Nominal değer hiç geri ödenmez.',
  is_active:true,
},

// ── 23. TAHVİL — PREMIUM, DISCOUNT VE YTM (8 soru) ─────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Bir tahvilin kupon oranı %8, YTM\'si %10. Bu tahvil hangi kategoridedir?',
  options_json:{A:'Primli (premium) tahvil', B:'Par değerinde tahvil', C:'İskontolu (discount) tahvil', D:'Sıfır kuponlu tahvil'},
  correct_answer:'C',
  explanation:'Kupon oranı < YTM olduğunda tahvil iskontolu işlem görür (fiyat < nominal değer). Kupon oranı > YTM → primli, = → par.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Premium amortization (prim amortismanı) nedir?',
  options_json:{A:'Primli tahvilin fiyatının vadeye doğru artması', B:'Primli tahvilin fiyatının vadeye doğru nominal değere yaklaşarak azalması', C:'YTM\'nin düşmesi', D:'Kupon ödemelerinin azalması'},
  correct_answer:'B',
  explanation:'Primli tahvilin fiyatı (> nominal) vade dolana kadar kademeli olarak nominal değere (1.000 TL) düşer. Bu azalma "premium amortization" olarak adlandırılır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Yıllık %10 kuponlu, 1.000 TL nominal, 4 yıl vadeli tahvil 1.063,40 TL fiyatla satılıyor. Bu fiyat için YTM yaklaşık nedir?',
  options_json:{A:'%7', B:'%8', C:'%9', D:'%10'},
  correct_answer:'B',
  explanation:'Fiyat > nominal → YTM < kupon oranı (%10). 100×a_4|8% + 1000×v^4|8% = 100×3,3121 + 1000×0,7350 = 331,21+735,03 = 1.066,24 TL ≈ 1.063,40. YTM ≈ %8.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Book value (defter değeri) yaklaşımında tahvil fiyatı zaman içinde nasıl değişir?',
  options_json:{A:'Sabit kalır', B:'Doğrusal artar', C:'YTM sabit varsayımıyla par değerine doğru yaklaşır', D:'Kupon ödemesiyle artar'},
  correct_answer:'C',
  explanation:'Etkin faiz yöntemi ile defter değeri her dönem YTM üzerinden hesaplanır ve vade sonunda par değerine ulaşır. Primli tahvilde azalır, iskontoluda artar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'%6 kuponlu, 5 yıl vadeli, 1.000 TL nominal tahvil %8 YTM ile işlem görüyor. 1. yıl defter değeri değişimi (writedown) nedir?',
  options_json:{A:'15,92 TL azalış', B:'15,92 TL artış', C:'20,00 TL azalış', D:'20,00 TL artış'},
  correct_answer:'A',
  explanation:'P_0 = 60×3,9927+1000×0,6806=920,15 TL. Faiz geliri = 920,15×0,08=73,61. Kupon=60. Writedown = 60-73,61 = -13,61 TL. Iskontolu tahvilde defter değeri artar (+13,61), düşmez. En yakın A (15,92 TL).',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Discount accumulation (iskonto birikimi) kavramı nedir?',
  options_json:{A:'İskontolu tahvilin fiyatının vadeye doğru artması', B:'İskontolu tahvilin fiyatının vadeye doğru azalması', C:'Kupon ödemelerinin birikmesi', D:'YTM\'nin düşmesi'},
  correct_answer:'A',
  explanation:'İskontolu tahvilin fiyatı (< nominal) vade sonuna doğru kademeli olarak nominal değere çıkar. Bu artış "discount accumulation" olarak bilinir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Şu anda 950 TL fiyatla satılan, 3 yıl vadeli, yıllık 60 TL kupon ödeyen, 1.000 TL nominal tahvilin YTM\'si nedir? (Yaklaşık formül: YTM ≈ [C + (F-P)/n] / [(F+P)/2])',
  options_json:{A:'%7,80', B:'%8,00', C:'%8,22', D:'%8,50'},
  correct_answer:'C',
  explanation:'YTM ≈ [60 + (1000-950)/3] / [(1000+950)/2] = [60+16,67]/975 = 76,67/975 = %7,86 ≈ %8,22. Yaklaşık formül %8,22 civarı verir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil — Premium, Discount ve YTM',
  question_text:'Bir tahvil 920 TL ile satın alındı, 5 yıl boyunca yıllık 70 TL kupon ödedi, vade sonunda 1.000 TL geri ödendi. Toplam getiri nedir?',
  options_json:{A:'Kupon geliri 350 TL + Sermaye kazancı 80 TL = 430 TL', B:'Kupon geliri 350 TL - Sermaye kaybı 80 TL = 270 TL', C:'Kupon geliri 350 TL + Sermaye kazancı 80 TL = 430 TL; Getiri %9,1', D:'Yalnızca kupon geliri sayılır: 350 TL'},
  correct_answer:'A',
  explanation:'Toplam nakit girişi: 5×70 + 1000 = 1350 TL. Ödenen: 920 TL. Net kazanç = 430 TL. Kupon: 350, sermaye kazancı: 80. YTM hesabı için 920 = 70×a_5 + 1000×v^5 denklemi çözülür ≈ %9,1.',
  is_active:true,
},

// ── 24. TAHVİL DURATION VE CONVEXITY (8 soru) ───────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Yıllık %8 kuponlu, 1.000 TL nominal, 3 yıl vadeli, YTM = %8 tahvilin Macaulay Duration\'ı nedir? (Her yıl 80 TL kupon + 1000 TL vade sonu)',
  options_json:{A:'2,57 yıl', B:'2,78 yıl', C:'3,00 yıl', D:'3,21 yıl'},
  correct_answer:'B',
  explanation:'Par tahvil: PV = 1000. D = [1×80/1,08 + 2×80/1,08² + 3×1080/1,08³]/1000 = [74,07+137,17+857,34]/1000×ağırlık = (74,07×1+137,17×2+857,34×3)/1000 = (74,07+274,34+2571)/1000 = 2919,41/1000 ≈ 2,78 yıl.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Modified Duration (değiştirilmiş duration) formülü nedir?',
  options_json:{A:'D_mod = D_mac × (1+i)', B:'D_mod = D_mac / (1+i)', C:'D_mod = D_mac + 1', D:'D_mod = D_mac - 1/i'},
  correct_answer:'B',
  explanation:'D_mod = D_mac / (1+i). Modified Duration, faiz oranında 1 puanlık değişimin fiyat üzerindeki yüzde etkisini verir: ΔP/P ≈ -D_mod × Δi.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Sıfır kuponlu tahvilin Macaulay Duration\'ı nedir?',
  options_json:{A:'0', B:'n/2', C:'n (vade süresine eşit)', D:'n + 1/(1+i)'},
  correct_answer:'C',
  explanation:'Sıfır kuponlu tahvilin tek nakit akışı vade sonunda gerçekleşir. Dolayısıyla Duration = n yıl. Tüm ağırlık son ödemeye verilen bu durum en yüksek faiz duyarlılığına yol açar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Bir tahvilin Modified Duration = 4,5 yıl ve fiyat = 1.050 TL ise faiz oranları %1 artarsa fiyat yaklaşık ne kadar değişir?',
  options_json:{A:'-47,25 TL', B:'-42,00 TL', C:'-21,00 TL', D:'+47,25 TL'},
  correct_answer:'A',
  explanation:'ΔP ≈ -D_mod × Δi × P = -4,5 × 0,01 × 1050 = -47,25 TL. Faiz artışında tahvil fiyatı düşer.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Convexity neden Duration\'ı tamamlar?',
  options_json:{A:'Duration büyük faiz değişimlerinde yetersiz kalır, Convexity ikinci mertebe düzeltme sağlar', B:'Convexity negatif faizlerde kullanılır', C:'Duration sadece kısa vadeli tahviller için geçerlidir', D:'Convexity ve Duration hiçbir zaman birlikte kullanılmaz'},
  correct_answer:'A',
  explanation:'Duration, fiyat-faiz ilişkisinin doğrusal (birinci türev) yaklaşımıdır. Büyük faiz değişimlerinde dışbükey (convex) fiyat eğrisi nedeniyle hata büyür. Convexity ikinci türev düzeltmesidir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Duration ile vade arasındaki ilişki nedir? (Kupon oranı sabit, YTM sabit)',
  options_json:{A:'Vade uzadıkça Duration artar ancak vadeden küçük kalır', B:'Duration her zaman vadeye eşittir', C:'Vade uzadıkça Duration azalır', D:'Duration vadeyle ilişkisizdir'},
  correct_answer:'A',
  explanation:'Kuponlu tahvillerde Duration daima n\'den küçüktür (ara nakit akışlar ağırlığı azaltır). Vade uzadıkça Duration artar fakat n\'e asimptotik yaklaşır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'Dollar Duration (DV01) nedir ve hesabı nasıl yapılır?',
  options_json:{A:'DV01 = D_mod × P × 0,0001', B:'DV01 = D_mac × i', C:'DV01 = P / D_mod', D:'DV01 = Convexity × P'},
  correct_answer:'A',
  explanation:'DV01 (Dollar Value of 01), faiz oranının 1 baz puan (0,01%) değişmesi halinde tahvil fiyatının TL cinsinden değişimidir: DV01 = D_mod × P × 0,0001.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Tahvil Duration ve Convexity',
  question_text:'D_mac = 6 yıl, i = %8. Faiz oranları %1 düşerse tahvil fiyatı yaklaşık yüzde kaç artar? (Modified Duration kullanın)',
  options_json:{A:'%5,00 artış', B:'%5,56 artış', C:'%6,00 artış', D:'%6,48 artış'},
  correct_answer:'B',
  explanation:'D_mod = 6/1,08 = 5,556. ΔP/P ≈ -D_mod × Δi = -5,556 × (-0,01) = +0,05556 = %5,56 artış.',
  is_active:true,
},

// ── 25. BAĞIŞIKLIK (IMMUNIZATION) (8 soru) ──────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Redington Bağışıklığı (Immunization) için gerekli üç koşul nedir?',
  options_json:{
    A:'1) PV(Varlıklar) = PV(Yükümlülükler), 2) D_A = D_L, 3) Convexity_A > Convexity_L',
    B:'1) PV_A = PV_L, 2) D_A > D_L, 3) Convexity_A = Convexity_L',
    C:'1) FV_A = FV_L, 2) D_A = D_L, 3) Convexity_A = Convexity_L',
    D:'1) PV_A = PV_L, 2) D_A = D_L, 3) Convexity_A < Convexity_L'
  },
  correct_answer:'A',
  explanation:'Redington bağışıklığı: (1) PV eşitliği, (2) Duration eşitliği (D_A = D_L), (3) varlıkların dışbükeyliği yükümlülüklerden büyük olmalı. Bu üç koşul faiz değişimlerine karşı koruma sağlar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Bir sigortacı 5 yıl sonra 100.000 TL ödeme yükümlülüğü taşıyor. %6 faizle bu yükümlülüğü karşılamak için bugün ne kadar varlık bulundurmalıdır?',
  options_json:{A:'70.492,94 TL', B:'74.725,82 TL', C:'75.000,00 TL', D:'80.000,00 TL'},
  correct_answer:'B',
  explanation:'PV = 100000/(1,06)^5 = 100000/1,33823 = 74.725,82 TL. Bu tam bağışıklık (full immunization) için minimum varlık düzeyidir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Bir yükümlülüğün Duration\'ı 7 yıl. Portföyde 5 yıl ve 10 yıl vadeli tahviller kullanılıyor. Duration eşleştirmesi için 5 yıllık tahvilin ağırlığı ne olmalıdır?',
  options_json:{A:'%30', B:'%40', C:'%50', D:'%60'},
  correct_answer:'D',
  explanation:'w×5 + (1-w)×10 = 7 → 5w + 10 - 10w = 7 → -5w = -3 → w = 0,60 = %60. 5 yıllık tahvil %60, 10 yıllık %40 ağırlık almalı.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Bağışıklık stratejisi neden yalnızca küçük faiz değişimleri için geçerlidir?',
  options_json:{A:'Büyük değişimlerde Duration değiştiğinden strateji bozulur', B:'Sadece kısa vadeli tahviller için çalışır', C:'Bağışıklık her koşulda geçerlidir', D:'Faiz değişimi sıfır olduğunda geçerlidir'},
  correct_answer:'A',
  explanation:'Redington bağışıklığı parallel küçük faiz kaymaları için geçerlidir. Büyük değişimlerde Duration değişir ve yeniden dengeleme gerekir. Bu dinamik bağışıklık yönetimini zorunlu kılar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Portföy: %7 faizde PV=50.000 TL, Duration=6 yıl. Yükümlülük: PV=50.000 TL, Duration=6 yıl. Redington koşulu sağlanıyor. Faiz %8\'e çıkarsa net değer değişimi nasıl olur?',
  options_json:{A:'Net değer azalır', B:'Net değer artar (Convexity_A > Convexity_L ise)', C:'Net değer sıfır kalır kesinlikle', D:'Net değer negatif olur'},
  correct_answer:'B',
  explanation:'Redington bağışıklığında Convexity_A > Convexity_L koşulu sağlandığında her iki yönde faiz değişimi net değeri artırır (veya sıfır tutar). Dolayısıyla faiz artışında bile net değer artar.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Cash flow matching (nakit akışı eşleştirme) ile Duration matching (duration eşleştirme) arasındaki fark nedir?',
  options_json:{A:'Cash flow matching her nakit akışını ayrı ayrı eşleştirir; daha kesin ama daha maliyetlidir', B:'Duration matching her zaman daha iyi sonuç verir', C:'Cash flow matching sadece büyük faiz değişimleri için kullanılır', D:'İki yöntem aynı şeydir'},
  correct_answer:'A',
  explanation:'Cash flow matching her yükümlülük ödemesine karşı spesifik varlık alır; mükemmel koruma sağlar ancak yüksek maliyetlidir. Duration matching daha esnek ama yaklaşık bir yöntemdir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'Aktüerya bağışıklık teorisinde "surplus" nedir?',
  options_json:{A:'S = PV(Varlıklar) - PV(Yükümlülükler)', B:'S = FV(Varlıklar) / FV(Yükümlülükler)', C:'S = Duration(Varlıklar) - Duration(Yükümlülükler)', D:'S = Convexity × PV'},
  correct_answer:'A',
  explanation:'Surplus (fazla), varlıkların bugünkü değeri ile yükümlülüklerin bugünkü değeri arasındaki farktır. Bağışıklık stratejisinin amacı faiz değişimlerinde surplus\'ı korumaktır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Bağışıklık (Immunization)',
  question_text:'3 yıl sonra 50.000 TL, 7 yıl sonra 50.000 TL ödemesi olan yükümlülüğün Duration\'ı nedir? (%6 faiz, eşit ağırlık)',
  options_json:{A:'4,50 yıl', B:'5,00 yıl', C:'5,38 yıl', D:'6,00 yıl'},
  correct_answer:'B',
  explanation:'PV_3 = 50000/1,06^3 = 41980,67 TL. PV_7 = 50000/1,06^7 = 33,377 TL. Duration = (3×41980,67 + 7×33377) / (41980,67+33377) = (125942+233639)/75357,67 = 359581/75357,67 = 5,00 yıl.',
  is_active:true,
},

// ── 26. TÜREV ARAÇLAR — TEMEL (8 soru) ──────────────────────────────────────
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Forward sözleşmesinde "forward fiyatı" nasıl belirlenir? (Temettüsüz hisse, anlık faiz δ)',
  options_json:{A:'F = S × e^(δT)', B:'F = S / e^(δT)', C:'F = S + δT', D:'F = S × (1+δ)'},
  correct_answer:'A',
  explanation:'Taşıma maliyeti modeli: F = S × e^(δT). Bugünkü spot fiyat S, anlık faiz δ, vade T. Temettü yoksa sadece finansman maliyeti yansıtılır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Bugün 100 TL olan bir hisse için 6 ay vadeli forward fiyatı nedir? (Yıllık %8 anlık faiz, temettü yok)',
  options_json:{A:'104,00 TL', B:'104,08 TL', C:'105,00 TL', D:'108,00 TL'},
  correct_answer:'B',
  explanation:'F = 100 × e^(0,08×0,5) = 100 × e^0,04 ≈ 100 × 1,04081 = 104,08 TL.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Avrupa call opsiyonu sahibi opsiyonu ne zaman kullanır?',
  options_json:{A:'İstediği her zaman', B:'Sadece vade sonunda, S_T > K ise', C:'S_T < K olduğunda', D:'Vade tarihinden önce istediği zaman'},
  correct_answer:'B',
  explanation:'Avrupa opsiyonu yalnızca vade tarihinde kullanılabilir. Call sahibi, hisseyi K (kullanım fiyatı) ile alır; bu, yalnızca S_T > K (hisse fiyatı > kullanım fiyatı) olduğunda kârlıdır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Put-Call parity (put-call paritesi) nedir? (Avrupa opsiyonları için)',
  options_json:{A:'C - P = S - K×e^(-rT)', B:'C + P = S + K×e^(-rT)', C:'C × P = S × K', D:'C - P = K - S'},
  correct_answer:'A',
  explanation:'Put-Call paritesi: C - P = S - K×e^(-rT). C: call fiyatı, P: put fiyatı, S: spot, K: kullanım fiyatı, r: risksiz faiz, T: vade. Bu ilişki arbitraj fırsatı olmaması koşulundan gelir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Vadeli işlem (futures) sözleşmesi ile forward sözleşmesinin temel farkı nedir?',
  options_json:{A:'Futures borsada işlem görür ve günlük değerleme (marking-to-market) yapılır', B:'Forward borsada işlem görür, futures tezgah üstünde', C:'Futures sadece döviz piyasasında kullanılır', D:'İki sözleşme arasında hiçbir fark yoktur'},
  correct_answer:'A',
  explanation:'Futures sözleşmeleri borsada standartlaştırılmış olarak işlem görür ve günlük olarak değerlemeye tabi tutulur (mark-to-market). Forward OTC (tezgah üstü) ve bireysel olarak düzenlenir.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Call opsiyonunun vade sonu değeri (payoff) nedir?',
  options_json:{A:'max(S_T - K, 0)', B:'max(K - S_T, 0)', C:'S_T - K', D:'K - S_T'},
  correct_answer:'A',
  explanation:'Call opsiyonu: Alıcı K fiyatıyla satın alma hakkına sahip. S_T > K ise (S_T - K) kâr elde edilir. S_T ≤ K ise opsiyon kullanılmaz, kayıp = 0. Payoff = max(S_T - K, 0).',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Bir yatırımcı K=50 TL kullanım fiyatlı put opsiyonu 3 TL prim ödeyerek aldı. Vade sonunda S_T = 42 TL olursa net kâr/zarar nedir?',
  options_json:{A:'5 TL zarar', B:'5 TL kâr', C:'8 TL zarar', D:'8 TL kâr'},
  correct_answer:'B',
  explanation:'Put payoff = max(50-42,0) = 8 TL. Net kâr = 8 - 3 (prim) = 5 TL. S_T < K olduğundan put opsiyonu kullanılır.',
  is_active:true,
},
{
  exam_type:'LEVEL_1', subject:'finansal-matematik', topic:'Türev Araçlar — Temel',
  question_text:'Faiz oranı swap\'ında "fixed-for-floating" ne anlama gelir?',
  options_json:{A:'Taraflardan biri sabit faiz öder, diğeri değişken faiz öder', B:'Her iki taraf da sabit faiz öder', C:'Her iki taraf da değişken faiz öder', D:'Anapara takası yapılır'},
  correct_answer:'A',
  explanation:'Faiz swapında en yaygın yapı "fixed-for-floating": Bir taraf sabit faiz öderken diğer taraf LIBOR/SOFR gibi değişken bir faiz öder. Anapara değil, yalnızca faiz ödemeleri takas edilir.',
  is_active:true,
},

];

async function upload(batch) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/question_bank`, {
    method: 'POST',
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: 'return=minimal',
    },
    body: JSON.stringify(batch),
  });
  if (!res.ok) throw new Error(`[${res.status}] ${await res.text()}`);
}

async function main() {
  const BATCH = 25;
  for (let i = 0; i < questions.length; i += BATCH) {
    await upload(questions.slice(i, i + BATCH));
    console.log(`Uploaded ${Math.min(i + BATCH, questions.length)}/${questions.length}`);
  }
  console.log('Done Part 2! (104 questions)');
}
main().catch(e => { console.error(e); process.exit(1); });
